/* Banque — Prépa deuxième année (MP · PC · PSI · MPI) */
(function () {

  L.addSujets("spe", "fiche", [
    {
      t: "Fiche 1 — Séries numériques", st: "Critères de convergence, comparaison, séries alternées", diff: "★★",
      desc: "Reconnaître la nature d'une série et justifier proprement.",
      intro: "Toujours commencer par le terme général : signe, équivalent, puis critère adapté.",
      ex: [
        {
          t: "Natures de séries",
          c: ["Déterminer la nature des séries de terme général :",
            ["q", "$u_{n} = \\dfrac{n+1}{n^{3}+2}$", "$v_{n} = \\dfrac{1}{n\\ln n}$ $(n\\geqslant 2)$",
              "$w_{n} = \\left(1 - \\dfrac{1}{n}\\right)^{n^{2}}$", "$t_{n} = \\dfrac{(-1)^{n}}{\\sqrt{n}}$",
              "$s_{n} = \\dfrac{n!}{n^{\\,n}}$"]],
          sol: [["q", "$u_{n} \\sim \\dfrac{1}{n^{2}}$, série de Riemann convergente.",
            "Comparaison série-intégrale : $\\displaystyle\\int^{X}\\frac{\\mathrm{d}t}{t\\ln t} = \\ln\\ln X \\to +\\infty$, la série diverge.",
            "$w_{n} = \\exp\\!\\left(n^{2}\\ln\\!\\left(1-\\tfrac{1}{n}\\right)\\right) \\sim \\mathrm{e}^{-n}$ : convergente.",
            "Série alternée dont le module décroît vers $0$ : convergente (mais pas absolument).",
            "Règle de d'Alembert : $\\dfrac{s_{n+1}}{s_{n}} = \\left(\\dfrac{n}{n+1}\\right)^{n} \\to \\mathrm{e}^{-1} < 1$ : convergente."]],
        },
        {
          t: "Comparaison série-intégrale",
          c: ["Soit $H_{n} = \\displaystyle\\sum_{k=1}^{n}\\frac{1}{k}$.",
            ["q", "Montrer que $\\ln(n+1) \\leqslant H_{n} \\leqslant 1 + \\ln n$.",
              "En déduire $H_{n} \\sim \\ln n$.",
              "Montrer que $u_{n} = H_{n} - \\ln n$ converge (constante d'Euler $\\gamma$).",
              "En déduire un équivalent de $\\displaystyle\\sum_{k=n+1}^{2n}\\frac{1}{k}$."]],
          sol: [["q", "Encadrement de $\\tfrac{1}{k}$ par $\\displaystyle\\int_{k}^{k+1}\\tfrac{\\mathrm{d}t}{t}$ et $\\displaystyle\\int_{k-1}^{k}\\tfrac{\\mathrm{d}t}{t}$, puis sommation.",
            "Diviser l'encadrement par $\\ln n$ et passer à la limite.",
            "$u_{n+1}-u_{n} = \\tfrac{1}{n+1} - \\ln\\!\\left(1+\\tfrac{1}{n}\\right) = O\\!\\left(\\tfrac{1}{n^{2}}\\right)$ : la série télescopique converge absolument, donc $(u_{n})$ converge.",
            "$H_{2n} - H_{n} = \\ln 2 + u_{2n} - u_{n} \\to \\ln 2$ : la somme tend vers $\\ln 2$."]],
        },
        {
          t: "Développements asymptotiques",
          c: [["q", "Étudier la nature de $\\displaystyle\\sum \\left(\\sqrt{n+1}-\\sqrt{n}\\right)$.",
            "Étudier la nature de $\\displaystyle\\sum \\ln\\!\\left(1 + \\frac{(-1)^{n}}{\\sqrt{n}}\\right)$ pour $n \\geqslant 2$.",
            "Étudier la nature de $\\displaystyle\\sum \\frac{(-1)^{n}}{n + (-1)^{n}}$."]],
          sol: [["q", "$\\sqrt{n+1}-\\sqrt{n} = \\dfrac{1}{\\sqrt{n+1}+\\sqrt{n}} \\sim \\dfrac{1}{2\\sqrt{n}}$ : divergente (Riemann $\\tfrac{1}{2} \\leqslant 1$).",
            "$\\ln(1+x) = x - \\tfrac{x^{2}}{2} + o(x^{2})$ donne $\\dfrac{(-1)^{n}}{\\sqrt{n}} - \\dfrac{1}{2n} + o\\!\\left(\\tfrac{1}{n}\\right)$ : somme d'une série alternée convergente et d'une série divergente, donc divergente.",
            "$\\dfrac{(-1)^{n}}{n+(-1)^{n}} = \\dfrac{(-1)^{n}}{n} - \\dfrac{1}{n^{2}} + o\\!\\left(\\tfrac{1}{n^{2}}\\right)$ : convergente."]],
        },
        {
          t: "Calculs de sommes",
          c: ["Calculer les sommes suivantes :",
            ["q", "$\\displaystyle\\sum_{n=0}^{+\\infty}\\frac{1}{2^{\\,n}}$", "$\\displaystyle\\sum_{n=1}^{+\\infty}\\frac{1}{n(n+1)}$",
              "$\\displaystyle\\sum_{n=0}^{+\\infty}\\frac{n}{2^{\\,n}}$", "$\\displaystyle\\sum_{n=0}^{+\\infty}\\frac{1}{n!}$"]],
          sol: [["q", "$2$ (série géométrique).", "$1$ (télescopage).",
            "En dérivant $\\displaystyle\\sum x^{n} = \\tfrac{1}{1-x}$ puis en multipliant par $x$ : $\\dfrac{x}{(1-x)^{2}}$, soit $2$ en $x = \\tfrac{1}{2}$.",
            "$\\mathrm{e}$."]],
        },
      ],
    },
    {
      t: "Fiche 2 — Suites et séries de fonctions", st: "Convergence simple, uniforme, normale, interversions", diff: "★★★",
      desc: "Les trois modes de convergence et les théorèmes de passage à la limite.",
      ex: [
        {
          t: "Modes de convergence",
          c: ["Soit $f_{n}(x) = x^{\\,n}(1-x)$ sur $[0\\,;\\,1]$.",
            ["q", "Étudier la convergence simple de $(f_{n})$.",
              "Calculer $\\|f_{n}\\|_{\\infty}$ et en déduire la convergence uniforme.",
              "Calculer $\\displaystyle\\lim_{n\\to+\\infty}\\int_{0}^{1}f_{n}(x)\\,\\mathrm{d}x$ de deux façons."]],
          sol: [["q", "Pour $x \\in [0\\,;\\,1[$, $x^{n}\\to 0$ ; en $1$, $f_{n}(1) = 0$ : convergence simple vers la fonction nulle.",
            "$f_{n}'(x) = x^{\\,n-1}(n - (n+1)x)$ : maximum en $x_{n} = \\tfrac{n}{n+1}$, $\\|f_{n}\\|_{\\infty} = \\left(\\tfrac{n}{n+1}\\right)^{n}\\tfrac{1}{n+1} \\sim \\dfrac{1}{\\mathrm{e}n} \\to 0$ : convergence uniforme.",
            "Par convergence uniforme la limite est $0$ ; par calcul direct, $\\displaystyle\\int_{0}^{1}f_{n} = \\tfrac{1}{n+1}-\\tfrac{1}{n+2} \\to 0$."]],
        },
        {
          t: "Un contre-exemple",
          c: ["Soit $g_{n}(x) = n\\,x\\,\\mathrm{e}^{-nx}$ sur $[0\\,;\\,1]$.",
            ["q", "Étudier la convergence simple de $(g_{n})$.",
              "La convergence est-elle uniforme sur $[0\\,;\\,1]$ ?",
              "Et sur $[a\\,;\\,1]$ avec $a > 0$ ?",
              "Calculer $\\displaystyle\\lim_{n}\\int_{0}^{1}g_{n}$ et conclure."]],
          sol: [["q", "Pour $x>0$, $g_{n}(x)\\to 0$ ; $g_{n}(0) = 0$ : convergence simple vers $0$.",
            "$\\|g_{n}\\|_{\\infty} = g_{n}\\!\\left(\\tfrac{1}{n}\\right) = \\mathrm{e}^{-1}$, qui ne tend pas vers $0$ : pas de convergence uniforme.",
            "Sur $[a\\,;\\,1]$, pour $n$ assez grand $g_{n}$ est décroissante et $\\|g_{n}\\|_{\\infty} = na\\,\\mathrm{e}^{-na}\\to 0$ : convergence uniforme.",
            "$\\displaystyle\\int_{0}^{1}g_{n} = \\big[-(x+\\tfrac1n)\\mathrm{e}^{-nx}\\big]_{0}^{1} = \\tfrac{1}{n} - \\left(1+\\tfrac1n\\right)\\mathrm{e}^{-n} \\to 0$ : ici l'interversion est valable bien que la convergence ne soit pas uniforme sur $[0\\,;\\,1]$."]],
        },
        {
          t: "Série de fonctions",
          c: ["On pose $S(x) = \\displaystyle\\sum_{n=1}^{+\\infty}\\frac{(-1)^{n}}{n + x^{2}}$ pour $x\\in\\mathbb{R}$.",
            ["q", "Montrer que la série converge simplement sur $\\mathbb{R}$.",
              "Montrer qu'il n'y a pas convergence normale.",
              "Montrer la convergence uniforme sur $\\mathbb{R}$ (majoration du reste d'une série alternée).",
              "En déduire que $S$ est continue sur $\\mathbb{R}$.",
              "Déterminer $\\displaystyle\\lim_{x\\to+\\infty}S(x)$."]],
          sol: [["q", "Série alternée dont le module décroît vers $0$ à $x$ fixé.",
            "$\\sup_{x}\\left|\\dfrac{(-1)^{n}}{n+x^{2}}\\right| = \\dfrac{1}{n}$, terme général d'une série divergente.",
            "Le reste vérifie $|R_{n}(x)| \\leqslant \\dfrac{1}{n+1+x^{2}} \\leqslant \\dfrac{1}{n+1}$ : $\\|R_{n}\\|_{\\infty}\\to 0$.",
            "Somme d'une série uniformément convergente de fonctions continues.",
            "Chaque terme tend vers $0$ et $|S(x)| \\leqslant \\dfrac{1}{1+x^{2}}$ (majoration du premier terme) : la limite est $0$."]],
        },
        {
          t: "Interversion limite-intégrale",
          c: ["Justifier les égalités suivantes :",
            ["q", "$\\displaystyle\\int_{0}^{1}\\sum_{n=0}^{+\\infty}x^{\\,n}\\,\\mathrm{d}x$ : la série converge-t-elle uniformément sur $[0\\,;\\,1[$ ?",
              "Montrer que $\\displaystyle\\int_{0}^{1}\\frac{\\ln t}{t-1}\\mathrm{d}t = \\sum_{n=1}^{+\\infty}\\frac{1}{n^{2}}$.",
              "En déduire une méthode numérique d'approximation de $\\tfrac{\\pi^{2}}{6}$."]],
          sol: [["q", "Pas de convergence uniforme sur $[0\\,;\\,1[$ (le reste vaut $\\tfrac{x^{n+1}}{1-x}$, non borné), mais convergence uniforme sur tout $[0\\,;\\,a]$, ce qui suffit pour intégrer sur $[0\\,;\\,a]$.",
            "$\\dfrac{\\ln t}{t-1} = -\\ln t\\displaystyle\\sum_{n\\geqslant 0}t^{\\,n}$ ; les termes sont positifs, le théorème d'intégration terme à terme s'applique et $\\displaystyle\\int_{0}^{1}(-t^{n}\\ln t)\\,\\mathrm{d}t = \\dfrac{1}{(n+1)^{2}}$.",
            "Sommer les premiers termes de $\\sum \\tfrac{1}{n^{2}}$ avec un contrôle du reste par $\\displaystyle\\int_{n}^{+\\infty}\\tfrac{\\mathrm{d}t}{t^{2}} = \\tfrac{1}{n}$."]],
        },
      ],
    },
    {
      t: "Fiche 3 — Séries entières", st: "Rayon de convergence, somme, développements", diff: "★★★",
      desc: "Calculer un rayon, sommer une série entière, développer une fonction.",
      ex: [
        {
          t: "Rayons de convergence",
          c: ["Déterminer le rayon de convergence de $\\sum a_{n}z^{\\,n}$ pour :",
            ["q", "$a_{n} = \\dfrac{2^{\\,n}}{n!}$", "$a_{n} = n^{3}$", "$a_{n} = \\dfrac{1}{\\sqrt{n}}$",
              "$a_{n} = \\dfrac{n!}{n^{\\,n}}$", "$a_{n} = \\sin n$"]],
          sol: [["q", "$R = +\\infty$ (d'Alembert : le rapport tend vers $0$).", "$R = 1$.", "$R = 1$.",
            "$\\dfrac{a_{n+1}}{a_{n}} \\to \\mathrm{e}^{-1}$ : $R = \\mathrm{e}$.",
            "$(a_{n})$ est bornée et ne tend pas vers $0$ : $R = 1$."]],
        },
        {
          t: "Calculs de sommes",
          c: ["Pour $|x| < 1$, calculer :",
            ["q", "$\\displaystyle\\sum_{n\\geqslant 1} n x^{\\,n}$", "$\\displaystyle\\sum_{n\\geqslant 2} n(n-1)x^{\\,n}$",
              "$\\displaystyle\\sum_{n\\geqslant 0}\\frac{x^{\\,n}}{n+1}$", "$\\displaystyle\\sum_{n\\geqslant 0}\\frac{x^{2n}}{(2n)!}$"]],
          sol: [["q", "$\\dfrac{x}{(1-x)^{2}}$.", "$\\dfrac{2x^{2}}{(1-x)^{3}}$.",
            "$\\dfrac{-\\ln(1-x)}{x}$ pour $x \\neq 0$, et $1$ en $0$.", "$\\mathrm{ch}\\,x$."]],
        },
        {
          t: "Développements en série entière",
          c: ["Développer en série entière au voisinage de $0$, en précisant le rayon :",
            ["q", "$\\dfrac{1}{1+x^{2}}$", "$\\arctan x$", "$\\ln(1+x)$", "$\\dfrac{1}{(1-x)(2-x)}$"]],
          sol: [["q", "$\\displaystyle\\sum_{n\\geqslant 0}(-1)^{n}x^{2n}$, $R = 1$.",
            "$\\displaystyle\\sum_{n\\geqslant 0}\\frac{(-1)^{n}x^{2n+1}}{2n+1}$, $R = 1$.",
            "$\\displaystyle\\sum_{n\\geqslant 1}\\frac{(-1)^{n+1}x^{\\,n}}{n}$, $R = 1$.",
            "Décomposition : $\\dfrac{1}{1-x} - \\dfrac{1}{2-x} = \\displaystyle\\sum_{n\\geqslant 0}\\left(1 - \\tfrac{1}{2^{\\,n+1}}\\right)x^{\\,n}$, $R = 1$."]],
        },
        {
          t: "Série entière et équation différentielle",
          c: ["On cherche une solution développable en série entière de $(1+x)y' = y$, avec $y(0) = 1$.",
            ["q", "Déterminer une relation de récurrence sur les coefficients $a_{n}$.",
              "En déduire $a_{n}$ et le rayon de convergence.",
              "Reconnaître la fonction somme.",
              "Application : retrouver le développement de $\\sqrt{1+x}$ en résolvant $2(1+x)y' = y$."]],
          sol: [["q", "$(n+1)a_{n+1} + na_{n} = a_{n}$, soit $a_{n+1} = \\dfrac{1-n}{n+1}a_{n}$.",
            "$a_{0}=1$, $a_{1}=1$, puis $a_{n} = 0$ pour $n \\geqslant 2$ : la série est le polynôme $1+x$, de rayon infini.",
            "La solution est $y = 1+x$, ce que l'on vérifie directement.",
            "Avec $2(1+x)y' = y$ : $a_{n+1} = \\dfrac{1-2n}{2(n+1)}a_{n}$, qui redonne les coefficients binomiaux généralisés de $(1+x)^{1/2}$, de rayon $1$."]],
        },
      ],
    },
    {
      t: "Fiche 4 — Intégration sur un intervalle quelconque", st: "Intégrales généralisées, comparaison, convergence dominée", diff: "★★★",
      desc: "Convergence des intégrales impropres et théorèmes d'interversion.",
      ex: [
        {
          t: "Natures d'intégrales",
          c: ["Étudier la convergence de :",
            ["q", "$\\displaystyle\\int_{1}^{+\\infty}\\frac{\\mathrm{d}t}{t^{2}+1}$", "$\\displaystyle\\int_{0}^{1}\\frac{\\mathrm{d}t}{\\sqrt{t}}$",
              "$\\displaystyle\\int_{0}^{+\\infty}\\mathrm{e}^{-t^{2}}\\mathrm{d}t$", "$\\displaystyle\\int_{1}^{+\\infty}\\frac{\\ln t}{t}\\mathrm{d}t$",
              "$\\displaystyle\\int_{0}^{+\\infty}\\frac{\\sin t}{t}\\mathrm{d}t$"]],
          sol: [["q", "Convergente ($\\sim t^{-2}$), et vaut $\\tfrac{\\pi}{4}$.",
            "Convergente (Riemann en $0$, exposant $\\tfrac12 < 1$), vaut $2$.",
            "Convergente : $\\mathrm{e}^{-t^{2}} \\leqslant \\mathrm{e}^{-t}$ pour $t\\geqslant 1$.",
            "Divergente : primitive $\\tfrac{(\\ln t)^{2}}{2} \\to +\\infty$.",
            "Semi-convergente : convergente par IPP, mais $\\displaystyle\\int\\left|\\tfrac{\\sin t}{t}\\right|$ diverge."]],
        },
        {
          t: "Intégrales à paramètre",
          c: ["On pose $F(x) = \\displaystyle\\int_{0}^{+\\infty}\\frac{\\mathrm{e}^{-xt}}{1+t^{2}}\\,\\mathrm{d}t$ pour $x \\geqslant 0$.",
            ["q", "Justifier que $F$ est bien définie sur $[0\\,;\\,+\\infty[$.",
              "Montrer que $F$ est continue sur $[0\\,;\\,+\\infty[$ (domination).",
              "Calculer $F(0)$.",
              "Déterminer $\\displaystyle\\lim_{x\\to+\\infty}F(x)$.",
              "Montrer que $F$ est de classe $\\mathcal{C}^{1}$ sur $]0\\,;\\,+\\infty[$."]],
          sol: [["q", "$0 \\leqslant \\dfrac{\\mathrm{e}^{-xt}}{1+t^{2}} \\leqslant \\dfrac{1}{1+t^{2}}$, intégrable sur $[0\\,;\\,+\\infty[$.",
            "La domination précédente est indépendante de $x$ et l'intégrande est continue en $x$ : théorème de continuité sous l'intégrale.",
            "$F(0) = \\displaystyle\\int_{0}^{+\\infty}\\frac{\\mathrm{d}t}{1+t^{2}} = \\frac{\\pi}{2}$.",
            "Par convergence dominée, $F(x)\\to 0$.",
            "$\\left|\\partial_{x}\\right| = \\dfrac{t\\,\\mathrm{e}^{-xt}}{1+t^{2}} \\leqslant t\\,\\mathrm{e}^{-at}$ pour $x \\geqslant a > 0$, intégrable : dérivation sous l'intégrale sur $[a\\,;\\,+\\infty[$, pour tout $a>0$."]],
        },
        {
          t: "Convergence dominée",
          c: ["Calculer les limites suivantes en justifiant :",
            ["q", "$\\displaystyle\\lim_{n\\to+\\infty}\\int_{0}^{1}\\frac{n\\,\\mathrm{d}t}{1+n^{2}t^{2}}$",
              "$\\displaystyle\\lim_{n\\to+\\infty}\\int_{0}^{+\\infty}\\frac{\\mathrm{d}t}{1+t^{\\,n}}$ (on distinguera $t<1$ et $t>1$)",
              "$\\displaystyle\\lim_{n\\to+\\infty}\\int_{0}^{1}n\\ln\\!\\left(1+\\frac{t}{n}\\right)\\mathrm{d}t$"]],
          sol: [["q", "Changement $u = nt$ : $\\displaystyle\\int_{0}^{n}\\frac{\\mathrm{d}u}{1+u^{2}} \\to \\frac{\\pi}{2}$ (pas de domination : la masse s'échappe).",
            "La limite simple vaut $1$ sur $[0\\,;\\,1[$ et $0$ sur $]1\\,;\\,+\\infty[$, avec domination par $\\tfrac{1}{1+t^{2}}$ pour $n\\geqslant 2$ sur $[1;+\\infty[$ : la limite vaut $1$.",
            "$n\\ln\\!\\left(1+\\tfrac{t}{n}\\right) \\to t$ avec domination par $t$ : la limite vaut $\\displaystyle\\int_{0}^{1}t\\,\\mathrm{d}t = \\tfrac{1}{2}$."]],
        },
        {
          t: "Intégrale de Gauss",
          c: ["On pose $I = \\displaystyle\\int_{0}^{+\\infty}\\mathrm{e}^{-t^{2}}\\mathrm{d}t$ et $u_{n} = \\displaystyle\\int_{0}^{\\sqrt{n}}\\left(1-\\frac{t^{2}}{n}\\right)^{n}\\mathrm{d}t$.",
            ["q", "Montrer que $\\left(1-\\tfrac{t^{2}}{n}\\right)^{n} \\leqslant \\mathrm{e}^{-t^{2}}$ sur $[0\\,;\\,\\sqrt{n}]$.",
              "Montrer que $u_{n}\\to I$ par convergence dominée.",
              "Avec le changement $t = \\sqrt{n}\\sin\\theta$, exprimer $u_{n}$ à l'aide des intégrales de Wallis.",
              "En déduire $I = \\dfrac{\\sqrt{\\pi}}{2}$, sachant que $W_{n}\\sim\\sqrt{\\dfrac{\\pi}{2n}}$."]],
          sol: [["q", "$\\ln(1-x)\\leqslant -x$ pour $x<1$, appliqué à $x = \\tfrac{t^{2}}{n}$ puis multiplié par $n$.",
            "La suite de fonctions prolongée par $0$ converge simplement vers $\\mathrm{e}^{-t^{2}}$, dominée par $\\mathrm{e}^{-t^{2}}$ intégrable.",
            "$u_{n} = \\sqrt{n}\\displaystyle\\int_{0}^{\\pi/2}\\cos^{2n+1}\\theta\\,\\mathrm{d}\\theta = \\sqrt{n}\\,W_{2n+1}$.",
            "$\\sqrt{n}\\,W_{2n+1} \\sim \\sqrt{n}\\sqrt{\\dfrac{\\pi}{2(2n+1)}} \\to \\dfrac{\\sqrt{\\pi}}{2}$."]],
        },
      ],
    },
    {
      t: "Fiche 5 — Réduction : diagonalisation", st: "Éléments propres, polynôme caractéristique, diagonalisabilité", diff: "★★★",
      desc: "Calculer un spectre, décider si une matrice est diagonalisable, la réduire.",
      ex: [
        {
          t: "Diagonaliser",
          c: ["Soit $A = \\begin{pmatrix}1&2\\\\3&2\\end{pmatrix}$.",
            ["q", "Calculer le polynôme caractéristique de $A$.",
              "Déterminer les valeurs propres et des vecteurs propres associés.",
              "Écrire $A = PDP^{-1}$.",
              "En déduire $A^{\\,n}$ pour $n\\in\\mathbb{N}$."]],
          sol: [["q", "$\\chi_{A}(\\lambda) = \\lambda^{2}-3\\lambda-4 = (\\lambda-4)(\\lambda+1)$.",
            "$\\lambda = 4$ : vecteur $(2,3)$ ; $\\lambda = -1$ : vecteur $(1,-1)$.",
            "$P = \\begin{pmatrix}2&1\\\\3&-1\\end{pmatrix}$, $D = \\mathrm{diag}(4,-1)$.",
            "$A^{n} = P\\,\\mathrm{diag}(4^{\\,n},(-1)^{n})\\,P^{-1}$, soit $A^{n} = \\dfrac{1}{5}\\begin{pmatrix}2\\cdot4^{n}+3(-1)^{n}&2\\cdot4^{n}-2(-1)^{n}\\\\3\\cdot4^{n}-3(-1)^{n}&3\\cdot4^{n}+2(-1)^{n}\\end{pmatrix}$."]],
        },
        {
          t: "Diagonalisable ou non ?",
          c: ["Pour chacune des matrices, dire si elle est diagonalisable dans $\\mathcal{M}_{n}(\\mathbb{R})$ :",
            ["q", "$A = \\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$", "$B = \\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$",
              "$C = \\begin{pmatrix}2&0&0\\\\0&2&0\\\\0&0&5\\end{pmatrix}$", "$D$ symétrique réelle quelconque"]],
          sol: [["q", "Non : valeur propre double $1$ mais sous-espace propre de dimension $1$.",
            "Non dans $\\mathbb{R}$ ($\\chi_{B} = \\lambda^{2}+1$ n'est pas scindé), mais oui dans $\\mathbb{C}$.",
            "Oui : elle est déjà diagonale.",
            "Oui : théorème spectral, et même dans une base orthonormée."]],
        },
        {
          t: "Endomorphisme de polynômes",
          c: ["Sur $E = \\mathbb{R}_{2}[X]$, on pose $u(P) = (X^{2}-1)P'' + 2XP'$.",
            ["q", "Vérifier que $u$ est un endomorphisme de $E$.",
              "Écrire sa matrice dans la base $(1,X,X^{2})$.",
              "Déterminer les valeurs propres de $u$.",
              "$u$ est-elle diagonalisable ? Donner une base de vecteurs propres."]],
          sol: [["q", "Le degré reste $\\leqslant 2$ : $u(X^{2}) = 2(X^{2}-1) + 4X^{2} = 6X^{2}-2$.",
            "$u(1) = 0$, $u(X) = 2X$, $u(X^{2}) = 6X^{2}-2$ : $M = \\begin{pmatrix}0&0&-2\\\\0&2&0\\\\0&0&6\\end{pmatrix}$.",
            "$M$ est triangulaire : les valeurs propres sont $0$, $2$ et $6$.",
            "Trois valeurs propres distinctes en dimension $3$ : $u$ est diagonalisable, de base propre $\\left(1,\\ X,\\ 3X^{2}-1\\right)$."]],
        },
        {
          t: "Suites récurrentes linéaires",
          c: ["Soit $u_{0}=1$, $v_{0}=0$ et $\\begin{cases}u_{n+1} = 3u_{n} + v_{n}\\\\ v_{n+1} = u_{n} + 3v_{n}\\end{cases}$.",
            ["q", "Écrire le système sous forme matricielle $X_{n+1} = AX_{n}$.",
              "Diagonaliser $A$.",
              "En déduire $u_{n}$ et $v_{n}$.",
              "Déterminer $\\displaystyle\\lim_{n\\to+\\infty}\\frac{u_{n}}{v_{n}}$."]],
          sol: [["q", "$A = \\begin{pmatrix}3&1\\\\1&3\\end{pmatrix}$ et $X_{n} = A^{n}X_{0}$.",
            "Valeurs propres $4$ (vecteur $(1,1)$) et $2$ (vecteur $(1,-1)$).",
            "$u_{n} = \\tfrac{4^{n}+2^{n}}{2}$ et $v_{n} = \\tfrac{4^{n}-2^{n}}{2}$.",
            "Le quotient tend vers $1$ (le terme dominant $4^{n}$ est commun)."]],
        },
      ],
    },
    {
      t: "Fiche 6 — Polynômes annulateurs et trigonalisation", st: "Cayley-Hamilton, polynôme minimal, nilpotence", diff: "★★★",
      desc: "Au-delà de la diagonalisation : annulateurs, sous-espaces caractéristiques.",
      ex: [
        {
          t: "Polynômes annulateurs",
          c: ["Soit $A$ telle que $A^{2} - 5A + 6I = 0$.",
            ["q", "Montrer que $A$ est inversible et exprimer $A^{-1}$.",
              "Quelles sont les valeurs propres possibles de $A$ ?",
              "Montrer que $A$ est diagonalisable.",
              "Donner un exemple de telle matrice non scalaire en dimension $2$."]],
          sol: [["q", "$A\\left(\\tfrac{5I-A}{6}\\right) = I$ donc $A^{-1} = \\dfrac{5I-A}{6}$.",
            "Les racines du polynôme annulateur : $2$ et $3$.",
            "$X^{2}-5X+6 = (X-2)(X-3)$ est scindé à racines simples et annulateur : $A$ est diagonalisable.",
            "$\\mathrm{diag}(2,3)$, ou toute matrice semblable, par exemple $\\begin{pmatrix}2&1\\\\0&3\\end{pmatrix}$."]],
        },
        {
          t: "Cayley-Hamilton",
          c: ["Soit $A = \\begin{pmatrix}1&1&0\\\\0&1&1\\\\0&0&2\\end{pmatrix}$.",
            ["q", "Calculer $\\chi_{A}$.",
              "$A$ est-elle diagonalisable ?",
              "Déterminer le polynôme minimal de $A$.",
              "Calculer $A^{-1}$ à l'aide de Cayley-Hamilton."]],
          sol: [["q", "$\\chi_{A}(\\lambda) = (1-\\lambda)^{2}(2-\\lambda)$.",
            "Non : $\\dim\\ker(A-I) = 1 < 2$.",
            "$\\mu_{A} = (X-1)^{2}(X-2)$ (le facteur $(X-1)$ seul n'annule pas $A$).",
            "$\\chi_{A}(A) = 0$ s'écrit $-A^{3}+4A^{2}-5A+2I = 0$, d'où $A^{-1} = \\tfrac{1}{2}\\left(A^{2}-4A+5I\\right)$."]],
        },
        {
          t: "Matrices nilpotentes",
          c: ["Soit $N \\in \\mathcal{M}_{n}(\\mathbb{C})$ nilpotente.",
            ["q", "Montrer que $0$ est la seule valeur propre de $N$.",
              "En déduire $\\chi_{N}$.",
              "Montrer que $I - N$ est inversible et exprimer son inverse.",
              "Montrer qu'une matrice nilpotente non nulle n'est jamais diagonalisable."]],
          sol: [["q", "Si $Nx = \\lambda x$ avec $x\\neq0$, alors $N^{k}x = \\lambda^{k}x = 0$ donc $\\lambda = 0$.",
            "$\\chi_{N} = (-1)^{n}X^{\\,n}$ (spectre réduit à $0$ dans $\\mathbb{C}$).",
            "$(I-N)^{-1} = I + N + \\dots + N^{\\,p-1}$ si $N^{p} = 0$.",
            "Si elle l'était, elle serait semblable à $\\mathrm{diag}(0,\\dots,0) = 0$, donc nulle."]],
        },
        {
          t: "Trigonalisation",
          c: ["Soit $A = \\begin{pmatrix}2&1\\\\-1&4\\end{pmatrix}$.",
            ["q", "Calculer $\\chi_{A}$ et montrer que $A$ a une unique valeur propre.",
              "$A$ est-elle diagonalisable ?",
              "Trigonaliser $A$ : trouver $P$ telle que $P^{-1}AP = \\begin{pmatrix}3&1\\\\0&3\\end{pmatrix}$.",
              "En déduire $A^{\\,n}$."]],
          sol: [["q", "$\\chi_{A} = \\lambda^{2}-6\\lambda+9 = (\\lambda-3)^{2}$ : valeur propre double $3$.",
            "Non : $A - 3I = \\begin{pmatrix}-1&1\\\\-1&1\\end{pmatrix}$ est de rang $1$, le sous-espace propre est de dimension $1$.",
            "Vecteur propre $e_{1} = (1,1)$ ; on choisit $e_{2} = (1,0)$, qui vérifie $(A-3I)e_{2} = -e_{1}$ : avec $P = \\begin{pmatrix}1&-1\\\\1&0\\end{pmatrix}$ on obtient la forme voulue.",
            "$\\begin{pmatrix}3&1\\\\0&3\\end{pmatrix}^{n} = \\begin{pmatrix}3^{n}&n3^{\\,n-1}\\\\0&3^{n}\\end{pmatrix}$, puis $A^{n} = P(\\cdot)P^{-1} = 3^{\\,n-1}\\begin{pmatrix}3-n&n\\\\-n&3+n\\end{pmatrix}$."]],
        },
      ],
    },
    {
      t: "Fiche 7 — Espaces euclidiens", st: "Produit scalaire, orthogonalité, projections, matrices symétriques", diff: "★★★",
      desc: "Gram-Schmidt, projections orthogonales et théorème spectral.",
      ex: [
        {
          t: "Produit scalaire et norme",
          c: ["Sur $E = \\mathbb{R}[X]$, on pose $\\langle P,Q\\rangle = \\displaystyle\\int_{0}^{1}P(t)Q(t)\\,\\mathrm{d}t$.",
            ["q", "Vérifier qu'il s'agit d'un produit scalaire.",
              "Calculer $\\|1\\|$, $\\|X\\|$ et $\\langle 1,X\\rangle$.",
              "Orthonormaliser la famille $(1, X)$ par le procédé de Gram-Schmidt.",
              "En déduire la projection orthogonale de $X^{2}$ sur $\\mathbb{R}_{1}[X]$."]],
          sol: [["q", "Bilinéaire, symétrique, et $\\langle P,P\\rangle = \\displaystyle\\int_{0}^{1}P^{2} = 0$ avec $P$ continue implique $P = 0$.",
            "$\\|1\\| = 1$, $\\|X\\| = \\tfrac{1}{\\sqrt3}$, $\\langle1,X\\rangle = \\tfrac12$.",
            "$e_{1} = 1$ ; $X - \\tfrac12$ de norme $\\tfrac{1}{2\\sqrt3}$ : $e_{2} = 2\\sqrt{3}\\left(X-\\tfrac12\\right)$.",
            "$p(X^{2}) = \\langle X^{2},e_{1}\\rangle e_{1} + \\langle X^{2},e_{2}\\rangle e_{2} = \\tfrac13 + \\left(X - \\tfrac12\\right) = X - \\tfrac16$."]],
        },
        {
          t: "Projection orthogonale",
          c: ["Dans $\\mathbb{R}^{3}$ euclidien canonique, soit $F = \\mathrm{Vect}\\big((1,1,0),(0,1,1)\\big)$.",
            ["q", "Déterminer une base de $F^{\\perp}$.",
              "Déterminer la matrice de la projection orthogonale sur $F$.",
              "Calculer la distance du point $(1,0,0)$ à $F$."]],
          sol: [["q", "$(x,y,z)$ orthogonal aux deux générateurs : $x+y = 0$, $y+z=0$ : $F^{\\perp} = \\mathrm{Vect}\\big((1,-1,1)\\big)$.",
            "$p = \\mathrm{id} - \\dfrac{\\langle\\cdot,n\\rangle}{\\|n\\|^{2}}n$ avec $n = (1,-1,1)$ : $P = I_{3} - \\tfrac13\\begin{pmatrix}1&-1&1\\\\-1&1&-1\\\\1&-1&1\\end{pmatrix}$.",
            "$d = \\dfrac{|\\langle(1,0,0),n\\rangle|}{\\|n\\|} = \\dfrac{1}{\\sqrt3}$."]],
        },
        {
          t: "Matrices symétriques",
          c: ["Soit $S = \\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$.",
            ["q", "Justifier a priori que $S$ est diagonalisable en base orthonormée.",
              "Déterminer ses valeurs propres et une base orthonormée de vecteurs propres.",
              "Écrire $S = Q\\,D\\,Q^{\\top}$ avec $Q$ orthogonale.",
              "La forme quadratique $q(x,y) = 2x^{2}+2xy+2y^{2}$ est-elle définie positive ?"]],
          sol: [["q", "Théorème spectral : toute matrice symétrique réelle est orthodiagonalisable.",
            "$\\lambda = 3$ pour $\\tfrac{1}{\\sqrt2}(1,1)$ et $\\lambda = 1$ pour $\\tfrac{1}{\\sqrt2}(1,-1)$.",
            "$Q = \\tfrac{1}{\\sqrt2}\\begin{pmatrix}1&1\\\\1&-1\\end{pmatrix}$ et $D = \\mathrm{diag}(3,1)$.",
            "Les valeurs propres sont strictement positives : oui, $q$ est définie positive."]],
        },
        {
          t: "Inégalités",
          c: [["q", "Énoncer et démontrer l'inégalité de Cauchy-Schwarz dans un espace préhilbertien.",
            "Cas d'égalité ?",
            "Application : pour $f$ continue sur $[0\\,;\\,1]$, montrer $\\left(\\displaystyle\\int_{0}^{1}f\\right)^{2}\\leqslant\\displaystyle\\int_{0}^{1}f^{2}$.",
            "Montrer que pour $a,b,c>0$, $(a+b+c)\\left(\\tfrac1a+\\tfrac1b+\\tfrac1c\\right)\\geqslant 9$."]],
          sol: [["q", "$|\\langle x,y\\rangle| \\leqslant \\|x\\|\\|y\\|$ : le trinôme $t\\mapsto\\|x+ty\\|^{2}\\geqslant0$ a un discriminant négatif.",
            "Égalité si et seulement si la famille $(x,y)$ est liée.",
            "Cauchy-Schwarz avec $g = 1$ pour le produit scalaire intégral.",
            "Cauchy-Schwarz appliqué aux vecteurs $(\\sqrt a,\\sqrt b,\\sqrt c)$ et $\\left(\\tfrac{1}{\\sqrt a},\\tfrac{1}{\\sqrt b},\\tfrac{1}{\\sqrt c}\\right)$ : $9 = (1+1+1)^{2}\\leqslant (a+b+c)\\left(\\tfrac1a+\\tfrac1b+\\tfrac1c\\right)$."]],
        },
      ],
    },
    {
      t: "Fiche 8 — Équations différentielles linéaires", st: "Systèmes différentiels, exponentielle de matrice, raccords", diff: "★★★",
      desc: "Résolution par réduction et étude qualitative des solutions.",
      ex: [
        {
          t: "Systèmes différentiels",
          c: ["Résoudre le système $X' = AX$ avec $A = \\begin{pmatrix}1&2\\\\2&1\\end{pmatrix}$.",
            ["q", "Diagonaliser $A$.",
              "En déduire la solution générale du système.",
              "Déterminer la solution vérifiant $X(0) = \\begin{pmatrix}1\\\\0\\end{pmatrix}$.",
              "Décrire le comportement des solutions en $+\\infty$."]],
          sol: [["q", "Valeurs propres $3$ (vecteur $(1,1)$) et $-1$ (vecteur $(1,-1)$).",
            "$X(t) = \\alpha\\mathrm{e}^{3t}\\begin{pmatrix}1\\\\1\\end{pmatrix} + \\beta\\mathrm{e}^{-t}\\begin{pmatrix}1\\\\-1\\end{pmatrix}$.",
            "$\\alpha = \\beta = \\tfrac12$ : $X(t) = \\tfrac12\\begin{pmatrix}\\mathrm{e}^{3t}+\\mathrm{e}^{-t}\\\\ \\mathrm{e}^{3t}-\\mathrm{e}^{-t}\\end{pmatrix}$.",
            "Sauf si $\\alpha = 0$, les solutions explosent en suivant la direction propre $(1,1)$."]],
        },
        {
          t: "Ordre 2 avec second membre",
          c: ["Résoudre sur $\\mathbb{R}$ :",
            ["q", "$y'' - y = \\mathrm{e}^{x}$", "$y'' + 4y = \\cos(2x)$", "$y'' + y' - 2y = x$"]],
          sol: [["q", "Racines $\\pm1$, résonance simple : $y = A\\mathrm{e}^{x}+B\\mathrm{e}^{-x} + \\tfrac{x}{2}\\mathrm{e}^{x}$.",
            "Résonance : $y = A\\cos 2x + B\\sin 2x + \\tfrac{x}{4}\\sin 2x$.",
            "Solution particulière affine $y = -\\tfrac{x}{2} - \\tfrac{1}{4}$ : $y = A\\mathrm{e}^{x}+B\\mathrm{e}^{-2x} - \\tfrac{x}{2}-\\tfrac14$."]],
        },
        {
          t: "Équation à coefficients non constants",
          c: ["On considère $x^{2}y'' - 2y = 0$ sur $]0\\,;\\,+\\infty[$.",
            ["q", "Chercher des solutions de la forme $y = x^{\\alpha}$.",
              "En déduire la solution générale sur $]0\\,;\\,+\\infty[$.",
              "Existe-t-il des solutions non nulles sur $\\mathbb{R}$ tout entier, prolongeables par continuité en $0$ ?"]],
          sol: [["q", "$\\alpha(\\alpha-1) - 2 = 0$ donne $\\alpha = 2$ ou $\\alpha = -1$.",
            "$y = Ax^{2} + \\dfrac{B}{x}$ (l'espace des solutions est de dimension $2$).",
            "Seules les solutions avec $B = 0$, soit $y = Ax^{2}$, se prolongent en une solution sur $\\mathbb{R}$."]],
        },
        {
          t: "Modélisation : deux populations",
          c: ["Deux espèces vérifient $\\begin{cases}x' = -x + y\\\\ y' = x - y\\end{cases}$.",
            ["q", "Montrer que $x + y$ est constante.",
              "Résoudre le système avec $x(0) = 10$, $y(0) = 0$.",
              "Déterminer la limite des populations.",
              "Interpréter le résultat."]],
          sol: [["q", "$(x+y)' = 0$ : la population totale est conservée.",
            "$x - y$ vérifie $(x-y)' = -2(x-y)$ : $x - y = 10\\mathrm{e}^{-2t}$, et $x+y = 10$, d'où $x = 5(1+\\mathrm{e}^{-2t})$ et $y = 5(1-\\mathrm{e}^{-2t})$.",
            "Les deux populations tendent vers $5$.",
            "Les échanges entre les deux milieux équilibrent les effectifs : c'est un modèle de diffusion."]],
        },
      ],
    },
    {
      t: "Fiche 9 — Probabilités discrètes", st: "Lois usuelles, espérance, fonctions génératrices, convergence", diff: "★★★",
      desc: "Variables aléatoires à valeurs dans $\\mathbb{N}$, conditionnement et limites.",
      ex: [
        {
          t: "Lois usuelles",
          c: [["q", "Soit $X \\sim \\mathcal{G}(p)$ (loi géométrique). Rappeler $P(X=k)$, calculer $E(X)$ et $V(X)$.",
            "Soit $Y \\sim \\mathcal{P}(\\lambda)$. Calculer $E(Y)$ et $V(Y)$.",
            "Montrer que la somme de deux variables de Poisson indépendantes suit une loi de Poisson.",
            "Montrer la propriété d'absence de mémoire de la loi géométrique."]],
          sol: [["q", "$P(X=k) = (1-p)^{k-1}p$ pour $k\\geqslant1$, $E(X) = \\tfrac1p$, $V(X) = \\tfrac{1-p}{p^{2}}$.",
            "$E(Y) = V(Y) = \\lambda$.",
            "Produit de convolution : $P(Y_{1}+Y_{2}=n) = \\mathrm{e}^{-(\\lambda+\\mu)}\\displaystyle\\sum_{k}\\frac{\\lambda^{k}\\mu^{\\,n-k}}{k!(n-k)!} = \\mathrm{e}^{-(\\lambda+\\mu)}\\frac{(\\lambda+\\mu)^{n}}{n!}$.",
            "$P(X>n+k \\mid X>n) = \\dfrac{(1-p)^{n+k}}{(1-p)^{n}} = (1-p)^{k} = P(X>k)$."]],
        },
        {
          t: "Fonctions génératrices",
          c: ["Soit $X$ à valeurs dans $\\mathbb{N}$, de fonction génératrice $G_{X}(t) = E(t^{X})$.",
            ["q", "Calculer $G_{X}$ pour $X\\sim\\mathcal{B}(n,p)$ et pour $X\\sim\\mathcal{P}(\\lambda)$.",
              "Exprimer $E(X)$ et $V(X)$ à l'aide de $G_{X}'$ et $G_{X}''$.",
              "Montrer que si $X$ et $Y$ sont indépendantes, $G_{X+Y} = G_{X}G_{Y}$.",
              "Application : retrouver la loi de la somme de deux binomiales de même paramètre $p$."]],
          sol: [["q", "$(1-p+pt)^{n}$ et $\\mathrm{e}^{\\lambda(t-1)}$.",
            "$E(X) = G_{X}'(1)$ et $V(X) = G_{X}''(1) + G_{X}'(1) - G_{X}'(1)^{2}$.",
            "$E(t^{X+Y}) = E(t^{X})E(t^{Y})$ par indépendance.",
            "$(1-p+pt)^{n}(1-p+pt)^{m} = (1-p+pt)^{n+m}$ : la somme suit $\\mathcal{B}(n+m,p)$."]],
        },
        {
          t: "Conditionnement et récurrence",
          c: ["Une puce part de $0$ ; à chaque étape elle avance de $1$ avec probabilité $p$ et reste sur place sinon. On note $T$ le temps d'atteinte de la position $2$.",
            ["q", "Quelle est la loi du temps d'atteinte de la position $1$ ?",
              "En déduire la loi de $T$ comme somme de deux variables indépendantes.",
              "Calculer $E(T)$ et $V(T)$.",
              "Calculer $P(T = 3)$."]],
          sol: [["q", "Loi géométrique de paramètre $p$.",
            "$T = T_{1}+T_{2}$ avec $T_{i}$ i.i.d. géométriques : $T$ suit une loi de Pascal (binomiale négative), $P(T=k) = (k-1)p^{2}(1-p)^{k-2}$ pour $k\\geqslant2$.",
            "$E(T) = \\tfrac2p$ et $V(T) = \\dfrac{2(1-p)}{p^{2}}$.",
            "$P(T=3) = 2p^{2}(1-p)$."]],
        },
        {
          t: "Convergences",
          c: [["q", "Énoncer l'inégalité de Bienaymé-Tchebychev et la loi faible des grands nombres.",
            "Soit $X_{n}\\sim\\mathcal{B}(n,\\lambda/n)$. Montrer que $X_{n}$ converge en loi vers une loi de Poisson.",
            "Application : sur $2\\,000$ pages, une coquille apparaît avec probabilité $10^{-3}$ par page. Estimer la probabilité d'avoir au plus une coquille."]],
          sol: [["q", "$P(|X-E(X)|\\geqslant\\varepsilon)\\leqslant\\dfrac{V(X)}{\\varepsilon^{2}}$ ; la moyenne empirique de variables i.i.d. intégrables converge en probabilité vers l'espérance.",
            "$P(X_{n}=k) = \\binom{n}{k}\\left(\\tfrac{\\lambda}{n}\\right)^{k}\\left(1-\\tfrac{\\lambda}{n}\\right)^{n-k} \\to \\mathrm{e}^{-\\lambda}\\dfrac{\\lambda^{k}}{k!}$.",
            "$\\lambda = 2$ : $P(X\\leqslant1) \\approx \\mathrm{e}^{-2}(1+2) \\approx 0{,}406$."]],
        },
      ],
    },
    {
      t: "Fiche 10 — Calcul différentiel", st: "Dérivées partielles, gradient, extremums, équations aux dérivées partielles", diff: "★★",
      desc: "Fonctions de plusieurs variables : différentielle, points critiques, optimisation.",
      ex: [
        {
          t: "Dérivées partielles",
          c: ["Soit $f(x,y) = x^{3} + y^{3} - 3xy$.",
            ["q", "Calculer $\\nabla f$.",
              "Déterminer les points critiques.",
              "Calculer la matrice hessienne et déterminer la nature de chaque point critique.",
              "La fonction admet-elle un minimum global ?"]],
          sol: [["q", "$\\nabla f = (3x^{2}-3y,\\ 3y^{2}-3x)$.",
            "$x^{2}=y$ et $y^{2}=x$ : $x^{4}=x$, soit $x = 0$ ou $x=1$ : points $(0,0)$ et $(1,1)$.",
            "$H = \\begin{pmatrix}6x&-3\\\\-3&6y\\end{pmatrix}$ : en $(0,0)$, $\\det = -9 < 0$ (point selle) ; en $(1,1)$, $\\det = 27 > 0$ et $6 > 0$ (minimum local, $f(1,1) = -1$).",
            "Non : $f(x,0) = x^{3} \\to -\\infty$."]],
        },
        {
          t: "Optimisation sous contrainte",
          c: ["Déterminer les extremums de $f(x,y) = xy$ sur le cercle $x^{2}+y^{2} = 1$.",
            ["q", "Paramétrer le cercle et se ramener à une fonction d'une variable.",
              "Déterminer les extremums et les points où ils sont atteints.",
              "Retrouver le résultat avec un multiplicateur de Lagrange."]],
          sol: [["q", "$x = \\cos\\theta$, $y = \\sin\\theta$ : $g(\\theta) = \\cos\\theta\\sin\\theta = \\tfrac{\\sin 2\\theta}{2}$.",
            "Maximum $\\tfrac12$ en $\\theta = \\tfrac{\\pi}{4}$ et $\\tfrac{5\\pi}{4}$ ; minimum $-\\tfrac12$ en $\\theta = \\tfrac{3\\pi}{4}$ et $\\tfrac{7\\pi}{4}$.",
            "$\\nabla f = \\lambda\\nabla g$ donne $y = 2\\lambda x$ et $x = 2\\lambda y$, d'où $x = \\pm y$ : mêmes points."]],
        },
        {
          t: "Changement de variables",
          c: ["Soit $f$ de classe $\\mathcal{C}^{1}$ sur $\\mathbb{R}^{2}$ et $g(u,v) = f(u+v,\\ u-v)$.",
            ["q", "Exprimer $\\partial_{u}g$ et $\\partial_{v}g$ en fonction des dérivées partielles de $f$.",
              "Résoudre l'équation $\\partial_{x}f + \\partial_{y}f = 0$.",
              "Résoudre $x\\,\\partial_{x}f + y\\,\\partial_{y}f = 0$ en coordonnées polaires."]],
          sol: [["q", "$\\partial_{u}g = \\partial_{x}f + \\partial_{y}f$ et $\\partial_{v}g = \\partial_{x}f - \\partial_{y}f$.",
            "L'équation devient $\\partial_{u}g = 0$ : $g$ ne dépend que de $v$, donc $f(x,y) = \\varphi(x-y)$.",
            "En polaires, l'équation s'écrit $r\\,\\partial_{r}f = 0$ : $f$ ne dépend que de $\\theta$, soit $f(x,y) = \\psi\\!\\left(\\arctan\\tfrac{y}{x}\\right)$ (sur un demi-plan)."]],
        },
        {
          t: "Application géométrique",
          c: ["Soit $S$ la surface d'équation $z = x^{2}+y^{2}$.",
            ["q", "Déterminer le plan tangent à $S$ au point $(1,1,2)$.",
              "Déterminer le point de $S$ le plus proche de $A(0,0,1)$.",
              "Interpréter géométriquement."]],
          sol: [["q", "Avec $F(x,y,z) = x^{2}+y^{2}-z$, $\\nabla F(1,1,2) = (2,2,-1)$ : $2x + 2y - z - 2 = 0$.",
            "On minimise $d^{2} = r^{2} + (r^{2}-1)^{2}$ avec $r^{2} = x^{2}+y^{2}$ : la dérivée en $s = r^{2}$ vaut $1 + 2(s-1) = 0$, soit $s = \\tfrac12$ : tous les points du cercle $x^{2}+y^{2} = \\tfrac12$, $z = \\tfrac12$.",
            "Le minimum est atteint sur tout un cercle, par symétrie de révolution du paraboloïde autour de l'axe $(Oz)$."]],
        },
      ],
    },
  ]);

  L.addSujets("spe", "ds", [
    {
      t: "Contrôle n° 1 — Séries numériques", st: "Natures, comparaisons, calculs de sommes", h: 1, calc: "interdite",
      desc: "Trois exercices de rédaction rapide sur les séries.",
      ex: [
        {
          t: "Natures", pts: 8,
          c: ["Déterminer la nature des séries de terme général :",
            ["q", "$\\dfrac{\\ln n}{n^{2}}$", "$\\dfrac{1}{n^{1+1/n}}$", "$\\left(\\dfrac{n}{n+1}\\right)^{n^{2}}$",
              "$\\dfrac{(-1)^{n}}{n+(-1)^{n}\\sqrt{n}}$"]],
          sol: [["q", "$\\dfrac{\\ln n}{n^{2}} = o\\!\\left(\\tfrac{1}{n^{3/2}}\\right)$ : convergente.",
            "$n^{1/n} = \\mathrm{e}^{\\ln n/n}\\to1$ donc le terme est équivalent à $\\tfrac1n$ : divergente.",
            "$\\exp\\!\\left(n^{2}\\ln\\!\\left(1-\\tfrac{1}{n+1}\\right)\\right)\\sim\\mathrm{e}^{-n}$ : convergente.",
            "Développement : $\\dfrac{(-1)^{n}}{n} - \\dfrac{1}{n^{3/2}} + o\\!\\left(n^{-3/2}\\right)$ : convergente."]],
        },
        {
          t: "Comparaison série-intégrale", pts: 6,
          c: ["Soit $\\alpha > 0$ et $S_{n} = \\displaystyle\\sum_{k=1}^{n}k^{\\alpha}$.",
            ["q", "Encadrer $S_{n}$ à l'aide d'intégrales.",
              "En déduire un équivalent de $S_{n}$.",
              "Application : donner un équivalent de $\\displaystyle\\sum_{k=1}^{n}\\sqrt{k}$."]],
          sol: [["q", "$\\displaystyle\\int_{0}^{n}t^{\\alpha}\\mathrm{d}t \\leqslant S_{n} \\leqslant \\displaystyle\\int_{1}^{n+1}t^{\\alpha}\\mathrm{d}t$ par croissance de $t\\mapsto t^{\\alpha}$.",
            "Les deux bornes sont équivalentes à $\\dfrac{n^{\\alpha+1}}{\\alpha+1}$ : $S_{n}\\sim\\dfrac{n^{\\alpha+1}}{\\alpha+1}$.",
            "$\\displaystyle\\sum_{k=1}^{n}\\sqrt{k}\\sim\\dfrac{2}{3}n^{3/2}$."]],
        },
        {
          t: "Sommes", pts: 6,
          c: ["Calculer :",
            ["q", "$\\displaystyle\\sum_{n=2}^{+\\infty}\\frac{1}{n^{2}-1}$", "$\\displaystyle\\sum_{n=0}^{+\\infty}\\frac{n^{2}}{2^{\\,n}}$",
              "$\\displaystyle\\sum_{n=1}^{+\\infty}\\frac{(-1)^{n+1}}{n}$"]],
          sol: [["q", "$\\dfrac{1}{n^{2}-1} = \\tfrac12\\left(\\tfrac{1}{n-1}-\\tfrac{1}{n+1}\\right)$ : télescopage, la somme vaut $\\tfrac34$.",
            "En dérivant deux fois la série géométrique : $\\displaystyle\\sum n^{2}x^{n} = \\dfrac{x(1+x)}{(1-x)^{3}}$, soit $6$ en $x=\\tfrac12$.",
            "$\\ln 2$ (série harmonique alternée)."]],
        },
      ],
    },
    {
      t: "Contrôle n° 2 — Réduction", st: "Éléments propres, diagonalisation, puissances", h: 1, calc: "interdite",
      desc: "Trois exercices sur la réduction des endomorphismes.",
      ex: [
        {
          t: "Diagonalisation", pts: 8,
          c: ["Soit $A = \\begin{pmatrix}3&-1&1\\\\0&2&0\\\\1&-1&3\\end{pmatrix}$.",
            ["q", "Calculer $\\chi_{A}$.",
              "Déterminer les sous-espaces propres.",
              "$A$ est-elle diagonalisable ? Si oui, donner $P$ et $D$.",
              "Calculer $A^{\\,n}$."]],
          sol: [["q", "$\\chi_{A}(\\lambda) = (2-\\lambda)^{2}(4-\\lambda)$.",
            "$E_{2} = \\ker(A-2I) = \\mathrm{Vect}\\big((1,1,0),(1,0,-1)\\big)$ (rang $1$) ; $E_{4} = \\mathrm{Vect}\\big((1,0,1)\\big)$.",
            "Oui : $\\dim E_{2} + \\dim E_{4} = 3$, avec $P$ formée de ces trois vecteurs et $D = \\mathrm{diag}(2,2,4)$.",
            "$A^{n} = PD^{n}P^{-1}$ avec $D^{n} = \\mathrm{diag}(2^{n},2^{n},4^{n})$ ; on peut aussi écrire $A^{n} = 2^{n}I + (4^{n}-2^{n})\\,\\pi$, où $\\pi$ est le projecteur sur $E_{4}$ parallèlement à $E_{2}$."]],
        },
        {
          t: "Polynôme annulateur", pts: 6,
          c: ["Soit $A\\in\\mathcal{M}_{3}(\\mathbb{R})$ vérifiant $A^{3} = A$.",
            ["q", "Quelles sont les valeurs propres possibles de $A$ ?",
              "Montrer que $A$ est diagonalisable.",
              "Donner un exemple de telle matrice de rang $2$.",
              "Que vaut $A^{2024}$ en fonction de $A$ et $A^{2}$ ?"]],
          sol: [["q", "Racines de $X^{3}-X$ : $-1$, $0$, $1$.",
            "$X^{3}-X$ est scindé à racines simples et annule $A$.",
            "$\\mathrm{diag}(1,-1,0)$.",
            "$A^{3} = A$ donne $A^{2k+1} = A$ ; donc $A^{2024} = A^{2023}A = A\\cdot A = A^{2}$."]],
        },
        {
          t: "Trace et rang", pts: 6,
          c: ["Soit $A$ une matrice de rang $1$ de $\\mathcal{M}_{n}(\\mathbb{R})$.",
            ["q", "Montrer qu'il existe $U,V$ colonnes telles que $A = UV^{\\top}$.",
              "Montrer que $A^{2} = \\mathrm{tr}(A)\\,A$.",
              "À quelle condition $A$ est-elle diagonalisable ?"]],
          sol: [["q", "L'image est une droite engendrée par $U$, et chaque colonne de $A$ est un multiple de $U$ : $A = UV^{\\top}$.",
            "$A^{2} = U(V^{\\top}U)V^{\\top} = (V^{\\top}U)A$ et $\\mathrm{tr}(A) = V^{\\top}U$.",
            "Si $\\mathrm{tr}(A)\\neq0$, $X^{2}-\\mathrm{tr}(A)X$ est scindé à racines simples : diagonalisable. Si $\\mathrm{tr}(A)=0$, $A$ est nilpotente non nulle : non diagonalisable."]],
        },
      ],
    },
    {
      t: "Contrôle n° 3 — Intégrales généralisées", st: "Convergence, calcul, convergence dominée", h: 1, calc: "interdite",
      desc: "Nature d'intégrales impropres et passage à la limite.",
      ex: [
        {
          t: "Convergences", pts: 7,
          c: ["Étudier la convergence et calculer lorsque c'est possible :",
            ["q", "$\\displaystyle\\int_{0}^{+\\infty}t\\,\\mathrm{e}^{-t}\\mathrm{d}t$", "$\\displaystyle\\int_{0}^{1}\\ln t\\,\\mathrm{d}t$",
              "$\\displaystyle\\int_{1}^{+\\infty}\\frac{\\mathrm{d}t}{t\\sqrt{t+1}}$", "$\\displaystyle\\int_{0}^{+\\infty}\\frac{\\mathrm{d}t}{\\sqrt{t}(1+t)}$"]],
          sol: [["q", "Convergente, vaut $1$ (IPP).",
            "Convergente (faussement impropre en $0$), vaut $-1$.",
            "$\\sim t^{-3/2}$ en $+\\infty$ : convergente.",
            "Convergente aux deux bornes ; changement $t = u^{2}$ : $2\\displaystyle\\int_{0}^{+\\infty}\\frac{\\mathrm{d}u}{1+u^{2}} = \\pi$."]],
        },
        {
          t: "Intégrale à paramètre", pts: 7,
          c: ["Soit $F(x) = \\displaystyle\\int_{0}^{+\\infty}\\mathrm{e}^{-t}\\cos(xt)\\,\\mathrm{d}t$.",
            ["q", "Justifier l'existence de $F(x)$ pour tout $x$.",
              "Montrer que $F$ est de classe $\\mathcal{C}^{1}$.",
              "Calculer $F(x)$ (deux IPP ou passage aux complexes).",
              "En déduire $\\displaystyle\\int_{0}^{+\\infty}\\mathrm{e}^{-t}\\sin(xt)\\,\\mathrm{d}t$."]],
          sol: [["q", "$|\\mathrm{e}^{-t}\\cos(xt)|\\leqslant\\mathrm{e}^{-t}$, intégrable.",
            "La dérivée partielle est dominée par $t\\mathrm{e}^{-t}$, intégrable et indépendante de $x$.",
            "En considérant $\\displaystyle\\int_{0}^{+\\infty}\\mathrm{e}^{-(1-\\mathrm{i}x)t}\\mathrm{d}t = \\dfrac{1}{1-\\mathrm{i}x}$, on prend la partie réelle : $F(x) = \\dfrac{1}{1+x^{2}}$.",
            "C'est la partie imaginaire : $\\dfrac{x}{1+x^{2}}$."]],
        },
        {
          t: "Convergence dominée", pts: 6,
          c: [["q", "Calculer $\\displaystyle\\lim_{n\\to+\\infty}\\int_{0}^{+\\infty}\\frac{\\mathrm{e}^{-t}}{1+\\frac{t}{n}}\\,\\mathrm{d}t$.",
            "Calculer $\\displaystyle\\lim_{n\\to+\\infty}\\int_{0}^{1}\\frac{t^{\\,n}}{1+t}\\,\\mathrm{d}t$.",
            "Justifier soigneusement les hypothèses de domination."]],
          sol: [["q", "La limite simple est $\\mathrm{e}^{-t}$, dominée par $\\mathrm{e}^{-t}$ : la limite vaut $1$.",
            "Limite simple nulle sur $[0\\,;\\,1[$, dominée par $1$ : la limite vaut $0$.",
            "Dans les deux cas, la domination est indépendante de $n$ et la fonction dominante est intégrable sur l'intervalle."]],
        },
      ],
    },
    {
      t: "Contrôle n° 4 — Espaces euclidiens", st: "Orthogonalité, projections, matrices symétriques", h: 1, calc: "interdite",
      desc: "Gram-Schmidt, distance à un sous-espace et théorème spectral.",
      ex: [
        {
          t: "Projection et distance", pts: 8,
          c: ["Dans $\\mathbb{R}^{4}$ euclidien canonique, $F = \\mathrm{Vect}\\big(u_{1}=(1,1,0,0),\\ u_{2}=(0,1,1,0)\\big)$.",
            ["q", "Orthonormaliser $(u_{1},u_{2})$.",
              "Déterminer la projection orthogonale de $x = (1,0,0,1)$ sur $F$.",
              "En déduire $d(x,F)$.",
              "Déterminer une base de $F^{\\perp}$."]],
          sol: [["q", "$e_{1} = \\tfrac{1}{\\sqrt2}(1,1,0,0)$ ; $u_{2}-\\langle u_{2},e_{1}\\rangle e_{1} = \\tfrac12(-1,1,2,0)$, normalisé : $e_{2} = \\tfrac{1}{\\sqrt6}(-1,1,2,0)$.",
            "$\\langle x,e_{1}\\rangle = \\tfrac{1}{\\sqrt2}$, $\\langle x,e_{2}\\rangle = -\\tfrac{1}{\\sqrt6}$ : $p(x) = \\tfrac12(1,1,0,0) - \\tfrac16(-1,1,2,0) = \\left(\\tfrac23,\\tfrac13,-\\tfrac13,0\\right)$.",
            "$x - p(x) = \\left(\\tfrac13,-\\tfrac13,\\tfrac13,1\\right)$, de norme $\\sqrt{\\tfrac13+1} = \\tfrac{2}{\\sqrt3}$.",
            "$F^{\\perp} = \\{(a,b,c,d) : a+b = 0,\\ b+c = 0\\} = \\mathrm{Vect}\\big((1,-1,1,0),(0,0,0,1)\\big)$."]],
        },
        {
          t: "Matrice symétrique", pts: 7,
          c: ["Soit $S = \\begin{pmatrix}1&2&0\\\\2&1&0\\\\0&0&3\\end{pmatrix}$.",
            ["q", "Justifier que $S$ est orthodiagonalisable.",
              "Déterminer ses valeurs propres.",
              "Donner une base orthonormée de vecteurs propres.",
              "La forme quadratique associée est-elle positive ?"]],
          sol: [["q", "$S$ est symétrique réelle : théorème spectral.",
            "Le bloc $2\\times2$ donne $3$ et $-1$ ; la dernière ligne donne $3$ : spectre $\\{-1,3,3\\}$.",
            "$\\tfrac{1}{\\sqrt2}(1,1,0)$ pour $3$, $(0,0,1)$ pour $3$, $\\tfrac{1}{\\sqrt2}(1,-1,0)$ pour $-1$.",
            "Non : la valeur propre $-1$ est strictement négative, la forme n'est pas positive."]],
        },
        {
          t: "Inégalité", pts: 5,
          c: [["q", "Soit $f$ continue sur $[0\\,;\\,1]$. Montrer $\\left(\\displaystyle\\int_{0}^{1}tf(t)\\,\\mathrm{d}t\\right)^{2}\\leqslant\\frac{1}{3}\\displaystyle\\int_{0}^{1}f(t)^{2}\\mathrm{d}t$.",
            "Préciser le cas d'égalité."]],
          sol: [["q", "Cauchy-Schwarz avec $g(t) = t$ : $\\|g\\|^{2} = \\displaystyle\\int_{0}^{1}t^{2}\\mathrm{d}t = \\tfrac13$.",
            "Égalité si et seulement si $f$ est proportionnelle à $t\\mapsto t$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 5 — Probabilités", st: "Lois discrètes, espérance, génératrices", h: 1, calc: "interdite",
      desc: "Lois usuelles, conditionnement et fonctions génératrices.",
      ex: [
        {
          t: "Lois usuelles", pts: 7,
          c: [["q", "Soit $X\\sim\\mathcal{G}(p)$. Calculer $P(X>n)$ puis $E(X)$ par la formule $E(X)=\\displaystyle\\sum_{n\\geqslant0}P(X>n)$.",
            "Soit $Y\\sim\\mathcal{P}(3)$. Calculer $P(Y\\leqslant2)$ (valeur exacte).",
            "Calculer $E\\!\\left(\\dfrac{1}{Y+1}\\right)$ pour $Y\\sim\\mathcal{P}(\\lambda)$."]],
          sol: [["q", "$P(X>n) = (1-p)^{n}$ et $\\displaystyle\\sum_{n\\geqslant0}(1-p)^{n} = \\tfrac1p$.",
            "$\\mathrm{e}^{-3}\\left(1+3+\\tfrac92\\right) = \\tfrac{17}{2}\\mathrm{e}^{-3} \\approx 0{,}423$.",
            "$\\displaystyle\\sum_{k\\geqslant0}\\frac{\\mathrm{e}^{-\\lambda}\\lambda^{k}}{(k+1)!} = \\frac{\\mathrm{e}^{-\\lambda}}{\\lambda}\\left(\\mathrm{e}^{\\lambda}-1\\right) = \\frac{1-\\mathrm{e}^{-\\lambda}}{\\lambda}$."]],
        },
        {
          t: "Conditionnement", pts: 7,
          c: ["Une urne contient $N$ boules numérotées de $1$ à $N$. On tire avec remise jusqu'à obtenir une boule déjà sortie. On note $T$ le nombre de tirages.",
            ["q", "Calculer $P(T > k)$ pour $k \\leqslant N$.",
              "En déduire la loi de $T$.",
              "Pour $N = 365$, interpréter le résultat (paradoxe des anniversaires).",
              "Écrire $E(T)$ sous forme de somme."]],
          sol: [["q", "$P(T>k) = \\dfrac{N(N-1)\\cdots(N-k+1)}{N^{k}}$ : les $k$ premiers tirages sont distincts.",
            "$P(T=k) = P(T>k-1) - P(T>k)$.",
            "Pour $N=365$, $P(T\\leqslant23)>\\tfrac12$ : dans un groupe de $23$ personnes, il y a plus d'une chance sur deux que deux partagent leur anniversaire.",
            "$E(T) = \\displaystyle\\sum_{k\\geqslant0}P(T>k) = \\sum_{k=0}^{N}\\frac{N!}{(N-k)!\\,N^{k}}$."]],
        },
        {
          t: "Fonction génératrice", pts: 6,
          c: ["Soit $X$ de fonction génératrice $G(t) = \\dfrac{t}{3-2t}$ pour $|t| < \\tfrac32$.",
            ["q", "Vérifier que $G(1) = 1$.",
              "Déterminer la loi de $X$ en développant $G$ en série entière.",
              "Calculer $E(X)$ et $V(X)$."]],
          sol: [["q", "$G(1) = \\tfrac{1}{1} = 1$.",
            "$G(t) = \\dfrac{t}{3}\\cdot\\dfrac{1}{1-\\tfrac{2t}{3}} = \\displaystyle\\sum_{k\\geqslant1}\\frac{2^{\\,k-1}}{3^{\\,k}}t^{k}$ : $X$ suit la loi géométrique de paramètre $\\tfrac13$.",
            "$E(X) = 3$ et $V(X) = \\dfrac{2/3}{1/9} = 6$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 1 — Séries entières et équations différentielles", st: "Problème : une fonction définie par une série entière", h: 3, calc: "interdite",
      desc: "Un problème en trois parties reliant série entière, équation différentielle et intégrale.",
      ex: [
        {
          t: "La fonction de Bessel $J_{0}$", pts: 20, nom: "Problème",
          c: ["On pose $J_{0}(x) = \\displaystyle\\sum_{n=0}^{+\\infty}\\frac{(-1)^{n}}{(n!)^{2}}\\left(\\frac{x}{2}\\right)^{2n}$.",
            ["h", "Partie A — La série entière"],
            ["q", "Déterminer le rayon de convergence de cette série entière.",
              "Calculer $J_{0}(0)$ et $J_{0}'(0)$.",
              "Montrer que $J_{0}$ est paire et de classe $\\mathcal{C}^{\\infty}$ sur $\\mathbb{R}$."],
            ["h", "Partie B — Équation différentielle"],
            ["q", "Montrer que $x\\,J_{0}''(x) + J_{0}'(x) + x\\,J_{0}(x) = 0$.",
              "En déduire que $y = J_{0}$ vérifie $\\left(x\\,y'\\right)' = -xy$.",
              "Montrer que si $J_{0}$ s'annulait sur un intervalle, elle serait identiquement nulle."],
            ["h", "Partie C — Une représentation intégrale"],
            ["q", "Montrer que $\\displaystyle\\int_{0}^{\\pi}\\cos^{2n}\\theta\\,\\mathrm{d}\\theta = \\pi\\frac{(2n)!}{4^{\\,n}(n!)^{2}}$.",
              "En déduire que $J_{0}(x) = \\dfrac{1}{\\pi}\\displaystyle\\int_{0}^{\\pi}\\cos(x\\sin\\theta)\\,\\mathrm{d}\\theta$.",
              "En déduire que $|J_{0}(x)|\\leqslant1$ pour tout $x$."]],
          sol: [["h", "Partie A"],
            ["q", "Avec $a_{n} = \\dfrac{(-1)^{n}}{4^{n}(n!)^{2}}$ et le critère de d'Alembert appliqué à $u_{n}=|a_{n}|x^{2n}$ : le rapport tend vers $0$, donc $R = +\\infty$.",
              "$J_{0}(0) = 1$ ; la série ne contient que des puissances paires donc $J_{0}'(0) = 0$.",
              "Somme d'une série entière de rayon infini : $\\mathcal{C}^{\\infty}$ sur $\\mathbb{R}$, et paire car seuls les exposants pairs apparaissent."],
            ["h", "Partie B"],
            ["q", "On dérive terme à terme et on réindexe : le coefficient de $x^{2n+1}$ dans $xJ_{0}''+J_{0}'$ vaut $\\dfrac{(-1)^{n+1}(2n+2)^{2}}{4^{\\,n+1}((n+1)!)^{2}}$, opposé à celui de $xJ_{0}$.",
              "$\\left(xy'\\right)' = y' + xy''$ : c'est exactement la relation précédente.",
              "$J_{0}$ est somme d'une série entière ; si elle était nulle sur un intervalle non trivial, tous ses coefficients de Taylor seraient nuls (principe des zéros isolés), or $J_{0}(0)=1$."],
            ["h", "Partie C"],
            ["q", "Intégrales de Wallis : $\\displaystyle\\int_{0}^{\\pi}\\cos^{2n} = 2W_{2n} = \\pi\\dfrac{(2n)!}{4^{n}(n!)^{2}}$.",
              "On développe $\\cos(x\\sin\\theta)$ en série entière, on intervertit (convergence normale sur $[0\\,;\\,\\pi]$) et on utilise la question précédente : les coefficients coïncident.",
              "$|\\cos(x\\sin\\theta)|\\leqslant1$ donne $|J_{0}(x)|\\leqslant\\dfrac{1}{\\pi}\\times\\pi = 1$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 2 — Réduction et suites de matrices", st: "Problème : matrices stochastiques et chaîne de Markov", h: 3, calc: "interdite",
      desc: "Diagonalisation, puissances de matrices et comportement asymptotique d'un modèle aléatoire.",
      ex: [
        {
          t: "Matrices stochastiques", pts: 20, nom: "Problème",
          c: ["Une matrice $A\\in\\mathcal{M}_{n}(\\mathbb{R})$ est dite stochastique si ses coefficients sont positifs et si la somme de chaque ligne vaut $1$.",
            ["h", "Partie A — Propriétés générales"],
            ["q", "Montrer que $1$ est valeur propre de toute matrice stochastique.",
              "Montrer que le produit de deux matrices stochastiques est stochastique.",
              "Montrer que toute valeur propre $\\lambda$ vérifie $|\\lambda|\\leqslant1$."],
            ["h", "Partie B — Un exemple"],
            ["q", "Soit $A = \\begin{pmatrix}0{,}9&0{,}1\\\\0{,}3&0{,}7\\end{pmatrix}$. Vérifier que $A$ est stochastique et calculer ses valeurs propres.",
              "Diagonaliser $A$.",
              "Calculer $A^{\\,k}$ et déterminer $\\displaystyle\\lim_{k\\to+\\infty}A^{\\,k}$.",
              "Interpréter : une population se répartit entre deux villes selon ces probabilités de migration annuelle."],
            ["h", "Partie C — Vecteur invariant"],
            ["q", "Déterminer les lignes $\\pi = (\\pi_{1},\\pi_{2})$ à coefficients positifs de somme $1$ telles que $\\pi A = \\pi$.",
              "Comparer avec la limite obtenue en partie B.",
              "Montrer que pour toute répartition initiale $X_{0}$, $X_{0}A^{k}$ converge vers $\\pi$."]],
          sol: [["h", "Partie A"],
            ["q", "Le vecteur colonne $U$ de coefficients $1$ vérifie $AU = U$.",
              "Les coefficients restent positifs, et $ABU = AU = U$ : les sommes des lignes valent $1$.",
              "Si $AX = \\lambda X$ avec $|x_{i}|$ maximal : $|\\lambda||x_{i}| \\leqslant \\displaystyle\\sum_{j}a_{ij}|x_{j}| \\leqslant |x_{i}|$."],
            ["h", "Partie B"],
            ["q", "Coefficients positifs, sommes des lignes égales à $1$ ; $\\chi_{A}(\\lambda) = \\lambda^{2}-1{,}6\\lambda+0{,}6 = (\\lambda-1)(\\lambda-0{,}6)$.",
              "Vecteurs propres : $(1,1)^{\\top}$ pour $1$ et $(1,-3)^{\\top}$ pour $0{,}6$.",
              "$A^{k} = \\dfrac{1}{4}\\begin{pmatrix}3+0{,}6^{k}&1-0{,}6^{k}\\\\3-3\\cdot0{,}6^{k}&1+3\\cdot0{,}6^{k}\\end{pmatrix} \\to \\dfrac14\\begin{pmatrix}3&1\\\\3&1\\end{pmatrix}$.",
              "Quelle que soit la répartition de départ, $75\\,\\%$ de la population finit dans la première ville."],
            ["h", "Partie C"],
            ["q", "$\\pi A = \\pi$ donne $0{,}9\\pi_{1}+0{,}3\\pi_{2} = \\pi_{1}$, soit $\\pi_{2} = \\tfrac13\\pi_{1}$ ; avec $\\pi_{1}+\\pi_{2}=1$ : $\\pi = \\left(\\tfrac34,\\tfrac14\\right)$.",
              "C'est exactement la ligne commune de la matrice limite.",
              "$X_{0}A^{k} \\to X_{0}\\left(\\text{matrice limite}\\right) = \\pi$ car la somme des coefficients de $X_{0}$ vaut $1$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 3 — Analyse : suites et séries de fonctions", st: "Convergence uniforme, interversion, intégrale à paramètre", h: 2, calc: "interdite",
      desc: "Deux problèmes d'analyse : une série de fonctions et une intégrale à paramètre.",
      ex: [
        {
          t: "Une série de fonctions", pts: 10, nom: "Problème",
          c: ["On pose $S(x) = \\displaystyle\\sum_{n=1}^{+\\infty}\\frac{x}{n(1+n x^{2})}$ pour $x \\geqslant 0$.",
            ["q", "Montrer que la série converge simplement sur $[0\\,;\\,+\\infty[$.",
              "Montrer qu'il y a convergence normale sur tout $[a\\,;\\,+\\infty[$ avec $a>0$.",
              "En déduire la continuité de $S$ sur $]0\\,;\\,+\\infty[$.",
              "Déterminer $\\displaystyle\\lim_{x\\to+\\infty}S(x)$.",
              "Étudier la continuité en $0$."]],
          sol: [["q", "Pour $x>0$ fixé, le terme général est équivalent à $\\dfrac{1}{n^{2}x}$ : convergence. En $x=0$ tous les termes sont nuls.",
            "Sur $[a\\,;\\,+\\infty[$, $\\dfrac{x}{n(1+nx^{2})} \\leqslant \\dfrac{1}{n^{2}x} \\leqslant \\dfrac{1}{n^{2}a}$ : la série des normes converge.",
            "Somme d'une série normalement convergente de fonctions continues sur tout segment de $]0\\,;\\,+\\infty[$.",
            "Chaque terme tend vers $0$ et la domination permet d'intervertir : $S(x)\\to0$.",
            "$S\\!\\left(\\tfrac{1}{\\sqrt{N}}\\right)\\geqslant\\displaystyle\\sum_{n=1}^{N}\\frac{1}{2n\\sqrt N} = \\frac{H_{N}}{2\\sqrt N}\\to0$ ; en fait $S(x)\\to0 = S(0)$ : $S$ est continue en $0$."]],
        },
        {
          t: "Une intégrale à paramètre", pts: 10, nom: "Problème",
          c: ["Pour $x>0$, on pose $\\Gamma(x) = \\displaystyle\\int_{0}^{+\\infty}t^{\\,x-1}\\mathrm{e}^{-t}\\,\\mathrm{d}t$.",
            ["q", "Montrer que $\\Gamma(x)$ est bien définie pour $x>0$.",
              "Montrer que $\\Gamma(x+1) = x\\,\\Gamma(x)$.",
              "En déduire $\\Gamma(n+1) = n!$ pour $n\\in\\mathbb{N}$.",
              "Montrer que $\\Gamma$ est de classe $\\mathcal{C}^{1}$ sur $]0\\,;\\,+\\infty[$.",
              "Déterminer $\\displaystyle\\lim_{x\\to0^{+}}x\\,\\Gamma(x)$."]],
          sol: [["q", "En $0$, $t^{x-1}\\mathrm{e}^{-t}\\sim t^{x-1}$ intégrable car $x>0$ ; en $+\\infty$, domination par $\\mathrm{e}^{-t/2}$.",
            "IPP : $\\Gamma(x+1) = \\big[-t^{x}\\mathrm{e}^{-t}\\big]_{0}^{+\\infty} + x\\displaystyle\\int_{0}^{+\\infty}t^{x-1}\\mathrm{e}^{-t}\\mathrm{d}t$.",
            "$\\Gamma(1) = 1$ puis récurrence.",
            "Domination locale de $|\\ln t|\\,t^{x-1}\\mathrm{e}^{-t}$ sur tout segment $[a\\,;\\,b]\\subset\\,]0\\,;\\,+\\infty[$.",
            "$x\\Gamma(x) = \\Gamma(x+1) \\to \\Gamma(1) = 1$ par continuité."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 4 — Probabilités", st: "Problème : temps d'attente, génératrices, convergences", h: 2, calc: "interdite",
      desc: "Un problème complet de probabilités discrètes autour d'un jeu de collection.",
      ex: [
        {
          t: "Le collectionneur de vignettes", pts: 20, nom: "Problème",
          c: ["Un paquet de céréales contient une vignette choisie uniformément parmi $n$ modèles. On note $T$ le nombre de paquets nécessaires pour obtenir la collection complète.",
            ["h", "Partie A — Décomposition"],
            ["q", "On note $T_{k}$ le nombre de paquets supplémentaires pour passer de $k-1$ à $k$ vignettes distinctes. Donner la loi de $T_{k}$.",
              "Justifier que $T = T_{1}+\\dots+T_{n}$ et que les $T_{k}$ sont indépendantes.",
              "Calculer $E(T)$ et montrer que $E(T) = n H_{n}$.",
              "En déduire un équivalent de $E(T)$ et sa valeur approchée pour $n = 50$."],
            ["h", "Partie B — Variance"],
            ["q", "Calculer $V(T_{k})$, puis $V(T)$.",
              "Montrer que $V(T) \\leqslant \\dfrac{\\pi^{2}n^{2}}{6}$.",
              "À l'aide de Bienaymé-Tchebychev, majorer $P\\big(|T - nH_{n}| \\geqslant n\\ln n\\big)$."],
            ["h", "Partie C — Une autre approche"],
            ["q", "Soit $A_{i}$ l'événement « la vignette $i$ n'apparaît pas dans les $m$ premiers paquets ». Calculer $P(A_{i})$.",
              "Majorer $P(T > m)$ par $n\\left(1-\\tfrac1n\\right)^{m}$.",
              "En déduire que $P\\big(T > n\\ln n + cn\\big) \\leqslant \\mathrm{e}^{-c}$."]],
          sol: [["h", "Partie A"],
            ["q", "Géométrique de paramètre $p_{k} = \\dfrac{n-k+1}{n}$.",
              "La collection progresse par paliers et, à chaque palier, les tirages sont indépendants des précédents.",
              "$E(T) = \\displaystyle\\sum_{k=1}^{n}\\frac{n}{n-k+1} = n\\sum_{j=1}^{n}\\frac{1}{j} = nH_{n}$.",
              "$E(T)\\sim n\\ln n$ ; pour $n=50$, $H_{50}\\approx4{,}499$, soit environ $225$ paquets."],
            ["h", "Partie B"],
            ["q", "$V(T_{k}) = \\dfrac{1-p_{k}}{p_{k}^{2}} \\leqslant \\dfrac{n^{2}}{(n-k+1)^{2}}$ ; par indépendance $V(T) = \\displaystyle\\sum_{k}\\frac{1-p_{k}}{p_{k}^{2}}$.",
              "$V(T) \\leqslant n^{2}\\displaystyle\\sum_{j=1}^{n}\\frac{1}{j^{2}} \\leqslant \\frac{\\pi^{2}n^{2}}{6}$.",
              "$P \\leqslant \\dfrac{V(T)}{n^{2}\\ln^{2}n} \\leqslant \\dfrac{\\pi^{2}}{6\\ln^{2}n}$."],
            ["h", "Partie C"],
            ["q", "$P(A_{i}) = \\left(1-\\tfrac1n\\right)^{m}$.",
              "$\\{T>m\\} = \\bigcup A_{i}$ : la sous-additivité donne la majoration.",
              "Avec $m = n\\ln n + cn$ : $n\\left(1-\\tfrac1n\\right)^{m} \\leqslant n\\,\\mathrm{e}^{-m/n} = n\\,\\mathrm{e}^{-\\ln n - c} = \\mathrm{e}^{-c}$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 5 — Concours blanc", st: "Endomorphismes symétriques, séries et intégrales", h: 3, calc: "interdite",
      desc: "Deux problèmes indépendants dans le format des écrits de concours.",
      ex: [
        {
          t: "Endomorphismes symétriques positifs", pts: 10, nom: "Problème",
          c: ["Soit $E$ un espace euclidien et $u$ un endomorphisme symétrique de $E$.",
            ["h", "Partie A — Généralités"],
            ["q", "Montrer que les sous-espaces propres de $u$ sont deux à deux orthogonaux.",
              "Montrer que $u$ est diagonalisable en base orthonormée.",
              "On suppose $\\langle u(x),x\\rangle \\geqslant 0$ pour tout $x$. Montrer que les valeurs propres de $u$ sont positives."],
            ["h", "Partie B — Racine carrée"],
            ["q", "Montrer qu'il existe un endomorphisme symétrique positif $v$ tel que $v^{2} = u$.",
              "Montrer que $v$ est unique (on pourra utiliser un polynôme).",
              "Application : déterminer la racine carrée symétrique positive de $\\begin{pmatrix}5&4\\\\4&5\\end{pmatrix}$."]],
          sol: [["h", "Partie A"],
            ["q", "Si $u(x)=\\lambda x$ et $u(y)=\\mu y$ avec $\\lambda\\neq\\mu$ : $\\lambda\\langle x,y\\rangle = \\langle u(x),y\\rangle = \\langle x,u(y)\\rangle = \\mu\\langle x,y\\rangle$, donc $\\langle x,y\\rangle = 0$.",
              "Théorème spectral : récurrence sur la dimension, en utilisant la stabilité de l'orthogonal d'une droite propre.",
              "Si $u(x) = \\lambda x$ avec $x\\neq0$ : $\\langle u(x),x\\rangle = \\lambda\\|x\\|^{2}\\geqslant0$ donc $\\lambda\\geqslant0$."],
            ["h", "Partie B"],
            ["q", "Dans une base orthonormée propre, $u = \\mathrm{diag}(\\lambda_{i})$ ; on pose $v = \\mathrm{diag}(\\sqrt{\\lambda_{i}})$ dans la même base.",
              "Un tel $v$ commute avec $u$, donc stabilise les espaces propres de $u$ ; sur $E_{\\lambda}$, $v$ est symétrique positif de carré $\\lambda\\,\\mathrm{id}$, donc $v = \\sqrt{\\lambda}\\,\\mathrm{id}$ : $v$ est déterminé.",
              "Valeurs propres $9$ et $1$, vecteurs $\\tfrac{1}{\\sqrt2}(1,1)$ et $\\tfrac{1}{\\sqrt2}(1,-1)$ : la racine est $\\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$."]],
        },
        {
          t: "Noyau de Dirichlet et série de Riemann", pts: 10, nom: "Problème",
          c: ["On pose $S = \\displaystyle\\sum_{n=1}^{+\\infty}\\frac{1}{n^{2}}$ et, pour $n\\geqslant1$, $I_{n} = \\displaystyle\\int_{0}^{\\pi/2}\\frac{\\sin^{2}(nt)}{\\sin^{2}t}\\,\\mathrm{d}t$.",
            ["q", "Justifier la convergence de la série définissant $S$.",
              "Montrer que $\\displaystyle\\sum_{n=1}^{N}\\frac{1}{n^{2}} \\leqslant 2 - \\frac{1}{N}$.",
              "Montrer que $I_{n+1}-I_{n} = \\displaystyle\\int_{0}^{\\pi/2}\\frac{\\sin((2n+1)t)}{\\sin t}\\,\\mathrm{d}t$.",
              "Montrer que cette intégrale vaut $\\dfrac{\\pi}{2}$ pour tout $n$ (noyau de Dirichlet).",
              "En déduire $I_{n} = \\dfrac{n\\pi}{2}$.",
              "En déduire la valeur moyenne de $t\\mapsto\\dfrac{\\sin^{2}(nt)}{\\sin^{2}t}$ sur $\\left[0\\,;\\,\\tfrac{\\pi}{2}\\right]$, puis un équivalent de $I_{n}$ ; commenter en une phrase le lien avec la majoration de la question 2."]],
          sol: [["q", "Série de Riemann d'exposant $2>1$, à termes positifs.",
            "$\\dfrac{1}{n^{2}}\\leqslant\\dfrac{1}{n(n-1)} = \\dfrac{1}{n-1}-\\dfrac1n$ pour $n\\geqslant2$ : télescopage.",
            "$\\sin^{2}((n+1)t)-\\sin^{2}(nt) = \\sin((2n+1)t)\\sin t$ (formule de factorisation), puis on divise par $\\sin^{2}t$.",
            "$\\dfrac{\\sin((2n+1)t)}{\\sin t} = 1 + 2\\displaystyle\\sum_{k=1}^{n}\\cos(2kt)$, dont l'intégrale sur $\\left[0\\,;\\,\\tfrac{\\pi}{2}\\right]$ vaut $\\tfrac{\\pi}{2}$ (les cosinus s'intègrent en $0$).",
            "$I_{1} = \\tfrac{\\pi}{2}$ et la différence est constante égale à $\\tfrac{\\pi}{2}$ : par récurrence $I_{n} = \\tfrac{n\\pi}{2}$.",
            "La valeur moyenne vaut $\\dfrac{I_{n}}{\\pi/2} = n$, donc $I_{n}\\sim\\tfrac{n\\pi}{2}$ : le noyau de Dirichlet concentre toute sa masse près de $0$, à la manière des termes $\\tfrac{1}{n^{2}}$ dont la somme partielle reste bornée par $2$ (question 2)."]],
        },
      ],
    },
  ]);
})();
