/* Banque — Terminale spécialité mathématiques */
(function () {

  L.addSujets("tle", "fiche", [
    {
      t: "Fiche 1 — Suites : limites et récurrence", st: "Raisonnement par récurrence, convergence, suites auxiliaires", diff: "★★",
      desc: "Démontrer par récurrence, encadrer, conclure sur une limite.",
      intro: "Le réflexe de l'année : pour une suite définie par récurrence, on démontre par récurrence, puis on utilise monotonie et bornes.",
      ex: [
        {
          t: "Une récurrence pour commencer",
          c: ["Soit $(u_{n})$ définie par $u_{0} = 1$ et $u_{n+1} = \\sqrt{3u_{n} + 4}$.",
            ["q", "Calculer $u_{1}$ et $u_{2}$ (valeurs arrondies à $10^{-3}$).",
              "Démontrer par récurrence que pour tout $n$, $1 \\leqslant u_{n} \\leqslant 4$.",
              "Démontrer que $(u_{n})$ est croissante.",
              "En déduire que $(u_{n})$ converge, puis déterminer sa limite."]],
          sol: [["q", "$u_{1} = \\sqrt{7} \\approx 2{,}646$ et $u_{2} = \\sqrt{3\\sqrt{7}+4} \\approx 3{,}440$.",
            "Initialisation : $1 \\leqslant u_{0} = 1 \\leqslant 4$. Hérédité : si $1 \\leqslant u_{n} \\leqslant 4$ alors $7 \\leqslant 3u_{n}+4 \\leqslant 16$, donc $\\sqrt{7} \\leqslant u_{n+1} \\leqslant 4$ et $\\sqrt{7} > 1$.",
            "$u_{n+1}^{2} - u_{n}^{2} = 3u_{n} + 4 - u_{n}^{2} = -(u_{n}-4)(u_{n}+1) \\geqslant 0$ car $1 \\leqslant u_{n} \\leqslant 4$ ; les termes étant positifs, $u_{n+1} \\geqslant u_{n}$.",
            "Croissante et majorée par $4$, elle converge vers $\\ell$ vérifiant $\\ell = \\sqrt{3\\ell+4}$, soit $\\ell^{2} - 3\\ell - 4 = 0$, d'où $\\ell = 4$ (la racine $-1$ est exclue)."]],
        },
        {
          t: "Limites de suites explicites",
          c: ["Déterminer la limite de chacune des suites suivantes, en justifiant :",
            ["q", "$u_{n} = \\dfrac{3n^{2} - 5n}{n^{2} + 1}$", "$v_{n} = n - \\sqrt{n}$", "$w_{n} = \\dfrac{2^{\\,n}}{3^{\\,n}}$",
              "$t_{n} = \\dfrac{\\sin n}{n}$", "$s_{n} = \\dfrac{\\mathrm{e}^{n}}{n^{2}}$"]],
          sol: [["q", "On factorise par $n^{2}$ : $u_{n} = \\dfrac{3 - 5/n}{1 + 1/n^{2}} \\to 3$.",
            "$v_{n} = \\sqrt{n}\\,(\\sqrt{n} - 1) \\to +\\infty$.",
            "$w_{n} = \\left(\\tfrac{2}{3}\\right)^{n} \\to 0$ car $0 < \\tfrac{2}{3} < 1$.",
            "$-\\tfrac{1}{n} \\leqslant t_{n} \\leqslant \\tfrac{1}{n}$ : par encadrement, $t_{n} \\to 0$.",
            "Croissances comparées : $\\dfrac{\\mathrm{e}^{n}}{n^{2}} \\to +\\infty$."]],
        },
        {
          t: "Récurrence et inégalité",
          c: [["q", "Démontrer par récurrence que pour tout entier $n \\geqslant 0$, $2^{\\,n} \\geqslant n + 1$.",
            "Démontrer par récurrence que pour tout $n \\geqslant 1$, $\\displaystyle\\sum_{k=1}^{n} k^{2} = \\frac{n(n+1)(2n+1)}{6}$.",
            "En déduire $\\displaystyle\\lim_{n \\to +\\infty} \\frac{1}{n^{3}}\\sum_{k=1}^{n} k^{2}$."]],
          sol: [["q", "Initialisation : $2^{0} = 1 \\geqslant 1$. Hérédité : $2^{\\,n+1} = 2 \\times 2^{\\,n} \\geqslant 2(n+1) = n + 2 + n \\geqslant n+2$.",
            "Initialisation : pour $n=1$, les deux membres valent $1$. Hérédité : $\\dfrac{n(n+1)(2n+1)}{6} + (n+1)^{2} = \\dfrac{(n+1)\\big[n(2n+1) + 6(n+1)\\big]}{6} = \\dfrac{(n+1)(n+2)(2n+3)}{6}$.",
            "$\\dfrac{n(n+1)(2n+1)}{6n^{3}} \\to \\dfrac{2}{6} = \\dfrac{1}{3}$."]],
        },
        {
          t: "Suite arithmético-géométrique",
          c: ["Soit $(u_{n})$ définie par $u_{0} = 1$ et $u_{n+1} = 0{,}4\\,u_{n} + 3$.",
            ["q", "Déterminer le réel $\\ell$ tel que $\\ell = 0{,}4\\ell + 3$.",
              "On pose $v_{n} = u_{n} - \\ell$. Montrer que $(v_{n})$ est géométrique.",
              "En déduire $u_{n}$ en fonction de $n$, puis $\\displaystyle\\lim_{n\\to+\\infty} u_{n}$.",
              "Déterminer le plus petit entier $n$ tel que $|u_{n} - \\ell| < 10^{-3}$."]],
          sol: [["q", "$0{,}6\\ell = 3$ donc $\\ell = 5$.",
            "$v_{n+1} = 0{,}4u_{n} + 3 - 5 = 0{,}4(u_{n} - 5) = 0{,}4\\,v_{n}$.",
            "$v_{0} = -4$ donc $v_{n} = -4 \\times 0{,}4^{\\,n}$ et $u_{n} = 5 - 4 \\times 0{,}4^{\\,n}$ ; comme $0 < 0{,}4 < 1$, la limite est $5$.",
            "$4 \\times 0{,}4^{\\,n} < 10^{-3} \\iff n > \\dfrac{\\ln(2{,}5 \\times 10^{-4})}{\\ln 0{,}4} \\approx 9{,}05$ : le plus petit entier est $n = 10$."]],
        },
      ],
    },
    {
      t: "Fiche 2 — Limites, continuité et TVI", st: "Limites de fonctions, asymptotes, théorème des valeurs intermédiaires", diff: "★★",
      desc: "Lever des indéterminations, tracer les asymptotes, justifier l'existence d'une solution.",
      ex: [
        {
          t: "Calculs de limites",
          c: ["Déterminer les limites suivantes :",
            ["q", "$\\displaystyle\\lim_{x \\to +\\infty} \\frac{2x^{2} - 3x + 1}{x^{2} + 5}$",
              "$\\displaystyle\\lim_{x \\to 2^{+}} \\frac{x + 1}{x - 2}$",
              "$\\displaystyle\\lim_{x \\to +\\infty} \\left(\\sqrt{x^{2}+x} - x\\right)$",
              "$\\displaystyle\\lim_{x \\to 0} \\frac{\\mathrm{e}^{x} - 1}{x}$"]],
          sol: [["q", "$\\dfrac{2 - 3/x + 1/x^{2}}{1 + 5/x^{2}} \\to 2$.",
            "Le numérateur tend vers $3 > 0$ et le dénominateur vers $0^{+}$ : la limite est $+\\infty$.",
            "On multiplie par la quantité conjuguée : $\\dfrac{x}{\\sqrt{x^{2}+x}+x} = \\dfrac{1}{\\sqrt{1+1/x}+1} \\to \\dfrac{1}{2}$.",
            "C'est le nombre dérivé de $\\exp$ en $0$ : la limite vaut $1$."]],
        },
        {
          t: "Asymptotes",
          c: ["Soit $f(x) = \\dfrac{2x^{2} + 3x - 1}{x - 1}$ sur $\\mathbb{R} \\setminus \\{1\\}$.",
            ["q", "Déterminer les limites de $f$ en $1^{-}$, $1^{+}$, $-\\infty$ et $+\\infty$.",
              "Montrer que $f(x) = 2x + 5 + \\dfrac{4}{x-1}$.",
              "En déduire que la droite $d : y = 2x + 5$ est asymptote oblique à la courbe en $\\pm\\infty$.",
              "Étudier la position de la courbe par rapport à $d$."]],
          sol: [["q", "En $1^{-}$ : $-\\infty$ ; en $1^{+}$ : $+\\infty$ ; en $\\pm\\infty$ : $\\pm\\infty$ (le quotient se comporte comme $2x$).",
            "$(2x+5)(x-1) + 4 = 2x^{2} + 3x - 5 + 4 = 2x^{2} + 3x - 1$.",
            "$f(x) - (2x+5) = \\dfrac{4}{x-1} \\to 0$ quand $x \\to \\pm\\infty$.",
            "La différence est du signe de $x - 1$ : la courbe est au-dessus de $d$ pour $x > 1$, en dessous pour $x < 1$."]],
        },
        {
          t: "Théorème des valeurs intermédiaires",
          c: ["Soit $f(x) = x^{3} + x - 3$ sur $\\mathbb{R}$.",
            ["q", "Étudier les variations de $f$.",
              "Démontrer que l'équation $f(x) = 0$ admet une unique solution $\\alpha$ dans $\\mathbb{R}$.",
              "Justifier que $\\alpha \\in [1\\,;\\,2]$, puis donner un encadrement d'amplitude $10^{-2}$.",
              "Écrire un algorithme de dichotomie donnant un encadrement de $\\alpha$ d'amplitude $\\varepsilon$."]],
          sol: [["q", "$f'(x) = 3x^{2} + 1 > 0$ : $f$ est strictement croissante sur $\\mathbb{R}$.",
            "$f$ est continue et strictement croissante, avec $\\lim_{-\\infty} f = -\\infty$ et $\\lim_{+\\infty} f = +\\infty$ : d'après le corollaire du TVI, l'équation a une unique solution.",
            "$f(1) = -1 < 0$ et $f(2) = 7 > 0$ donc $\\alpha \\in \\,]1\\,;\\,2[$ ; à la calculatrice $1{,}21 < \\alpha < 1{,}22$.",
            "Boucle $\\texttt{while b - a > eps}$ : si $f(a)f(m) \\leqslant 0$ alors $\\texttt{b = m}$ sinon $\\texttt{a = m}$, avec $m = (a+b)/2$."]],
        },
        {
          t: "Continuité d'une fonction par morceaux",
          c: ["Soit $f$ définie par $f(x) = \\dfrac{x^{2} - 4}{x - 2}$ si $x \\neq 2$ et $f(2) = a$.",
            ["q", "Simplifier $f(x)$ pour $x \\neq 2$.",
              "Déterminer la valeur de $a$ rendant $f$ continue en $2$.",
              "Avec cette valeur, $f$ est-elle dérivable en $2$ ?"]],
          sol: [["q", "$f(x) = \\dfrac{(x-2)(x+2)}{x-2} = x + 2$.",
            "$\\lim_{x \\to 2} f(x) = 4$ : il faut $a = 4$.",
            "Oui : $f$ coïncide alors avec la fonction affine $x \\mapsto x+2$, dérivable partout, de dérivée $1$."]],
        },
      ],
    },
    {
      t: "Fiche 3 — Dérivation, composées et convexité", st: "Dérivées de composées, dérivée seconde, points d'inflexion", diff: "★★",
      desc: "Dériver une composée sans erreur, lire la convexité, situer une tangente.",
      ex: [
        {
          t: "Dérivées de composées",
          c: ["Dériver les fonctions suivantes :",
            ["q", "$f(x) = (3x + 1)^{5}$", "$g(x) = \\sqrt{x^{2} + 1}$", "$h(x) = \\mathrm{e}^{-2x + 3}$",
              "$k(x) = \\ln(x^{2} + 1)$", "$m(x) = \\cos(3x)\\,\\mathrm{e}^{x}$"]],
          sol: [["q", "$f'(x) = 15(3x+1)^{4}$.",
            "$g'(x) = \\dfrac{x}{\\sqrt{x^{2}+1}}$.",
            "$h'(x) = -2\\,\\mathrm{e}^{-2x+3}$.",
            "$k'(x) = \\dfrac{2x}{x^{2}+1}$.",
            "$m'(x) = \\mathrm{e}^{x}\\big(\\cos(3x) - 3\\sin(3x)\\big)$."]],
        },
        {
          t: "Convexité",
          c: ["Soit $f(x) = x^{3} - 3x^{2} + 2$ sur $\\mathbb{R}$.",
            ["q", "Calculer $f'(x)$ et $f''(x)$.",
              "Étudier le signe de $f''$ et en déduire les intervalles de convexité de $f$.",
              "Montrer que la courbe admet un point d'inflexion dont on donnera les coordonnées.",
              "Déterminer l'équation de la tangente en ce point."]],
          sol: [["q", "$f'(x) = 3x^{2} - 6x$ et $f''(x) = 6x - 6$.",
            "$f''(x) \\geqslant 0 \\iff x \\geqslant 1$ : $f$ est convexe sur $[1\\,;\\,+\\infty[$ et concave sur $]-\\infty\\,;\\,1]$.",
            "$f''$ s'annule en changeant de signe en $x = 1$ : point d'inflexion $I(1\\,;\\,0)$.",
            "$f'(1) = -3$ : la tangente a pour équation $y = -3(x-1) = -3x + 3$."]],
        },
        {
          t: "Position par rapport à une tangente",
          c: ["Soit $f(x) = \\mathrm{e}^{x}$ et $T$ la tangente à sa courbe au point d'abscisse $0$.",
            ["q", "Déterminer une équation de $T$.",
              "Étudier le signe de $g(x) = \\mathrm{e}^{x} - x - 1$ sur $\\mathbb{R}$.",
              "En déduire la position de la courbe de $f$ par rapport à $T$.",
              "Quel résultat de convexité retrouve-t-on ainsi ?"]],
          sol: [["q", "$f(0) = 1$, $f'(0) = 1$ : $T : y = x + 1$.",
            "$g'(x) = \\mathrm{e}^{x} - 1$, négative sur $]-\\infty\\,;\\,0]$ et positive ensuite : $g$ admet un minimum $g(0) = 0$, donc $g \\geqslant 0$.",
            "La courbe est toujours au-dessus de $T$ (contact en $x = 0$).",
            "Une fonction convexe ($f'' = \\mathrm{e}^{x} > 0$) a sa courbe au-dessus de chacune de ses tangentes."]],
        },
        {
          t: "Coût marginal",
          c: ["Le coût total de production, en milliers d'euros, de $x$ tonnes d'un produit ($0 < x \\leqslant 10$) est $C(x) = 0{,}1x^{3} - 1{,}5x^{2} + 12x$.",
            ["q", "Calculer le coût marginal $C'(x)$.",
              "Étudier la convexité de $C$ et donner l'abscisse du point d'inflexion.",
              "Interpréter économiquement ce point d'inflexion.",
              "Déterminer la production pour laquelle le coût marginal est minimal."]],
          sol: [["q", "$C'(x) = 0{,}3x^{2} - 3x + 12$.",
            "$C''(x) = 0{,}6x - 3$, qui s'annule en $x = 5$ : $C$ est concave sur $]0\\,;\\,5]$, convexe sur $[5\\,;\\,10]$.",
            "Jusqu'à $5$ tonnes, chaque tonne supplémentaire coûte de moins en moins cher ; au-delà, le coût marginal repart à la hausse.",
            "$C'$ est un trinôme de sommet $x = 5$ : le coût marginal minimal vaut $C'(5) = 7{,}5 - 15 + 12 = 4{,}5$ milliers d'euros par tonne."]],
        },
      ],
    },
    {
      t: "Fiche 4 — Logarithme népérien", st: "Propriétés, équations, dérivées, croissances comparées", diff: "★★",
      desc: "Le logarithme comme outil de calcul, puis comme fonction à étudier.",
      ex: [
        {
          t: "Équations et inéquations",
          c: ["Résoudre dans $\\mathbb{R}$ (en précisant le domaine) :",
            ["q", "$\\ln(x) + \\ln(x - 1) = \\ln 6$", "$\\ln(2x - 1) \\leqslant 0$",
              "$\\mathrm{e}^{x} = 7$", "$2^{\\,n} > 10^{6}$ (avec $n$ entier)"]],
          sol: [["q", "Domaine $x > 1$ ; $x(x-1) = 6 \\iff x^{2} - x - 6 = 0 \\iff x = 3$ ou $x = -2$ : seul $x = 3$ convient.",
            "Domaine $x > \\tfrac{1}{2}$ ; $\\ln(2x-1) \\leqslant \\ln 1 \\iff 2x - 1 \\leqslant 1 \\iff x \\leqslant 1$ : $S = \\,]\\tfrac{1}{2}\\,;\\,1]$.",
            "$x = \\ln 7 \\approx 1{,}946$.",
            "$n\\ln 2 > 6\\ln 10 \\iff n > \\dfrac{6\\ln 10}{\\ln 2} \\approx 19{,}93$ : $n \\geqslant 20$."]],
        },
        {
          t: "Étude d'une fonction",
          c: ["Soit $f(x) = x - \\ln x$ sur $]0\\,;\\,+\\infty[$.",
            ["q", "Déterminer les limites de $f$ en $0^{+}$ et en $+\\infty$.",
              "Calculer $f'(x)$ et dresser le tableau de variations.",
              "En déduire que $f(x) \\geqslant 1$ pour tout $x > 0$.",
              "Que peut-on en déduire sur le nombre de solutions de $f(x) = 0$ ?"]],
          sol: [["q", "En $0^{+}$ : $-\\ln x \\to +\\infty$ donc $f \\to +\\infty$ ; en $+\\infty$ : $f(x) = x\\left(1 - \\tfrac{\\ln x}{x}\\right) \\to +\\infty$.",
            "$f'(x) = 1 - \\tfrac{1}{x} = \\tfrac{x-1}{x}$ : $f$ décroît sur $]0\\,;\\,1]$, croît sur $[1\\,;\\,+\\infty[$.",
            "Le minimum est $f(1) = 1$, donc $f(x) \\geqslant 1$.",
            "$f(x) = 0$ n'a aucune solution ; au passage, $\\ln x \\leqslant x - 1$ pour tout $x > 0$."]],
        },
        {
          t: "Croissances comparées",
          c: ["Déterminer les limites suivantes :",
            ["q", "$\\displaystyle\\lim_{x \\to +\\infty} \\frac{\\ln x}{x}$", "$\\displaystyle\\lim_{x \\to 0^{+}} x\\ln x$",
              "$\\displaystyle\\lim_{x \\to +\\infty} \\frac{\\mathrm{e}^{x}}{x^{3}}$", "$\\displaystyle\\lim_{x \\to +\\infty} \\big(x - \\ln(x^{2}+1)\\big)$"]],
          sol: [["q", "$0$ (croissance comparée).", "$0$ (croissance comparée).", "$+\\infty$.",
            "$x - \\ln(x^{2}+1) = x\\left(1 - \\dfrac{\\ln(x^{2}+1)}{x}\\right)$ et $\\dfrac{\\ln(x^{2}+1)}{x} \\to 0$ : la limite est $+\\infty$."]],
        },
        {
          t: "Demi-vie et datation",
          c: ["La masse d'un échantillon de carbone 14, en grammes, après $t$ années, est $m(t) = 10\\,\\mathrm{e}^{-0{,}000121\\,t}$.",
            ["q", "Calculer la masse restante après $1\\,000$ ans.",
              "Déterminer la demi-vie, c'est-à-dire le temps au bout duquel il ne reste que $5$ g.",
              "Un fossile contient $22\\,\\%$ du carbone 14 initial. Estimer son âge.",
              "Justifier que $m$ est décroissante et convexe."]],
          sol: [["q", "$m(1000) = 10\\,\\mathrm{e}^{-0{,}121} \\approx 8{,}86$ g.",
            "$\\mathrm{e}^{-0{,}000121t} = 0{,}5 \\iff t = \\dfrac{\\ln 2}{0{,}000121} \\approx 5\\,728$ ans.",
            "$t = \\dfrac{-\\ln 0{,}22}{0{,}000121} \\approx 12\\,510$ ans.",
            "$m'(t) = -0{,}00121\\,\\mathrm{e}^{-0{,}000121t} < 0$ et $m''(t) > 0$ : décroissante et convexe."]],
        },
      ],
    },
    {
      t: "Fiche 5 — Exponentielle : études et modèles", st: "Étude de fonctions, équations, modèle logistique", diff: "★★★",
      desc: "Deux études complètes et deux modèles issus des sciences.",
      ex: [
        {
          t: "Étude complète",
          c: ["Soit $f(x) = x\\,\\mathrm{e}^{-x}$ sur $\\mathbb{R}$.",
            ["q", "Déterminer les limites de $f$ en $-\\infty$ et $+\\infty$.",
              "Calculer $f'(x)$ et dresser le tableau de variations.",
              "Déterminer le maximum de $f$.",
              "Étudier la convexité de $f$ et préciser le point d'inflexion.",
              "Déterminer l'équation de la tangente à l'origine."]],
          sol: [["q", "En $-\\infty$ : $x \\to -\\infty$ et $\\mathrm{e}^{-x} \\to +\\infty$, donc $f \\to -\\infty$ ; en $+\\infty$ : croissance comparée, $f \\to 0^{+}$.",
            "$f'(x) = (1 - x)\\mathrm{e}^{-x}$ : croissante sur $]-\\infty\\,;\\,1]$, décroissante ensuite.",
            "Maximum $f(1) = \\mathrm{e}^{-1} \\approx 0{,}368$.",
            "$f''(x) = (x - 2)\\mathrm{e}^{-x}$ : concave sur $]-\\infty\\,;\\,2]$, convexe après ; point d'inflexion $\\left(2\\,;\\,2\\mathrm{e}^{-2}\\right)$.",
            "$f(0) = 0$ et $f'(0) = 1$ : $y = x$."]],
        },
        {
          t: "Avec un paramètre",
          c: ["Pour $k > 0$, soit $f_{k}(x) = \\mathrm{e}^{-kx}$.",
            ["q", "Montrer que toutes les courbes passent par un même point.",
              "Calculer $f_{k}'(0)$ : quelle est l'influence de $k$ sur la pente à l'origine ?",
              "Résoudre $f_{k}(x) = \\tfrac{1}{2}$ en fonction de $k$.",
              "Pour quelle valeur de $k$ a-t-on $f_{k}(5) = 0{,}1$ ?"]],
          sol: [["q", "$f_{k}(0) = 1$ : toutes passent par $(0\\,;\\,1)$.",
            "$f_{k}'(x) = -k\\mathrm{e}^{-kx}$ donc $f_{k}'(0) = -k$ : plus $k$ est grand, plus la décroissance initiale est rapide.",
            "$-kx = \\ln\\tfrac{1}{2}$ donc $x = \\dfrac{\\ln 2}{k}$.",
            "$\\mathrm{e}^{-5k} = 0{,}1 \\iff k = \\dfrac{\\ln 10}{5} \\approx 0{,}461$."]],
        },
        {
          t: "Le modèle logistique",
          c: ["Le nombre de personnes (en milliers) informées d'une rumeur après $t$ jours est",
            ["$", "N(t) = \\frac{50}{1 + 49\\,\\mathrm{e}^{-0{,}6t}}."],
            ["q", "Calculer $N(0)$ et interpréter.",
              "Déterminer $\\displaystyle\\lim_{t \\to +\\infty} N(t)$ et interpréter.",
              "Résoudre $N(t) = 25$ : que représente cet instant ?",
              "Justifier que $N$ est croissante."]],
          sol: [["q", "$N(0) = \\dfrac{50}{50} = 1$ : mille personnes au départ.",
            "$\\mathrm{e}^{-0{,}6t} \\to 0$ donc $N(t) \\to 50$ : la rumeur touche au plus $50\\,000$ personnes.",
            "$1 + 49\\mathrm{e}^{-0{,}6t} = 2 \\iff \\mathrm{e}^{-0{,}6t} = \\tfrac{1}{49} \\iff t = \\dfrac{\\ln 49}{0{,}6} \\approx 6{,}5$ jours : c'est l'instant où la moitié de la population est informée, là où la propagation est la plus rapide.",
            "Le dénominateur est strictement décroissant et positif, donc $N$ est strictement croissante."]],
        },
        {
          t: "Charge d'un condensateur",
          c: ["La tension aux bornes d'un condensateur, en volts, vérifie $u(t) = 12\\left(1 - \\mathrm{e}^{-t/\\tau}\\right)$ avec $\\tau = 0{,}5$ s.",
            ["q", "Calculer $u(0)$ et $\\displaystyle\\lim_{t\\to+\\infty} u(t)$.",
              "Calculer $u(\\tau)$ : quel pourcentage de la tension finale est atteint ?",
              "Au bout de combien de temps la tension atteint-elle $11$ V ?",
              "Montrer que $u$ vérifie $\\tau u'(t) + u(t) = 12$."]],
          sol: [["q", "$u(0) = 0$ et la limite vaut $12$ V.",
            "$u(\\tau) = 12(1 - \\mathrm{e}^{-1}) \\approx 7{,}59$ V, soit environ $63\\,\\%$ de la tension finale.",
            "$\\mathrm{e}^{-2t} = \\tfrac{1}{12} \\iff t = \\tfrac{\\ln 12}{2} \\approx 1{,}24$ s.",
            "$u'(t) = \\dfrac{12}{\\tau}\\mathrm{e}^{-t/\\tau}$ donc $\\tau u' + u = 12\\mathrm{e}^{-t/\\tau} + 12 - 12\\mathrm{e}^{-t/\\tau} = 12$."]],
        },
      ],
    },
    {
      t: "Fiche 6 — Primitives et intégrales", st: "Primitives usuelles, calcul d'aires, valeur moyenne", diff: "★★",
      desc: "Reconnaître une primitive, calculer une aire, interpréter une intégrale.",
      ex: [
        {
          t: "Primitives à reconnaître",
          c: ["Déterminer une primitive de chacune des fonctions suivantes sur un intervalle adapté :",
            ["q", "$f(x) = 3x^{2} - 4x + 1$", "$g(x) = \\dfrac{1}{x}$", "$h(x) = \\mathrm{e}^{3x}$",
              "$k(x) = \\dfrac{2x}{x^{2}+1}$", "$m(x) = (2x+1)^{4}$"]],
          sol: [["q", "$F(x) = x^{3} - 2x^{2} + x$.", "$G(x) = \\ln x$ sur $]0\\,;\\,+\\infty[$.",
            "$H(x) = \\tfrac{1}{3}\\mathrm{e}^{3x}$.", "$K(x) = \\ln(x^{2}+1)$.", "$M(x) = \\tfrac{1}{10}(2x+1)^{5}$."]],
        },
        {
          t: "Calculs d'intégrales",
          c: ["Calculer :",
            ["q", "$\\displaystyle\\int_{0}^{2} (3x^{2} - 1)\\,\\mathrm{d}x$", "$\\displaystyle\\int_{1}^{\\mathrm{e}} \\frac{1}{x}\\,\\mathrm{d}x$",
              "$\\displaystyle\\int_{0}^{1} \\mathrm{e}^{-x}\\,\\mathrm{d}x$", "$\\displaystyle\\int_{0}^{1} x\\,\\mathrm{e}^{x}\\,\\mathrm{d}x$ (intégration par parties)"]],
          sol: [["q", "$\\big[x^{3} - x\\big]_{0}^{2} = 8 - 2 = 6$.", "$\\big[\\ln x\\big]_{1}^{\\mathrm{e}} = 1$.",
            "$\\big[-\\mathrm{e}^{-x}\\big]_{0}^{1} = 1 - \\mathrm{e}^{-1} \\approx 0{,}632$.",
            "$\\big[x\\mathrm{e}^{x}\\big]_{0}^{1} - \\displaystyle\\int_{0}^{1}\\mathrm{e}^{x}\\mathrm{d}x = \\mathrm{e} - (\\mathrm{e} - 1) = 1$."]],
        },
        {
          t: "Aire entre deux courbes",
          c: ["Soit $f(x) = x^{2}$ et $g(x) = 2x$ sur $[0\\,;\\,2]$.",
            ["q", "Déterminer les points d'intersection des deux courbes.",
              "Étudier le signe de $g(x) - f(x)$ sur $[0\\,;\\,2]$.",
              "Calculer l'aire du domaine compris entre les deux courbes.",
              "Donner la valeur moyenne de $f$ sur $[0\\,;\\,2]$."]],
          sol: [["q", "$x^{2} = 2x \\iff x(x-2) = 0$ : les points $(0\\,;\\,0)$ et $(2\\,;\\,4)$.",
            "$g(x) - f(x) = x(2 - x) \\geqslant 0$ sur $[0\\,;\\,2]$ : la droite est au-dessus de la parabole.",
            "$\\displaystyle\\int_{0}^{2}(2x - x^{2})\\mathrm{d}x = \\Big[x^{2} - \\tfrac{x^{3}}{3}\\Big]_{0}^{2} = 4 - \\tfrac{8}{3} = \\tfrac{4}{3}$ unité d'aire.",
            "$\\mu = \\tfrac{1}{2}\\displaystyle\\int_{0}^{2} x^{2}\\mathrm{d}x = \\tfrac{1}{2} \\times \\tfrac{8}{3} = \\tfrac{4}{3}$."]],
        },
        {
          t: "Énergie consommée",
          c: ["La puissance électrique consommée par un appareil, en kW, est $p(t) = 2 + \\sin\\!\\left(\\dfrac{\\pi t}{12}\\right)$ pour $t \\in [0\\,;\\,24]$ (en heures).",
            ["q", "L'énergie consommée sur $[0\\,;\\,24]$ vaut $\\displaystyle\\int_{0}^{24} p(t)\\,\\mathrm{d}t$. Calculer cette intégrale.",
              "En déduire la puissance moyenne sur la journée.",
              "À quel instant la puissance est-elle maximale ? Que vaut-elle ?"]],
          sol: [["q", "Une primitive est $P(t) = 2t - \\tfrac{12}{\\pi}\\cos\\!\\left(\\tfrac{\\pi t}{12}\\right)$ ; $P(24) - P(0) = 48 - \\tfrac{12}{\\pi} + \\tfrac{12}{\\pi} = 48$ kWh.",
            "$\\mu = \\tfrac{48}{24} = 2$ kW.",
            "Le maximum est atteint quand $\\sin\\!\\left(\\tfrac{\\pi t}{12}\\right) = 1$, soit $t = 6$ h : la puissance vaut alors $3$ kW."]],
        },
      ],
    },
    {
      t: "Fiche 7 — Géométrie dans l'espace", st: "Vecteurs, droites, plans, représentations paramétriques", diff: "★★",
      desc: "Coordonnées, colinéarité, coplanarité et intersections dans l'espace.",
      ex: [
        {
          t: "Vecteurs de l'espace",
          c: ["Dans un repère orthonormé, $A(1\\,;\\,0\\,;\\,2)$, $B(3\\,;\\,-1\\,;\\,4)$, $C(0\\,;\\,2\\,;\\,1)$ et $D(5\\,;\\,-2\\,;\\,6)$.",
            ["q", "Calculer les coordonnées de $\\vec{AB}$ et $\\vec{AD}$.",
              "Les points $A$, $B$ et $D$ sont-ils alignés ?",
              "Calculer $AB$ et $AC$.",
              "Déterminer les coordonnées du point $E$ tel que $ABEC$ soit un parallélogramme."]],
          sol: [["q", "$\\vec{AB}(2\\,;\\,-1\\,;\\,2)$ et $\\vec{AD}(4\\,;\\,-2\\,;\\,4)$.",
            "$\\vec{AD} = 2\\vec{AB}$ : les trois points sont alignés.",
            "$AB = \\sqrt{4+1+4} = 3$ et $AC = \\sqrt{1+4+1} = \\sqrt{6}$.",
            "$\\vec{AB} = \\vec{CE}$ donne $E(0+2\\,;\\,2-1\\,;\\,1+2) = E(2\\,;\\,1\\,;\\,3)$."]],
        },
        {
          t: "Droites de l'espace",
          c: ["Soit $d$ la droite passant par $A(1\\,;\\,2\\,;\\,-1)$ de vecteur directeur $\\vec{u}(2\\,;\\,-1\\,;\\,3)$, et $d'$ définie par",
            ["$", "\\begin{cases} x = 3 + t \\\\ y = 1 - t \\\\ z = 2t \\end{cases}, \\quad t \\in \\mathbb{R}."],
            ["q", "Donner une représentation paramétrique de $d$.",
              "Les droites $d$ et $d'$ sont-elles parallèles ?",
              "Déterminer si elles sont sécantes.",
              "Le point $M(5\\,;\\,0\\,;\\,5)$ appartient-il à $d$ ?"]],
          sol: [["q", "$x = 1 + 2s$, $y = 2 - s$, $z = -1 + 3s$.",
            "$\\vec{u}(2\\,;\\,-1\\,;\\,3)$ et $\\vec{v}(1\\,;\\,-1\\,;\\,2)$ ne sont pas colinéaires : elles ne sont pas parallèles.",
            "Le système $1+2s = 3+t$, $2-s = 1-t$, $-1+3s = 2t$ donne $s = 1$, $t = 0$ dans les deux premières, mais $-1+3 = 2 \\neq 0$ : les droites ne sont pas sécantes, elles sont non coplanaires.",
            "$1 + 2s = 5$ donne $s = 2$, alors $y = 0$ et $z = 5$ : oui, $M \\in d$."]],
        },
        {
          t: "Plans",
          c: ["Soit le plan $\\mathcal{P}$ d'équation $2x - y + 3z - 6 = 0$.",
            ["q", "Donner un vecteur normal à $\\mathcal{P}$.",
              "Le point $A(1\\,;\\,-1\\,;\\,1)$ appartient-il à $\\mathcal{P}$ ?",
              "Déterminer une équation du plan $\\mathcal{Q}$ parallèle à $\\mathcal{P}$ passant par $B(0\\,;\\,0\\,;\\,1)$.",
              "Déterminer l'intersection de $\\mathcal{P}$ avec l'axe des cotes."]],
          sol: [["q", "$\\vec{n}(2\\,;\\,-1\\,;\\,3)$.",
            "$2 + 1 + 3 - 6 = 0$ : oui.",
            "$2x - y + 3z + c = 0$ avec $B$ : $3 + c = 0$, donc $2x - y + 3z - 3 = 0$.",
            "Pour $x = y = 0$ : $3z = 6$, soit le point $(0\\,;\\,0\\,;\\,2)$."]],
        },
        {
          t: "Droite et plan",
          c: ["Soit $d : x = 1 + t$, $y = 2t$, $z = -1 + 3t$ et $\\mathcal{P} : x + y + z - 4 = 0$.",
            ["q", "Le vecteur directeur de $d$ est-il orthogonal au vecteur normal de $\\mathcal{P}$ ?",
              "En déduire que $d$ et $\\mathcal{P}$ sont sécants.",
              "Déterminer les coordonnées du point d'intersection.",
              "Déterminer une équation du plan contenant $d$ et parallèle à l'axe $(Oz)$."]],
          sol: [["q", "$\\vec{u}(1\\,;\\,2\\,;\\,3)$ et $\\vec{n}(1\\,;\\,1\\,;\\,1)$ : $1 + 2 + 3 = 6 \\neq 0$, ils ne sont pas orthogonaux.",
            "Le vecteur directeur n'étant pas orthogonal au vecteur normal, la droite n'est pas parallèle au plan : ils sont sécants en un point.",
            "$(1+t) + 2t + (-1+3t) - 4 = 6t - 4 = 0$ donne $t = \\tfrac{2}{3}$, d'où le point $\\left(\\tfrac{5}{3}\\,;\\,\\tfrac{4}{3}\\,;\\,1\\right)$.",
            "Un tel plan a un vecteur normal orthogonal à $\\vec{u}$ et à $\\vec{k}(0\\,;\\,0\\,;\\,1)$, par exemple $\\vec{n}(2\\,;\\,-1\\,;\\,0)$ : $2x - y - 2 = 0$."]],
        },
      ],
    },
    {
      t: "Fiche 8 — Produit scalaire dans l'espace", st: "Orthogonalité, équations de plans, distances, projeté", diff: "★★★",
      desc: "Du cube en coordonnées au calcul de distance d'un point à un plan.",
      ex: [
        {
          t: "Orthogonalité",
          c: ["Dans un repère orthonormé, $A(2\\,;\\,1\\,;\\,0)$, $B(1\\,;\\,-1\\,;\\,3)$ et $C(4\\,;\\,0\\,;\\,1)$.",
            ["q", "Calculer $\\vec{AB} \\cdot \\vec{AC}$.",
              "Le triangle $ABC$ est-il rectangle en $A$ ?",
              "Calculer une valeur approchée de l'angle $\\widehat{BAC}$.",
              "Déterminer une équation du plan $(ABC)$."]],
          sol: [["q", "$\\vec{AB}(-1\\,;\\,-2\\,;\\,3)$, $\\vec{AC}(2\\,;\\,-1\\,;\\,1)$ : $-2 + 2 + 3 = 3$.",
            "Non : le produit scalaire n'est pas nul.",
            "$AB = \\sqrt{14}$, $AC = \\sqrt{6}$, $\\cos(\\widehat{BAC}) = \\dfrac{3}{\\sqrt{84}} \\approx 0{,}327$, soit environ $70{,}9^{\\circ}$.",
            "Un vecteur normal $\\vec{n}(a\\,;\\,b\\,;\\,c)$ vérifie $-a-2b+3c = 0$ et $2a-b+c = 0$ ; on trouve par exemple $\\vec{n}(1\\,;\\,7\\,;\\,5)$, d'où $x + 7y + 5z - 9 = 0$."]],
        },
        {
          t: "Distance d'un point à un plan",
          c: ["Soit $\\mathcal{P} : 2x - 2y + z - 3 = 0$ et $M(4\\,;\\,1\\,;\\,2)$.",
            ["q", "Donner un vecteur normal unitaire de $\\mathcal{P}$.",
              "Calculer la distance de $M$ à $\\mathcal{P}$.",
              "Déterminer une représentation paramétrique de la droite passant par $M$ et orthogonale à $\\mathcal{P}$.",
              "En déduire les coordonnées du projeté orthogonal $H$ de $M$ sur $\\mathcal{P}$."]],
          sol: [["q", "$\\vec{n}(2\\,;\\,-2\\,;\\,1)$ de norme $3$ : $\\tfrac{1}{3}(2\\,;\\,-2\\,;\\,1)$.",
            "$d = \\dfrac{|8 - 2 + 2 - 3|}{3} = \\dfrac{5}{3}$.",
            "$x = 4 + 2t$, $y = 1 - 2t$, $z = 2 + t$.",
            "En reportant : $2(4+2t) - 2(1-2t) + (2+t) - 3 = 9t + 5 = 0$, soit $t = -\\tfrac{5}{9}$ et $H\\!\\left(\\tfrac{26}{9}\\,;\\,\\tfrac{19}{9}\\,;\\,\\tfrac{13}{9}\\right)$."]],
        },
        {
          t: "Le cube",
          c: ["$ABCDEFGH$ est un cube d'arête $1$. On se place dans le repère orthonormé $\\left(A\\,;\\,\\vec{AB},\\vec{AD},\\vec{AE}\\right)$.",
            ["q", "Donner les coordonnées des huit sommets.",
              "Calculer $\\vec{AG} \\cdot \\vec{BD}$ et interpréter.",
              "Calculer une valeur approchée de l'angle entre la diagonale $(AG)$ et la face $ABCD$.",
              "Déterminer une équation du plan $(BDE)$."]],
          sol: [["q", "$A(0\\,;\\,0\\,;\\,0)$, $B(1\\,;\\,0\\,;\\,0)$, $C(1\\,;\\,1\\,;\\,0)$, $D(0\\,;\\,1\\,;\\,0)$, $E(0\\,;\\,0\\,;\\,1)$, $F(1\\,;\\,0\\,;\\,1)$, $G(1\\,;\\,1\\,;\\,1)$, $H(0\\,;\\,1\\,;\\,1)$.",
            "$\\vec{AG}(1\\,;\\,1\\,;\\,1)$ et $\\vec{BD}(-1\\,;\\,1\\,;\\,0)$ : le produit scalaire vaut $0$, la grande diagonale est orthogonale à $(BD)$.",
            "Le projeté de $G$ sur la face est $C$ : $\\cos\\theta = \\dfrac{AC}{AG} = \\dfrac{\\sqrt{2}}{\\sqrt{3}} \\approx 0{,}816$, soit $\\theta \\approx 35{,}3^{\\circ}$.",
            "$\\vec{AG}(1\\,;\\,1\\,;\\,1)$ est normal au plan $(BDE)$ : $x + y + z - 1 = 0$ (vérifié par $B$, $D$ et $E$)."]],
        },
        {
          t: "Sphère et plan",
          c: ["Soit $\\mathcal{S}$ l'ensemble des points $M(x\\,;\\,y\\,;\\,z)$ tels que $x^{2}+y^{2}+z^{2} - 2x + 4y - 4 = 0$.",
            ["q", "Montrer que $\\mathcal{S}$ est une sphère de centre $\\Omega$ et de rayon $R$ à préciser.",
              "Le plan $\\mathcal{P} : z = 3$ coupe-t-il $\\mathcal{S}$ ?",
              "Déterminer la nature et le rayon de l'intersection de $\\mathcal{S}$ avec le plan $z = 0$."]],
          sol: [["q", "$(x-1)^{2} + (y+2)^{2} + z^{2} = 4 + 1 + 4 = 9$ : sphère de centre $\\Omega(1\\,;\\,-2\\,;\\,0)$ et de rayon $3$.",
            "La distance de $\\Omega$ au plan $z = 3$ vaut $3 = R$ : le plan est tangent à la sphère (un seul point de contact).",
            "La distance de $\\Omega$ au plan $z = 0$ est nulle : l'intersection est un grand cercle, de centre $\\Omega$ et de rayon $3$."]],
        },
      ],
    },
    {
      t: "Fiche 9 — Probabilités : conditionnement et lois", st: "Arbres, loi binomiale, variables aléatoires, sommes", diff: "★★",
      desc: "Du conditionnement aux sommes de variables aléatoires.",
      ex: [
        {
          t: "Arbre et probabilités totales",
          c: ["Un site propose deux modes de livraison : standard ($70\\,\\%$ des commandes) et express. Une livraison standard est en retard avec une probabilité $0{,}12$, une express avec une probabilité $0{,}03$.",
            ["q", "Représenter la situation par un arbre pondéré.",
              "Calculer la probabilité qu'une commande soit en retard.",
              "Une commande est en retard : quelle est la probabilité qu'elle ait été en livraison express ?",
              "Les événements « livraison express » et « retard » sont-ils indépendants ?"]],
          sol: [["q", "$P(S) = 0{,}7$, $P(E) = 0{,}3$, puis $P_{S}(R) = 0{,}12$ et $P_{E}(R) = 0{,}03$.",
            "$P(R) = 0{,}7 \\times 0{,}12 + 0{,}3 \\times 0{,}03 = 0{,}084 + 0{,}009 = 0{,}093$.",
            "$P_{R}(E) = \\dfrac{0{,}009}{0{,}093} \\approx 0{,}097$.",
            "$P(E \\cap R) = 0{,}009$ et $P(E)P(R) = 0{,}3 \\times 0{,}093 = 0{,}0279$ : ils ne sont pas indépendants."]],
        },
        {
          t: "Loi binomiale",
          c: ["Un joueur de basket réussit ses lancers francs avec une probabilité $0{,}8$. Il en tente $10$, de façon indépendante. On note $X$ le nombre de réussites.",
            ["q", "Donner la loi de $X$.",
              "Calculer $P(X = 8)$ à $10^{-3}$ près.",
              "Calculer $P(X \\geqslant 9)$.",
              "Calculer $E(X)$ et $\\sigma(X)$.",
              "Combien de lancers doit-il tenter pour que la probabilité d'en réussir au moins un dépasse $0{,}999$ ?"]],
          sol: [["q", "$X \\sim \\mathcal{B}(10\\,;\\,0{,}8)$.",
            "$P(X=8) = \\binom{10}{8}0{,}8^{8}0{,}2^{2} \\approx 0{,}302$.",
            "$P(X \\geqslant 9) = P(X=9) + P(X=10) \\approx 0{,}268 + 0{,}107 = 0{,}376$.",
            "$E(X) = 8$ et $\\sigma(X) = \\sqrt{10 \\times 0{,}8 \\times 0{,}2} = \\sqrt{1{,}6} \\approx 1{,}26$.",
            "$1 - 0{,}2^{\\,n} > 0{,}999 \\iff 0{,}2^{\\,n} < 10^{-3} \\iff n > \\dfrac{-3\\ln 10}{\\ln 0{,}2} \\approx 4{,}29$ : $5$ lancers suffisent."]],
        },
        {
          t: "Somme de variables aléatoires",
          c: ["On lance deux dés équilibrés à six faces. On note $X_{1}$ et $X_{2}$ les résultats et $S = X_{1} + X_{2}$.",
            ["q", "Calculer $E(X_{1})$ et $V(X_{1})$.",
              "En déduire $E(S)$ et $V(S)$ en justifiant l'indépendance.",
              "Calculer $P(S = 7)$ et $P(S \\geqslant 10)$.",
              "On lance maintenant $n$ dés. Donner $E$ et $\\sigma$ de la somme."]],
          sol: [["q", "$E(X_{1}) = 3{,}5$ et $V(X_{1}) = \\dfrac{35}{12} \\approx 2{,}92$.",
            "Par linéarité $E(S) = 7$ ; les dés étant indépendants, $V(S) = \\dfrac{35}{6} \\approx 5{,}83$.",
            "$P(S=7) = \\tfrac{6}{36} = \\tfrac{1}{6}$ ; $P(S \\geqslant 10) = \\tfrac{3+2+1}{36} = \\tfrac{1}{6}$.",
            "$E = 3{,}5n$ et $\\sigma = \\sqrt{\\tfrac{35n}{12}}$."]],
        },
        {
          t: "Inégalité de concentration",
          c: ["Soit $X$ une variable aléatoire d'espérance $\\mu = 50$ et d'écart-type $\\sigma = 4$.",
            ["q", "Énoncer l'inégalité de Bienaymé-Tchebychev.",
              "Majorer $P(|X - 50| \\geqslant 10)$.",
              "On répète l'expérience $n$ fois et on note $M_{n}$ la moyenne des résultats. Majorer $P(|M_{n} - 50| \\geqslant 1)$ en fonction de $n$.",
              "Combien de répétitions garantissent $P(|M_{n} - 50| \\geqslant 1) \\leqslant 0{,}05$ ?"]],
          sol: [["q", "$P(|X - \\mu| \\geqslant \\delta) \\leqslant \\dfrac{V(X)}{\\delta^{2}}$ pour tout $\\delta > 0$.",
            "$P \\leqslant \\dfrac{16}{100} = 0{,}16$.",
            "$V(M_{n}) = \\dfrac{16}{n}$ donc $P(|M_{n} - 50| \\geqslant 1) \\leqslant \\dfrac{16}{n}$.",
            "$\\dfrac{16}{n} \\leqslant 0{,}05 \\iff n \\geqslant 320$."]],
        },
      ],
    },
    {
      t: "Fiche 10 — Algorithmique et simulation", st: "Seuils, dichotomie, Monte-Carlo, loi des grands nombres", diff: "★★",
      desc: "Programmer les algorithmes attendus au baccalauréat.",
      ex: [
        {
          t: "Seuil et suite",
          c: ["Soit $u_{0} = 2$ et $u_{n+1} = 0{,}75u_{n} + 1$.",
            ["q", "Déterminer la limite de $(u_{n})$.",
              "Écrire une fonction Python renvoyant le plus petit rang $n$ tel que $|u_{n} - \\ell| < 10^{-6}$.",
              "Justifier que cet algorithme se termine."]],
          sol: [["q", "Point fixe : $\\ell = 4$ ; $u_{n} - 4 = -2 \\times 0{,}75^{\\,n} \\to 0$, la limite est $4$.",
            ["code", "python", "def rang():\n    u = 2\n    n = 0\n    while abs(u - 4) >= 1e-6:\n        u = 0.75 * u + 1\n        n = n + 1\n    return n"],
            "$|u_{n} - 4| = 2 \\times 0{,}75^{\\,n} \\to 0$ : le test finit par être faux (ici $n = 51$)."]],
        },
        {
          t: "Dichotomie",
          c: ["On cherche la solution de $x^{3} + x - 3 = 0$ sur $[1\\,;\\,2]$.",
            ["code", "python", "def dicho(eps):\n    a, b = 1, 2\n    f = lambda x: x**3 + x - 3\n    while b - a > eps:\n        m = (a + b) / 2\n        if f(a) * f(m) <= 0:\n            b = m\n        else:\n            a = m\n    return a, b"],
            ["q", "Expliquer le rôle du test $\\texttt{f(a) * f(m) <= 0}$.",
              "Combien d'itérations sont nécessaires pour $\\varepsilon = 10^{-3}$ ?",
              "Donner l'encadrement obtenu (arrondi à $10^{-3}$)."]],
          sol: [["q", "Il détecte un changement de signe sur $[a\\,;\\,m]$ : la racine s'y trouve, on remplace $b$ par $m$.",
            "L'amplitude est divisée par deux à chaque étape : $2^{-n} < 10^{-3}$ donne $n = 10$ itérations.",
            "$1{,}213 < \\alpha < 1{,}214$."]],
        },
        {
          t: "Méthode de Monte-Carlo",
          c: ["On estime $\\pi$ en tirant des points au hasard dans le carré $[0\\,;\\,1]^{2}$ et en comptant ceux qui tombent dans le quart de disque.",
            ["code", "python", "from random import random\n\ndef estim(N):\n    c = 0\n    for i in range(N):\n        x, y = random(), random()\n        if x * x + y * y <= 1:\n            c = c + 1\n    return 4 * c / N"],
            ["q", "Justifier le facteur $4$ dans la dernière ligne.",
              "Quelle loi suit le nombre $c$ de points dans le quart de disque ?",
              "Donner $E(c)$ et $\\sigma(c)$ en fonction de $N$.",
              "Quel phénomène mathématique garantit la convergence de l'estimation ?"]],
          sol: [["q", "La probabilité de tomber dans le quart de disque vaut $\\tfrac{\\pi}{4}$ : la fréquence estime $\\tfrac{\\pi}{4}$, qu'il faut multiplier par $4$.",
            "$c \\sim \\mathcal{B}\\!\\left(N\\,;\\,\\tfrac{\\pi}{4}\\right)$.",
            "$E(c) = \\tfrac{\\pi N}{4}$ et $\\sigma(c) = \\sqrt{N \\times \\tfrac{\\pi}{4}\\left(1 - \\tfrac{\\pi}{4}\\right)} \\approx 0{,}41\\sqrt{N}$.",
            "La loi des grands nombres : la fréquence converge vers la probabilité."]],
        },
        {
          t: "Loi des grands nombres",
          c: ["On simule $n$ lancers d'une pièce équilibrée et on note $F_{n}$ la fréquence de « pile ».",
            ["q", "Donner $E(F_{n})$ et $V(F_{n})$.",
              "À l'aide de l'inégalité de concentration, majorer $P\\left(\\left|F_{n} - 0{,}5\\right| \\geqslant 0{,}05\\right)$.",
              "Combien de lancers pour que cette probabilité soit inférieure à $0{,}01$ ?",
              "Écrire un programme simulant $n$ lancers et renvoyant $F_{n}$."]],
          sol: [["q", "$E(F_{n}) = 0{,}5$ et $V(F_{n}) = \\dfrac{0{,}25}{n}$.",
            "$P \\leqslant \\dfrac{0{,}25/n}{0{,}0025} = \\dfrac{100}{n}$.",
            "$\\dfrac{100}{n} \\leqslant 0{,}01 \\iff n \\geqslant 10\\,000$.",
            ["code", "python", "from random import randint\n\ndef freq(n):\n    p = 0\n    for i in range(n):\n        p = p + randint(0, 1)\n    return p / n"]]],
        },
      ],
    },
  ]);

  L.addSujets("tle", "ds", [
    {
      t: "Contrôle n° 1 — Suites et récurrence", st: "Récurrence, convergence, suite auxiliaire", h: 1, calc: "autorisée",
      desc: "Trois exercices : récurrence, limite et algorithme de seuil.",
      ex: [
        {
          t: "Récurrence", pts: 6,
          c: [["q", "Démontrer par récurrence que pour tout entier $n \\geqslant 1$ : $\\displaystyle\\sum_{k=1}^{n} k = \\frac{n(n+1)}{2}$.",
            "Démontrer par récurrence que pour tout $n \\geqslant 4$ : $2^{\\,n} \\geqslant n^{2}$."]],
          sol: [["q", "Initialisation : pour $n=1$, $1 = \\tfrac{1 \\times 2}{2}$. Hérédité : $\\tfrac{n(n+1)}{2} + (n+1) = \\tfrac{(n+1)(n+2)}{2}$.",
            "Initialisation : $2^{4} = 16 = 4^{2}$. Hérédité : $2^{\\,n+1} = 2 \\times 2^{\\,n} \\geqslant 2n^{2}$ et $2n^{2} \\geqslant (n+1)^{2} \\iff n^{2} - 2n - 1 \\geqslant 0$, vrai pour $n \\geqslant 4$."]],
        },
        {
          t: "Étude d'une suite", pts: 9,
          c: ["Soit $(u_{n})$ définie par $u_{0} = 12$ et $u_{n+1} = \\dfrac{1}{3}u_{n} + 4$.",
            ["q", "Calculer $u_{1}$ et $u_{2}$.",
              "Démontrer par récurrence que $u_{n} \\geqslant 6$ pour tout $n$.",
              "Étudier le signe de $u_{n+1} - u_{n}$ et en déduire le sens de variation de $(u_{n})$.",
              "En déduire que $(u_{n})$ converge.",
              "On pose $v_{n} = u_{n} - 6$. Montrer que $(v_{n})$ est géométrique, puis exprimer $u_{n}$ en fonction de $n$.",
              "Retrouver la limite de $(u_{n})$."]],
          sol: [["q", "$u_{1} = 4 + 4 = 8$ et $u_{2} = \\tfrac{8}{3} + 4 = \\tfrac{20}{3} \\approx 6{,}67$.",
            "Initialisation : $u_{0} = 12 \\geqslant 6$. Hérédité : si $u_{n} \\geqslant 6$ alors $\\tfrac{1}{3}u_{n} + 4 \\geqslant 2 + 4 = 6$.",
            "$u_{n+1} - u_{n} = 4 - \\tfrac{2}{3}u_{n} = \\tfrac{2}{3}(6 - u_{n}) \\leqslant 0$ : la suite est décroissante.",
            "Décroissante et minorée par $6$ : elle converge.",
            "$v_{n+1} = \\tfrac{1}{3}u_{n} + 4 - 6 = \\tfrac{1}{3}(u_{n}-6) = \\tfrac{1}{3}v_{n}$, avec $v_{0} = 6$ : $u_{n} = 6 + 6\\left(\\tfrac{1}{3}\\right)^{n}$.",
            "$\\left(\\tfrac{1}{3}\\right)^{n} \\to 0$ : la limite est $6$, qui est le point fixe de la relation."]],
        },
        {
          t: "Algorithme", pts: 5,
          c: ["Soit $w_{0} = 1$ et $w_{n+1} = \\dfrac{1}{3}w_{n} + 4$.",
            ["q", "Calculer la limite de $(w_{n})$.",
              "Écrire une fonction Python renvoyant le plus petit rang $n$ tel que $6 - w_{n} < 10^{-4}$.",
              "Justifier la terminaison de la boucle."]],
          sol: [["q", "Même point fixe : $\\ell = 6$ ; $w_{n} = 6 - 5 \\times \\left(\\tfrac{1}{3}\\right)^{n} \\to 6$.",
            ["code", "python", "def rang():\n    w = 1\n    n = 0\n    while 6 - w >= 1e-4:\n        w = w / 3 + 4\n        n = n + 1\n    return n"],
            "$6 - w_{n} = 5\\left(\\tfrac{1}{3}\\right)^{n}$ tend vers $0$ : la condition devient fausse (ici $n = 10$)."]],
        },
      ],
    },
    {
      t: "Contrôle n° 2 — Logarithme népérien", st: "Équations, étude de fonction, croissances comparées", h: 1, calc: "autorisée",
      desc: "Manipulations algébriques, étude complète et application à l'acoustique.",
      ex: [
        {
          t: "Calculs", pts: 6,
          c: [["q", "Résoudre $\\ln(x+2) + \\ln(x-2) = \\ln 5$.",
            "Résoudre $\\mathrm{e}^{2x} - 5\\mathrm{e}^{x} + 4 = 0$.",
            "Simplifier $\\ln(\\mathrm{e}^{3}) + \\ln\\!\\left(\\tfrac{1}{\\mathrm{e}}\\right) - 2\\ln(\\sqrt{\\mathrm{e}})$.",
            "Déterminer le plus petit entier $n$ tel que $0{,}9^{\\,n} < 0{,}01$."]],
          sol: [["q", "Domaine $x > 2$ ; $x^{2} - 4 = 5 \\iff x^{2} = 9 \\iff x = 3$ (on écarte $-3$).",
            "Avec $X = \\mathrm{e}^{x}$ : $X^{2} - 5X + 4 = 0$, $X = 1$ ou $X = 4$, d'où $x = 0$ ou $x = \\ln 4$.",
            "$3 - 1 - 1 = 1$.",
            "$n\\ln 0{,}9 < \\ln 0{,}01 \\iff n > \\dfrac{\\ln 0{,}01}{\\ln 0{,}9} \\approx 43{,}7$ : $n = 44$."]],
        },
        {
          t: "Étude de fonction", pts: 9,
          c: ["Soit $f(x) = \\dfrac{\\ln x}{x}$ sur $]0\\,;\\,+\\infty[$.",
            ["q", "Déterminer les limites de $f$ en $0^{+}$ et en $+\\infty$.",
              "Calculer $f'(x)$ et montrer que $f'(x) = \\dfrac{1 - \\ln x}{x^{2}}$.",
              "Dresser le tableau de variations de $f$.",
              "En déduire le maximum de $f$.",
              "Résoudre $f(x) = 0$.",
              "En déduire le nombre de solutions de $x^{\\,\\mathrm{e}} = \\mathrm{e}^{\\,x}$ pour $x > 0$ (on pourra passer au logarithme)."]],
          sol: [["q", "En $0^{+}$ : $\\ln x \\to -\\infty$ et $\\tfrac{1}{x} \\to +\\infty$, donc $f \\to -\\infty$ ; en $+\\infty$ : $f \\to 0^{+}$ (croissance comparée).",
            "$f'(x) = \\dfrac{\\tfrac{1}{x} \\times x - \\ln x}{x^{2}} = \\dfrac{1 - \\ln x}{x^{2}}$.",
            "$f'(x) > 0 \\iff x < \\mathrm{e}$ : croissante sur $]0\\,;\\,\\mathrm{e}]$, décroissante sur $[\\mathrm{e}\\,;\\,+\\infty[$.",
            "$f(\\mathrm{e}) = \\dfrac{1}{\\mathrm{e}} \\approx 0{,}368$.",
            "$\\ln x = 0 \\iff x = 1$.",
            "$x^{\\mathrm{e}} = \\mathrm{e}^{x} \\iff \\mathrm{e}\\ln x = x \\iff f(x) = \\tfrac{1}{\\mathrm{e}}$ : d'après le tableau, une seule solution, $x = \\mathrm{e}$."]],
        },
        {
          t: "Décibels", pts: 5,
          c: ["Le niveau sonore en décibels vaut $L = 10\\log\\!\\left(\\dfrac{I}{I_{0}}\\right)$ avec $I_{0} = 10^{-12}$ W·m$^{-2}$ et $\\log x = \\dfrac{\\ln x}{\\ln 10}$.",
            ["q", "Calculer $L$ pour $I = 10^{-6}$ W·m$^{-2}$.",
              "De combien augmente $L$ si l'intensité est multipliée par $10$ ? Par $2$ ?",
              "Quelle intensité correspond au seuil de douleur $L = 120$ dB ?"]],
          sol: [["q", "$L = 10\\log(10^{6}) = 60$ dB.",
            "$+10$ dB si $I$ est multipliée par $10$ ; $10\\log 2 \\approx 3$ dB si elle est doublée.",
            "$\\log\\!\\left(\\tfrac{I}{I_{0}}\\right) = 12$ donc $I = 10^{12} \\times 10^{-12} = 1$ W·m$^{-2}$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 3 — Intégration", st: "Primitives, intégrales, aires, valeur moyenne", h: 1, calc: "autorisée",
      desc: "Primitives, intégration par parties et calcul d'aire.",
      ex: [
        {
          t: "Primitives", pts: 6,
          c: ["Déterminer une primitive sur un intervalle adapté :",
            ["q", "$f(x) = 4x^{3} - \\dfrac{2}{x^{2}}$", "$g(x) = \\dfrac{3}{3x+1}$", "$h(x) = x\\,\\mathrm{e}^{x^{2}}$", "$k(x) = \\dfrac{\\ln x}{x}$"]],
          sol: [["q", "$F(x) = x^{4} + \\dfrac{2}{x}$.", "$G(x) = \\ln(3x+1)$ sur $\\left]-\\tfrac{1}{3}\\,;\\,+\\infty\\right[$.",
            "$H(x) = \\tfrac{1}{2}\\mathrm{e}^{x^{2}}$.", "$K(x) = \\tfrac{1}{2}(\\ln x)^{2}$ sur $]0\\,;\\,+\\infty[$."]],
        },
        {
          t: "Calculs d'intégrales", pts: 7,
          c: [["q", "Calculer $\\displaystyle\\int_{1}^{3}\\left(2x - \\frac{1}{x}\\right)\\mathrm{d}x$.",
            "Calculer $\\displaystyle\\int_{0}^{1} x\\,\\mathrm{e}^{-x}\\,\\mathrm{d}x$ par intégration par parties.",
            "Calculer $\\displaystyle\\int_{1}^{\\mathrm{e}} \\ln x\\,\\mathrm{d}x$ (on posera $u = \\ln x$ et $v' = 1$)."]],
          sol: [["q", "$\\big[x^{2} - \\ln x\\big]_{1}^{3} = (9 - \\ln 3) - 1 = 8 - \\ln 3 \\approx 6{,}90$.",
            "$\\big[-x\\mathrm{e}^{-x}\\big]_{0}^{1} + \\displaystyle\\int_{0}^{1}\\mathrm{e}^{-x}\\mathrm{d}x = -\\mathrm{e}^{-1} + \\big[-\\mathrm{e}^{-x}\\big]_{0}^{1} = 1 - 2\\mathrm{e}^{-1} \\approx 0{,}264$.",
            "$\\big[x\\ln x\\big]_{1}^{\\mathrm{e}} - \\displaystyle\\int_{1}^{\\mathrm{e}} 1\\,\\mathrm{d}x = \\mathrm{e} - (\\mathrm{e} - 1) = 1$."]],
        },
        {
          t: "Aire et valeur moyenne", pts: 7,
          c: ["Soit $f(x) = 4 - x^{2}$ sur $[-2\\,;\\,2]$.",
            ["q", "Étudier le signe de $f$ sur cet intervalle.",
              "Calculer l'aire du domaine compris entre la courbe et l'axe des abscisses.",
              "Calculer la valeur moyenne de $f$ sur $[-2\\,;\\,2]$.",
              "Déterminer $a > 0$ tel que $\\displaystyle\\int_{0}^{a} f(x)\\,\\mathrm{d}x = 0$."]],
          sol: [["q", "$f(x) \\geqslant 0$ sur $[-2\\,;\\,2]$, nul en $-2$ et $2$.",
            "$\\displaystyle\\int_{-2}^{2}(4 - x^{2})\\mathrm{d}x = \\Big[4x - \\tfrac{x^{3}}{3}\\Big]_{-2}^{2} = \\tfrac{16}{3} + \\tfrac{16}{3} = \\tfrac{32}{3}$ u.a.",
            "$\\mu = \\tfrac{1}{4} \\times \\tfrac{32}{3} = \\tfrac{8}{3}$.",
            "$4a - \\tfrac{a^{3}}{3} = 0 \\iff a\\left(4 - \\tfrac{a^{2}}{3}\\right) = 0 \\iff a = 2\\sqrt{3}$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 4 — Géométrie dans l'espace", st: "Droites, plans, produit scalaire, distances", h: 1, calc: "autorisée",
      desc: "Un cube, un plan et une distance à calculer.",
      ex: [
        {
          t: "Dans le cube", pts: 8,
          c: ["$ABCDEFGH$ est un cube d'arête $1$, muni du repère orthonormé $\\left(A\\,;\\,\\vec{AB},\\vec{AD},\\vec{AE}\\right)$. On note $I$ le milieu de $[EF]$.",
            ["q", "Donner les coordonnées de $G$, $H$ et $I$.",
              "Calculer $\\vec{AI} \\cdot \\vec{AG}$.",
              "Calculer $AI$ et $AG$, puis une valeur approchée de l'angle $\\widehat{IAG}$.",
              "Déterminer une équation cartésienne du plan $(AIG)$."]],
          sol: [["q", "$G(1\\,;\\,1\\,;\\,1)$, $H(0\\,;\\,1\\,;\\,1)$, $I\\!\\left(\\tfrac{1}{2}\\,;\\,0\\,;\\,1\\right)$.",
            "$\\vec{AI}\\!\\left(\\tfrac{1}{2}\\,;\\,0\\,;\\,1\\right)$ et $\\vec{AG}(1\\,;\\,1\\,;\\,1)$ : $\\tfrac{1}{2} + 0 + 1 = \\tfrac{3}{2}$.",
            "$AI = \\sqrt{\\tfrac{5}{4}}$, $AG = \\sqrt{3}$, $\\cos\\theta = \\dfrac{1{,}5}{\\sqrt{3{,}75}} \\approx 0{,}775$, soit $\\theta \\approx 39{,}2^{\\circ}$.",
            "Un vecteur normal $\\vec{n}(a\\,;\\,b\\,;\\,c)$ vérifie $\\tfrac{a}{2} + c = 0$ et $a+b+c = 0$ : $\\vec{n}(2\\,;\\,-1\\,;\\,-1)$, d'où $2x - y - z = 0$."]],
        },
        {
          t: "Droite et plan", pts: 7,
          c: ["Soit $\\mathcal{P} : x + 2y - z + 1 = 0$ et $d$ passant par $A(2\\,;\\,0\\,;\\,1)$ de vecteur directeur $\\vec{u}(1\\,;\\,1\\,;\\,1)$.",
            ["q", "Donner une représentation paramétrique de $d$.",
              "Montrer que $d$ et $\\mathcal{P}$ sont sécants.",
              "Déterminer les coordonnées du point d'intersection.",
              "Calculer la distance de $A$ au plan $\\mathcal{P}$."]],
          sol: [["q", "$x = 2 + t$, $y = t$, $z = 1 + t$.",
            "$\\vec{u} \\cdot \\vec{n} = 1 + 2 - 1 = 2 \\neq 0$ : la droite n'est pas parallèle au plan, ils sont donc sécants.",
            "$(2+t) + 2t - (1+t) + 1 = 2t + 2 = 0$ donne $t = -1$ : le point d'intersection est $(1\\,;\\,-1\\,;\\,0)$.",
            "$d(A,\\mathcal{P}) = \\dfrac{|2 + 0 - 1 + 1|}{\\sqrt{1+4+1}} = \\dfrac{2}{\\sqrt{6}} \\approx 0{,}82$."]],
        },
        {
          t: "Sphère", pts: 5,
          c: ["Soit $\\mathcal{S} : x^{2} + y^{2} + z^{2} - 6x + 2y - 15 = 0$.",
            ["q", "Déterminer le centre et le rayon de $\\mathcal{S}$.",
              "Le point $O(0\\,;\\,0\\,;\\,0)$ est-il intérieur à la sphère ?",
              "Déterminer l'intersection de $\\mathcal{S}$ avec le plan $y = -1$."]],
          sol: [["q", "$(x-3)^{2} + (y+1)^{2} + z^{2} = 25$ : centre $\\Omega(3\\,;\\,-1\\,;\\,0)$, rayon $5$.",
            "$\\Omega O = \\sqrt{9+1} = \\sqrt{10} < 5$ : oui, $O$ est intérieur.",
            "La distance de $\\Omega$ au plan est nulle : c'est un grand cercle, de centre $\\Omega$ et de rayon $5$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 5 — Probabilités", st: "Conditionnement, binomiale, concentration", h: 1, calc: "autorisée",
      desc: "Un centre d'appels, un contrôle qualité et une inégalité de concentration.",
      ex: [
        {
          t: "Le centre d'appels", pts: 7,
          c: ["Dans un centre d'appels, $60\\,\\%$ des appels concernent une panne, les autres une question de facturation. Un appel « panne » est résolu en moins de $5$ minutes avec une probabilité $0{,}45$ ; un appel « facturation », avec une probabilité $0{,}8$.",
            ["q", "Construire un arbre pondéré.",
              "Calculer la probabilité qu'un appel soit résolu en moins de $5$ minutes.",
              "Un appel a été résolu rapidement : quelle est la probabilité qu'il concernait une panne ?",
              "Sur $20$ appels indépendants, quelle est la probabilité qu'au moins $15$ soient résolus rapidement ?"]],
          sol: [["q", "$P(A) = 0{,}6$ (panne) et $0{,}4$ (facturation), puis $0{,}45$ et $0{,}8$.",
            "$P(R) = 0{,}6 \\times 0{,}45 + 0{,}4 \\times 0{,}8 = 0{,}27 + 0{,}32 = 0{,}59$.",
            "$P_{R}(A) = \\dfrac{0{,}27}{0{,}59} \\approx 0{,}458$.",
            "$X \\sim \\mathcal{B}(20\\,;\\,0{,}59)$ : $P(X \\geqslant 15) = 1 - P(X \\leqslant 14) \\approx 0{,}108$."]],
        },
        {
          t: "Contrôle qualité", pts: 7,
          c: ["Une machine remplit des bouteilles ; $3\\,\\%$ sont mal remplies. On prélève $50$ bouteilles au hasard ; $X$ est le nombre de bouteilles mal remplies.",
            ["q", "Justifier que $X$ suit une loi binomiale.",
              "Calculer $P(X = 0)$ et $P(X \\leqslant 2)$ à $10^{-3}$ près.",
              "Calculer $E(X)$ et $V(X)$.",
              "Le contrôleur rejette le lot si $X \\geqslant 4$. Calculer la probabilité de rejeter un lot conforme."]],
          sol: [["q", "$50$ prélèvements identiques et indépendants, succès de probabilité $0{,}03$ : $X \\sim \\mathcal{B}(50\\,;\\,0{,}03)$.",
            "$P(X=0) = 0{,}97^{50} \\approx 0{,}218$ ; $P(X \\leqslant 2) \\approx 0{,}811$.",
            "$E(X) = 1{,}5$ et $V(X) = 50 \\times 0{,}03 \\times 0{,}97 = 1{,}455$.",
            "$P(X \\geqslant 4) = 1 - P(X \\leqslant 3) \\approx 1 - 0{,}937 = 0{,}063$."]],
        },
        {
          t: "Concentration", pts: 6,
          c: ["Soit $X$ d'espérance $20$ et de variance $9$, et $M_{n}$ la moyenne de $n$ répétitions indépendantes.",
            ["q", "Majorer $P(|X - 20| \\geqslant 6)$.",
              "Donner $E(M_{n})$ et $V(M_{n})$.",
              "Majorer $P(|M_{n} - 20| \\geqslant 0{,}5)$ en fonction de $n$.",
              "Déterminer $n$ pour que cette probabilité soit inférieure à $1\\,\\%$."]],
          sol: [["q", "$P \\leqslant \\dfrac{9}{36} = 0{,}25$.",
            "$E(M_{n}) = 20$ et $V(M_{n}) = \\dfrac{9}{n}$.",
            "$P \\leqslant \\dfrac{9/n}{0{,}25} = \\dfrac{36}{n}$.",
            "$\\dfrac{36}{n} \\leqslant 0{,}01 \\iff n \\geqslant 3\\,600$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 1 — Fonctions et suites", st: "Logarithme, suites, récurrence, algorithme", h: 2, calc: "autorisée",
      desc: "Deux grands exercices d'analyse et un exercice d'algorithmique.",
      ex: [
        {
          t: "Étude d'une fonction", pts: 8,
          c: ["Soit $f(x) = (x - 1)\\,\\mathrm{e}^{x} - 2$ sur $\\mathbb{R}$.",
            ["q", "Déterminer les limites de $f$ en $-\\infty$ et $+\\infty$.",
              "Calculer $f'(x)$ et dresser le tableau de variations.",
              "Montrer que l'équation $f(x) = 0$ admet une unique solution $\\alpha$, et que $\\alpha \\in \\,]1\\,;\\,2[$.",
              "Étudier la convexité de $f$ et préciser le point d'inflexion.",
              "Déterminer l'équation de la tangente au point d'abscisse $0$."]],
          sol: [["q", "En $-\\infty$ : $(x-1)\\mathrm{e}^{x} \\to 0$ (croissance comparée) donc $f \\to -2$ ; en $+\\infty$ : $f \\to +\\infty$.",
            "$f'(x) = \\mathrm{e}^{x} + (x-1)\\mathrm{e}^{x} = x\\,\\mathrm{e}^{x}$ : $f$ décroît sur $]-\\infty\\,;\\,0]$, croît sur $[0\\,;\\,+\\infty[$, minimum $f(0) = -3$.",
            "Sur $]-\\infty\\,;\\,0]$, $f$ décroît de $-2$ à $-3$ : elle reste négative, aucune solution. Sur $[0\\,;\\,+\\infty[$, $f$ est continue, strictement croissante, $f(0) = -3 < 0$ et $f(2) = \\mathrm{e}^{2} - 2 > 0$ : une unique solution $\\alpha$. Comme $f(1) = -2 < 0$, on a $\\alpha \\in \\,]1\\,;\\,2[$ (en fait $\\alpha \\approx 1{,}68$).",
            "$f''(x) = (x+1)\\mathrm{e}^{x}$ : concave sur $]-\\infty\\,;\\,-1]$, convexe ensuite, point d'inflexion en $x = -1$, soit $\\left(-1\\,;\\,-2\\mathrm{e}^{-1} - 2\\right)$.",
            "$f(0) = -3$ et $f'(0) = 0$ : la tangente est horizontale, $y = -3$."]],
        },
        {
          t: "Le réservoir", pts: 7,
          c: ["Un réservoir contient $500$ L d'eau. Chaque jour, $20\\,\\%$ du volume s'évapore ou est prélevé, et on ajoute $60$ L. On note $v_{n}$ le volume après $n$ jours.",
            ["q", "Exprimer $v_{n+1}$ en fonction de $v_{n}$, puis calculer $v_{1}$.",
              "Démontrer par récurrence que $v_{n} \\geqslant 300$ pour tout $n$.",
              "Montrer que $(v_{n})$ est décroissante.",
              "En déduire qu'elle converge et déterminer sa limite.",
              "Exprimer $v_{n}$ en fonction de $n$ à l'aide de la suite $w_{n} = v_{n} - 300$."]],
          sol: [["q", "$v_{n+1} = 0{,}8v_{n} + 60$ et $v_{1} = 400 + 60 = 460$ L.",
            "Initialisation : $500 \\geqslant 300$. Hérédité : si $v_{n} \\geqslant 300$ alors $0{,}8v_{n} + 60 \\geqslant 240 + 60 = 300$.",
            "$v_{n+1} - v_{n} = 60 - 0{,}2v_{n} = 0{,}2(300 - v_{n}) \\leqslant 0$.",
            "Décroissante et minorée par $300$ : elle converge vers $\\ell = 0{,}8\\ell + 60$, soit $\\ell = 300$ L.",
            "$w_{n+1} = 0{,}8w_{n}$ et $w_{0} = 200$ : $v_{n} = 300 + 200 \\times 0{,}8^{\\,n}$."]],
        },
        {
          t: "Algorithmique", pts: 5,
          c: ["On reprend la suite $(v_{n})$ précédente.",
            ["q", "Écrire une fonction Python $\\texttt{volume(n)}$ renvoyant $v_{n}$.",
              "Écrire une fonction renvoyant le premier jour où le volume passe sous $310$ L.",
              "Déterminer ce rang par le calcul, à l'aide du logarithme."]],
          sol: [["code", "python", "def volume(n):\n    v = 500\n    for k in range(n):\n        v = 0.8 * v + 60\n    return v\n\ndef jour():\n    v, n = 500, 0\n    while v >= 310:\n        v = 0.8 * v + 60\n        n = n + 1\n    return n"],
            ["q", "Voir ci-dessus.", "La fonction renvoie $14$.",
              "$200 \\times 0{,}8^{\\,n} < 10 \\iff n > \\dfrac{\\ln 0{,}05}{\\ln 0{,}8} \\approx 13{,}4$ : $n = 14$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 2 — Bac blanc n° 1", st: "Suites, fonctions, espace, probabilités", h: 3, calc: "autorisée",
      desc: "Quatre exercices indépendants dans le format de l'épreuve du baccalauréat.",
      ex: [
        {
          t: "Suites (5 points)", pts: 5, nom: "Exercice",
          c: ["Soit $(u_{n})$ définie par $u_{0} = 0$ et $u_{n+1} = \\dfrac{u_{n} + 3}{u_{n} + 2}$.",
            ["q", "Calculer $u_{1}$, $u_{2}$ et $u_{3}$ (valeurs approchées).",
              "Démontrer par récurrence que $0 \\leqslant u_{n} \\leqslant 2$ pour tout $n$.",
              "On admet que $(u_{n})$ converge. Déterminer sa limite.",
              "Écrire un algorithme donnant le premier rang tel que $|u_{n} - \\ell| < 10^{-3}$."]],
          sol: [["q", "$u_{1} = 1{,}5$, $u_{2} = \\tfrac{4{,}5}{3{,}5} \\approx 1{,}286$, $u_{3} \\approx 1{,}310$.",
            "Initialisation : $u_{0} = 0 \\in [0\\,;\\,2]$. Hérédité : si $0 \\leqslant u_{n} \\leqslant 2$, alors $u_{n+1} = 1 + \\dfrac{1}{u_{n}+2} \\in \\left[1 + \\tfrac{1}{4}\\,;\\,1 + \\tfrac{1}{2}\\right] \\subset [0\\,;\\,2]$.",
            "$\\ell = \\dfrac{\\ell+3}{\\ell+2} \\iff \\ell^{2} + \\ell - 3 = 0 \\iff \\ell = \\dfrac{-1+\\sqrt{13}}{2} \\approx 1{,}303$ (la racine négative est exclue).",
            "Boucle $\\texttt{while abs(u - l) >= 1e-3: u = (u + 3) / (u + 2)}$ en comptant les tours."]],
        },
        {
          t: "Fonction et intégrale (6 points)", pts: 6, nom: "Exercice",
          c: ["Soit $f(x) = \\ln(x) - x + 2$ sur $]0\\,;\\,+\\infty[$.",
            ["q", "Déterminer les limites de $f$ en $0^{+}$ et $+\\infty$.",
              "Calculer $f'(x)$ et dresser le tableau de variations.",
              "Montrer que l'équation $f(x) = 0$ admet exactement deux solutions.",
              "Donner un encadrement d'amplitude $10^{-1}$ de la plus grande.",
              "Calculer $\\displaystyle\\int_{1}^{2} f(x)\\,\\mathrm{d}x$ (on rappelle qu'une primitive de $\\ln$ est $x\\ln x - x$)."]],
          sol: [["q", "En $0^{+}$ : $-\\infty$ ; en $+\\infty$ : $f(x) = x\\left(\\tfrac{\\ln x}{x} - 1\\right) + 2 \\to -\\infty$.",
            "$f'(x) = \\tfrac{1}{x} - 1 = \\tfrac{1-x}{x}$ : croissante sur $]0\\,;\\,1]$, décroissante ensuite, maximum $f(1) = 1 > 0$.",
            "Sur chacun des deux intervalles de monotonie, $f$ est continue, strictement monotone et change de signe : le corollaire du TVI donne exactement une solution sur chacun, soit deux au total.",
            "$f(3) \\approx 0{,}10 > 0$ et $f(3{,}2) \\approx -0{,}04 < 0$ : $3{,}1 < \\alpha < 3{,}2$.",
            "$\\big[x\\ln x - x - \\tfrac{x^{2}}{2} + 2x\\big]_{1}^{2} = (2\\ln 2 - 2 - 2 + 4) - (0 - 1 - \\tfrac{1}{2} + 2) = 2\\ln 2 - \\tfrac{1}{2} \\approx 0{,}886$."]],
        },
        {
          t: "Géométrie dans l'espace (5 points)", pts: 5, nom: "Exercice",
          c: ["On considère $A(1\\,;\\,0\\,;\\,2)$, $B(2\\,;\\,1\\,;\\,0)$, $C(0\\,;\\,3\\,;\\,0)$ et le plan $\\mathcal{P} : x + y + z - 3 = 0$.",
            ["q", "Vérifier que $A$, $B$ et $C$ appartiennent à $\\mathcal{P}$.",
              "Les points $A$, $B$, $C$ définissent-ils bien un plan ?",
              "Déterminer une représentation paramétrique de la droite $d$ passant par $D(2\\,;\\,2\\,;\\,2)$ et orthogonale à $\\mathcal{P}$.",
              "Déterminer les coordonnées du projeté orthogonal $H$ de $D$ sur $\\mathcal{P}$, puis la distance $DH$."]],
          sol: [["q", "$1+0+2-3 = 0$, $2+1+0-3 = 0$ et $0+3+0-3 = 0$ : les trois points appartiennent à $\\mathcal{P}$.",
            "$\\vec{AB}(1\\,;\\,1\\,;\\,-2)$ et $\\vec{AC}(-1\\,;\\,3\\,;\\,-2)$ ne sont pas colinéaires : oui, ils définissent le plan $\\mathcal{P}$.",
            "$\\vec{n}(1\\,;\\,1\\,;\\,1)$ : $x = 2+t$, $y = 2+t$, $z = 2+t$.",
            "$(2+t) \\times 3 - 3 = 0 \\iff t = -1$, donc $H(1\\,;\\,1\\,;\\,1)$ et $DH = \\sqrt{3} \\approx 1{,}73$ ; on retrouve $\\dfrac{|6-3|}{\\sqrt{3}} = \\sqrt{3}$."]],
        },
        {
          t: "Probabilités (4 points)", pts: 4, nom: "Exercice",
          c: ["Un test antidopage détecte un produit chez $98\\,\\%$ des sportifs dopés, et donne un résultat positif chez $1\\,\\%$ des sportifs non dopés. On estime que $5\\,\\%$ des sportifs sont dopés.",
            ["q", "Représenter la situation par un arbre.",
              "Calculer la probabilité qu'un test soit positif.",
              "Un test est positif : quelle est la probabilité que le sportif soit réellement dopé ?",
              "Sur $200$ sportifs contrôlés, quel est le nombre moyen de tests positifs ?"]],
          sol: [["q", "$P(D) = 0{,}05$, $P_{D}(T) = 0{,}98$, $P_{\\bar{D}}(T) = 0{,}01$.",
            "$P(T) = 0{,}05 \\times 0{,}98 + 0{,}95 \\times 0{,}01 = 0{,}049 + 0{,}0095 = 0{,}0585$.",
            "$P_{T}(D) = \\dfrac{0{,}049}{0{,}0585} \\approx 0{,}838$.",
            "$X \\sim \\mathcal{B}(200\\,;\\,0{,}0585)$ : $E(X) = 11{,}7$ tests positifs en moyenne."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 3 — Analyse approfondie", st: "Exponentielle, intégrales, suites d'intégrales", h: 2, calc: "autorisée",
      desc: "Une étude de fonction complète et une suite définie par une intégrale.",
      ex: [
        {
          t: "Étude et aire", pts: 10,
          c: ["Soit $f(x) = (1 - x)\\,\\mathrm{e}^{-x}$ sur $[0\\,;\\,+\\infty[$.",
            ["q", "Calculer $f(0)$ et $\\displaystyle\\lim_{x\\to+\\infty} f(x)$.",
              "Montrer que $f'(x) = (x - 2)\\mathrm{e}^{-x}$ et dresser le tableau de variations.",
              "Déterminer le signe de $f$ sur $[0\\,;\\,+\\infty[$.",
              "Vérifier que $F(x) = x\\,\\mathrm{e}^{-x}$ est une primitive de $f$.",
              "Calculer l'aire, en unités d'aire, du domaine compris entre la courbe et l'axe des abscisses sur $[0\\,;\\,1]$."]],
          sol: [["q", "$f(0) = 1$ et $f(x) \\to 0$ en $+\\infty$ (croissance comparée).",
            "$f'(x) = -\\mathrm{e}^{-x} - (1-x)\\mathrm{e}^{-x} = (x-2)\\mathrm{e}^{-x}$ : décroissante sur $[0\\,;\\,2]$, croissante ensuite, minimum $f(2) = -\\mathrm{e}^{-2}$.",
            "$\\mathrm{e}^{-x} > 0$ : $f(x) \\geqslant 0 \\iff x \\leqslant 1$.",
            "$F'(x) = \\mathrm{e}^{-x} - x\\mathrm{e}^{-x} = (1-x)\\mathrm{e}^{-x} = f(x)$.",
            "$\\displaystyle\\int_{0}^{1} f = F(1) - F(0) = \\mathrm{e}^{-1} \\approx 0{,}368$ u.a."]],
        },
        {
          t: "Une suite d'intégrales", pts: 10,
          c: ["Pour $n \\geqslant 0$, on pose $I_{n} = \\displaystyle\\int_{0}^{1} x^{\\,n}\\,\\mathrm{e}^{-x}\\,\\mathrm{d}x$.",
            ["q", "Calculer $I_{0}$.",
              "Justifier que $I_{n} \\geqslant 0$ pour tout $n$.",
              "Montrer que pour tout $x \\in [0\\,;\\,1]$, $x^{\\,n+1}\\mathrm{e}^{-x} \\leqslant x^{\\,n}\\mathrm{e}^{-x}$, et en déduire que $(I_{n})$ est décroissante.",
              "Montrer que $I_{n} \\leqslant \\dfrac{1}{n+1}$ et en déduire $\\displaystyle\\lim_{n\\to+\\infty} I_{n}$.",
              "À l'aide d'une intégration par parties, montrer que $I_{n+1} = -\\mathrm{e}^{-1} + (n+1)I_{n}$."]],
          sol: [["q", "$I_{0} = \\big[-\\mathrm{e}^{-x}\\big]_{0}^{1} = 1 - \\mathrm{e}^{-1} \\approx 0{,}632$.",
            "L'intégrande est positive sur $[0\\,;\\,1]$ et les bornes sont dans l'ordre croissant.",
            "Sur $[0\\,;\\,1]$, $x^{\\,n+1} \\leqslant x^{\\,n}$ ; en intégrant l'inégalité, $I_{n+1} \\leqslant I_{n}$.",
            "$\\mathrm{e}^{-x} \\leqslant 1$ donne $I_{n} \\leqslant \\displaystyle\\int_{0}^{1}x^{n}\\mathrm{d}x = \\dfrac{1}{n+1}$ ; par encadrement, $I_{n} \\to 0$.",
            "Avec $u = x^{\\,n+1}$ et $v' = \\mathrm{e}^{-x}$ : $I_{n+1} = \\big[-x^{n+1}\\mathrm{e}^{-x}\\big]_{0}^{1} + (n+1)\\displaystyle\\int_{0}^{1}x^{n}\\mathrm{e}^{-x}\\mathrm{d}x = -\\mathrm{e}^{-1} + (n+1)I_{n}$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 4 — Espace et probabilités", st: "Droites, plans, distances, lois de probabilité", h: 2, calc: "autorisée",
      desc: "Une pyramide en coordonnées et deux exercices de probabilités.",
      ex: [
        {
          t: "La pyramide", pts: 9,
          c: ["Dans un repère orthonormé, $A(0\\,;\\,0\\,;\\,0)$, $B(4\\,;\\,0\\,;\\,0)$, $C(4\\,;\\,4\\,;\\,0)$, $D(0\\,;\\,4\\,;\\,0)$ et $S(2\\,;\\,2\\,;\\,6)$.",
            ["q", "Justifier que $ABCD$ est un carré.",
              "Calculer $\\vec{SA} \\cdot \\vec{SC}$.",
              "Déterminer une équation cartésienne du plan $(SAB)$.",
              "Calculer la distance de $D$ au plan $(SAB)$.",
              "Calculer le volume de la pyramide $SABCD$."]],
          sol: [["q", "$\\vec{AB}(4\\,;\\,0\\,;\\,0)$ et $\\vec{DC}(4\\,;\\,0\\,;\\,0)$ : parallélogramme ; $\\vec{AB} \\cdot \\vec{AD} = 0$ et $AB = AD = 4$ : c'est un carré.",
            "$\\vec{SA}(-2\\,;\\,-2\\,;\\,-6)$ et $\\vec{SC}(2\\,;\\,2\\,;\\,-6)$ : $-4 - 4 + 36 = 28$.",
            "Le plan contient $A$, $\\vec{AB}(4\\,;\\,0\\,;\\,0)$ et $\\vec{AS}(2\\,;\\,2\\,;\\,6)$ ; un vecteur normal est $\\vec{n}(0\\,;\\,3\\,;\\,-1)$ : $3y - z = 0$.",
            "$d(D,(SAB)) = \\dfrac{|12 - 0|}{\\sqrt{10}} = \\dfrac{12}{\\sqrt{10}} \\approx 3{,}79$.",
            "$V = \\tfrac{1}{3} \\times 16 \\times 6 = 32$ unités de volume."]],
        },
        {
          t: "Le questionnaire", pts: 6,
          c: ["Un QCM comporte $12$ questions à $3$ réponses, dont une seule exacte. Un candidat répond au hasard ; $X$ est son nombre de bonnes réponses.",
            ["q", "Donner la loi de $X$, son espérance et son écart-type.",
              "Calculer $P(X = 4)$ à $10^{-3}$ près.",
              "Calculer $P(X \\geqslant 6)$.",
              "Le seuil d'admission est fixé à $8$ bonnes réponses. Commenter la probabilité d'être admis au hasard."]],
          sol: [["q", "$X \\sim \\mathcal{B}\\!\\left(12\\,;\\,\\tfrac{1}{3}\\right)$, $E(X) = 4$, $\\sigma(X) = \\sqrt{12 \\times \\tfrac{1}{3} \\times \\tfrac{2}{3}} = \\sqrt{\\tfrac{8}{3}} \\approx 1{,}63$.",
            "$P(X=4) = \\binom{12}{4}\\left(\\tfrac{1}{3}\\right)^{4}\\left(\\tfrac{2}{3}\\right)^{8} \\approx 0{,}238$.",
            "$P(X \\geqslant 6) = 1 - P(X \\leqslant 5) \\approx 1 - 0{,}822 = 0{,}178$.",
            "$P(X \\geqslant 8) \\approx 0{,}019$ : moins de $2\\,\\%$ — répondre au hasard ne paie pas."]],
        },
        {
          t: "Files d'attente", pts: 5,
          c: ["Le temps d'attente $T$, en minutes, à un guichet a pour espérance $6$ et pour écart-type $3$.",
            ["q", "Majorer $P(|T - 6| \\geqslant 9)$ grâce à l'inégalité de Bienaymé-Tchebychev.",
              "On observe $n$ clients indépendants ; $M_{n}$ est le temps moyen. Donner $E(M_{n})$ et $V(M_{n})$.",
              "Déterminer $n$ pour que $P(|M_{n} - 6| \\geqslant 0{,}5) \\leqslant 0{,}02$."]],
          sol: [["q", "$P \\leqslant \\dfrac{9}{81} = \\dfrac{1}{9} \\approx 0{,}111$.",
            "$E(M_{n}) = 6$ et $V(M_{n}) = \\dfrac{9}{n}$.",
            "$\\dfrac{9/n}{0{,}25} \\leqslant 0{,}02 \\iff n \\geqslant 1\\,800$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 5 — Bac blanc n° 2", st: "QCM, analyse, espace, probabilités, algorithmique", h: 3, calc: "autorisée",
      desc: "Sujet complet de fin d'année, format baccalauréat, avec QCM initial.",
      ex: [
        {
          t: "QCM (4 points)", pts: 4, nom: "Exercice",
          c: ["Une seule réponse est exacte ; aucune justification n'est demandée.",
            ["q", "$\\displaystyle\\lim_{x\\to+\\infty} \\frac{\\ln x}{x^{2}}$ vaut : a) $+\\infty$ ; b) $0$ ; c) $1$.",
              "Une primitive de $x \\mapsto \\dfrac{1}{2x+1}$ sur $\\left]-\\tfrac{1}{2}\\,;\\,+\\infty\\right[$ est : a) $\\ln(2x+1)$ ; b) $\\tfrac{1}{2}\\ln(2x+1)$ ; c) $\\dfrac{-2}{(2x+1)^{2}}$.",
              "Si $X \\sim \\mathcal{B}(n\\,;\\,p)$ alors $V(X)$ vaut : a) $np$ ; b) $np(1-p)$ ; c) $\\sqrt{np(1-p)}$.",
              "Les plans $x+y-z = 0$ et $2x+2y-2z+5 = 0$ sont : a) sécants ; b) confondus ; c) strictement parallèles."]],
          sol: [["q", "b) $0$ (croissance comparée).", "b) $\\tfrac{1}{2}\\ln(2x+1)$.", "b) $np(1-p)$.",
            "c) strictement parallèles (vecteurs normaux colinéaires, équations non proportionnelles)."]],
        },
        {
          t: "Le médicament (5 points)", pts: 5, nom: "Exercice",
          c: ["La concentration d'un médicament dans le sang, en mg·L$^{-1}$, $t$ heures après l'injection, est $c(t) = 5t\\,\\mathrm{e}^{-0{,}5t}$ pour $t \\geqslant 0$.",
            ["q", "Calculer $c(0)$ et $\\displaystyle\\lim_{t\\to+\\infty} c(t)$.",
              "Montrer que $c'(t) = 5(1 - 0{,}5t)\\mathrm{e}^{-0{,}5t}$.",
              "Déterminer l'instant où la concentration est maximale, et cette concentration.",
              "Le médicament est efficace tant que $c(t) \\geqslant 2$. Déterminer, par balayage, la durée d'efficacité (au dixième d'heure).",
              "Étudier la convexité de $c$ sur $[0\\,;\\,+\\infty[$."]],
          sol: [["q", "$c(0) = 0$ et $c(t) \\to 0$ (croissance comparée).",
            "$c'(t) = 5\\mathrm{e}^{-0{,}5t} + 5t \\times (-0{,}5)\\mathrm{e}^{-0{,}5t} = 5(1 - 0{,}5t)\\mathrm{e}^{-0{,}5t}$.",
            "$c'$ s'annule en $t = 2$ : maximum $c(2) = 10\\mathrm{e}^{-1} \\approx 3{,}68$ mg·L$^{-1}$.",
            "$c(t) = 2$ pour $t \\approx 0{,}5$ h et $t \\approx 6{,}0$ h : l'efficacité dure environ $5{,}5$ heures.",
            "$c''(t) = 5(-0{,}5 - 0{,}5(1-0{,}5t))\\mathrm{e}^{-0{,}5t} = 1{,}25(t - 4)\\mathrm{e}^{-0{,}5t}$ : concave sur $[0\\,;\\,4]$, convexe ensuite, inflexion en $t = 4$."]],
        },
        {
          t: "Dans l'espace (5 points)", pts: 5, nom: "Exercice",
          c: ["On donne $A(1\\,;\\,2\\,;\\,3)$, $\\vec{u}(1\\,;\\,1\\,;\\,1)$ et le plan $\\mathcal{P} : 2x + y - z + 1 = 0$.",
            ["q", "Donner une représentation paramétrique de la droite $d$ passant par $A$ de vecteur directeur $\\vec{u}$.",
              "Montrer que $d$ et $\\mathcal{P}$ sont sécants, et déterminer leur point d'intersection.",
              "Calculer la distance de $A$ à $\\mathcal{P}$.",
              "Déterminer une équation du plan passant par $A$ et parallèle à $\\mathcal{P}$."]],
          sol: [["q", "$x = 1+t$, $y = 2+t$, $z = 3+t$.",
            "$\\vec{u} \\cdot \\vec{n} = 2 + 1 - 1 = 2 \\neq 0$ : ils sont sécants. En reportant : $2(1+t)+(2+t)-(3+t)+1 = 2t+2 = 0$, soit $t = -1$ et le point $(0\\,;\\,1\\,;\\,2)$.",
            "$d(A,\\mathcal{P}) = \\dfrac{|2|}{\\sqrt{6}} = \\dfrac{2}{\\sqrt{6}} \\approx 0{,}82$.",
            "$2x + y - z + c = 0$ avec $A$ : $2 + 2 - 3 + c = 0$, donc $2x + y - z - 1 = 0$."]],
        },
        {
          t: "Le jeu en ligne (6 points)", pts: 6, nom: "Exercice",
          c: ["Un joueur gagne une partie avec une probabilité $0{,}35$, indépendamment des autres parties. Il joue $15$ parties ; $X$ est le nombre de parties gagnées.",
            ["q", "Donner la loi de $X$, son espérance et sa variance.",
              "Calculer $P(X = 5)$ et $P(X \\leqslant 3)$ à $10^{-3}$ près.",
              "Calculer la probabilité qu'il gagne au moins la moitié des parties.",
              "Combien de parties doit-il jouer pour que la probabilité d'en gagner au moins une dépasse $0{,}99$ ?",
              "Majorer, avec l'inégalité de concentration, la probabilité que la fréquence de victoires sur $n$ parties s'écarte de $0{,}35$ de plus de $0{,}05$."]],
          sol: [["q", "$X \\sim \\mathcal{B}(15\\,;\\,0{,}35)$, $E(X) = 5{,}25$, $V(X) = 15 \\times 0{,}35 \\times 0{,}65 = 3{,}4125$.",
            "$P(X=5) \\approx 0{,}212$ et $P(X \\leqslant 3) \\approx 0{,}173$.",
            "$P(X \\geqslant 8) = 1 - P(X \\leqslant 7) \\approx 1 - 0{,}887 = 0{,}113$.",
            "$1 - 0{,}65^{\\,n} > 0{,}99 \\iff n > \\dfrac{\\ln 0{,}01}{\\ln 0{,}65} \\approx 10{,}7$ : $11$ parties.",
            "$V(F_{n}) = \\dfrac{0{,}35 \\times 0{,}65}{n} = \\dfrac{0{,}2275}{n}$ donc $P \\leqslant \\dfrac{0{,}2275}{n \\times 0{,}0025} = \\dfrac{91}{n}$."]],
        },
      ],
    },
  ]);
})();
