/* Banque — Première spécialité mathématiques */
(function () {

  L.addSujets("1re", "fiche", [
    {
      t: "Fiche 1 — Le second degré dans tous ses états", st: "Forme canonique, discriminant, signe, optimisation", diff: "★",
      desc: "Quatre exercices pour maîtriser paraboles, racines et tableaux de signes.",
      intro: "Objectif : passer d'une forme à l'autre (développée, canonique, factorisée) et lire un trinôme comme on lit une carte.",
      ex: [
        {
          t: "Trois visages d'une parabole",
          c: ["On considère $f(x) = x^{2} - 6x + 5$ définie sur $\\mathbb{R}$.",
            ["q", "Déterminer la forme canonique de $f$.", "En déduire les coordonnées du sommet de la parabole.",
              "Résoudre $f(x) = 0$, puis donner la forme factorisée de $f$.",
              "Dresser le tableau de signes de $f(x)$ sur $\\mathbb{R}$.",
              "Résoudre l'inéquation $f(x) \\leqslant -3$."]],
          sol: [["q", "$f(x) = (x-3)^{2} - 4$ car $(x-3)^{2} = x^{2}-6x+9$.",
            "Le sommet est $S(3\\,;\\,-4)$, minimum de $f$.",
            "$\\Delta = 36 - 20 = 16$, donc $x_{1} = 1$ et $x_{2} = 5$ : $f(x) = (x-1)(x-5)$.",
            "$f(x) > 0$ sur $]-\\infty\\,;\\,1[\\,\\cup\\,]5\\,;\\,+\\infty[$ et $f(x) < 0$ sur $]1\\,;\\,5[$.",
            "$f(x) \\leqslant -3 \\iff (x-3)^{2} \\leqslant 1 \\iff 2 \\leqslant x \\leqslant 4$, soit $S = [2\\,;\\,4]$."]],
        },
        {
          t: "Le potager du lycée",
          c: ["Le club jardinage dispose de $40$ m de grillage pour clôturer un potager rectangulaire. On note $x$ la largeur, en mètres.",
            ["q", "Exprimer la longueur du potager en fonction de $x$, puis son aire $A(x)$.",
              "Préciser l'intervalle auquel appartient $x$.",
              "Montrer que $A(x) = -(x-10)^{2} + 100$.",
              "En déduire les dimensions du potager d'aire maximale, et cette aire."]],
          sol: [["q", "La longueur vaut $20 - x$ et $A(x) = x(20-x) = -x^{2} + 20x$.",
            "$x$ doit être strictement positif et inférieur à $20$ : $x \\in \\,]0\\,;\\,20[$.",
            "$-(x-10)^{2} + 100 = -(x^{2} - 20x + 100) + 100 = -x^{2} + 20x = A(x)$.",
            "Le maximum est atteint pour $x = 10$ : le potager est un carré de côté $10$ m, d'aire $100$ m$^{2}$."]],
        },
        {
          t: "Inéquations en cascade",
          c: [["q", "Résoudre $-2x^{2} + 5x - 2 \\geqslant 0$.",
            "Résoudre $x^{2} + x + 1 > 0$.",
            "Résoudre $\\dfrac{x^{2}-4}{x-3} \\leqslant 0$ (on précisera le domaine)."]],
          sol: [["q", "$\\Delta = 25 - 16 = 9$, racines $x = \\dfrac{-5 \\pm 3}{-4}$, soit $\\tfrac{1}{2}$ et $2$. Le trinôme est positif entre les racines : $S = \\left[\\tfrac{1}{2}\\,;\\,2\\right]$.",
            "$\\Delta = 1 - 4 = -3 < 0$ et $a = 1 > 0$ : le trinôme est toujours strictement positif, $S = \\mathbb{R}$.",
            "Domaine : $x \\neq 3$. Tableau de signes du quotient avec les valeurs $-2$, $2$, $3$ : $S = \\,]-\\infty\\,;\\,-2] \\cup [2\\,;\\,3[$."]],
        },
        {
          t: "Le camion à pizzas",
          c: ["Un camion à pizzas vend $x$ pizzas par soirée. Son bénéfice, en euros, est modélisé par",
            ["$", "B(x) = -x^{2} + 70x - 600, \\qquad 0 \\leqslant x \\leqslant 70."],
            ["q", "Calculer $B(0)$ et interpréter ce résultat.",
              "Déterminer le nombre de pizzas à partir duquel l'activité devient rentable.",
              "Combien de pizzas faut-il vendre pour que le bénéfice soit maximal ? Quel est alors ce bénéfice ?"]],
          sol: [["q", "$B(0) = -600$ : sans aucune vente, le camion perd $600$ € (charges fixes).",
            "$\\Delta = 4900 - 2400 = 2500$, $\\sqrt{\\Delta} = 50$, racines $x = \\dfrac{70 \\pm 50}{2}$, soit $10$ et $60$. Le bénéfice est positif pour $10 \\leqslant x \\leqslant 60$.",
            "Le maximum est atteint au sommet, en $x = 35$, et $B(35) = -1225 + 2450 - 600 = 625$ €."]],
        },
      ],
    },
    {
      t: "Fiche 2 — Suites : du tableur au raisonnement", st: "Suites arithmétiques, géométriques, suites auxiliaires", diff: "★★",
      desc: "Modéliser une situation, reconnaître une suite auxiliaire, calculer une somme.",
      ex: [
        {
          t: "La plateforme de streaming",
          c: ["Une plateforme compte $2\\,000$ abonnés en janvier. Chaque mois, elle conserve $95\\,\\%$ de ses abonnés et en gagne $300$ nouveaux. On note $u_{n}$ le nombre d'abonnés au bout de $n$ mois, $u_{0} = 2000$.",
            ["q", "Justifier que $u_{n+1} = 0{,}95\\,u_{n} + 300$, puis calculer $u_{1}$ et $u_{2}$.",
              "On pose $v_{n} = u_{n} - 6000$. Montrer que $(v_{n})$ est géométrique de raison $0{,}95$.",
              "En déduire $u_{n}$ en fonction de $n$.",
              "Vers quelle valeur le nombre d'abonnés se stabilise-t-il ?"]],
          sol: [["q", "On garde $95\\,\\%$ des abonnés et on en ajoute $300$ : $u_{1} = 1900 + 300 = 2200$ et $u_{2} = 2090 + 300 = 2390$.",
            "$v_{n+1} = u_{n+1} - 6000 = 0{,}95u_{n} - 5700 = 0{,}95(u_{n} - 6000) = 0{,}95\\,v_{n}$.",
            "$v_{0} = -4000$ donc $v_{n} = -4000 \\times 0{,}95^{\\,n}$ et $u_{n} = 6000 - 4000 \\times 0{,}95^{\\,n}$.",
            "$0{,}95^{\\,n}$ tend vers $0$ : le nombre d'abonnés se rapproche de $6\\,000$ en croissant."]],
        },
        {
          t: "L'escalier de pierres",
          c: ["Pour construire un escalier, un maçon pose $3$ pierres sur la première marche, $7$ sur la deuxième, $11$ sur la troisième, et ainsi de suite.",
            ["q", "Quelle est la nature de la suite $(p_{n})$ du nombre de pierres de la marche $n$ ? Donner $p_{1}$ et la raison.",
              "Exprimer $p_{n}$ en fonction de $n$.",
              "Combien de pierres sur la $15^{\\text{e}}$ marche ?",
              "Combien de pierres au total pour un escalier de $15$ marches ?"]],
          sol: [["q", "Suite arithmétique de premier terme $p_{1} = 3$ et de raison $r = 4$.",
            "$p_{n} = 3 + 4(n-1) = 4n - 1$.",
            "$p_{15} = 59$ pierres.",
            "$S = \\dfrac{15 \\times (p_{1} + p_{15})}{2} = \\dfrac{15 \\times 62}{2} = 465$ pierres."]],
        },
        {
          t: "Placement et seuil",
          c: ["Un capital de $1\\,500$ € est placé au taux annuel de $3\\,\\%$ à intérêts composés. On note $c_{n}$ le capital après $n$ années.",
            ["q", "Exprimer $c_{n}$ en fonction de $n$.",
              "Calculer le capital au bout de $5$ ans, arrondi au centime.",
              "À l'aide de la calculatrice, déterminer la première année où le capital dépasse $2\\,000$ €."]],
          sol: [["q", "$c_{n} = 1500 \\times 1{,}03^{\\,n}$.",
            "$c_{5} = 1500 \\times 1{,}03^{5} \\approx 1738{,}91$ €.",
            "$c_{9} \\approx 1957$ € et $c_{10} \\approx 2016$ € : c'est au bout de $10$ ans."]],
        },
        {
          t: "Algorithme de seuil",
          c: ["On reprend la suite $c_{n} = 1500 \\times 1{,}03^{\\,n}$. Voici un programme Python incomplet :",
            ["code", "python", "def seuil(S):\n    c = 1500\n    n = 0\n    while ... :\n        c = ...\n        n = n + 1\n    return n"],
            ["q", "Compléter les deux lignes manquantes pour que la fonction renvoie le nombre d'années nécessaires pour dépasser le seuil $S$.",
              "Que renvoie $\\texttt{seuil(2000)}$ ?",
              "Modifier le programme pour qu'il renvoie aussi le capital obtenu."]],
          sol: [["q", "$\\texttt{while c <= S:}$ puis $\\texttt{c = c * 1.03}$.",
            "Le programme renvoie $10$.",
            "Il suffit d'écrire $\\texttt{return n, c}$ à la dernière ligne."]],
        },
      ],
    },
    {
      t: "Fiche 3 — Dérivation : tangentes et variations", st: "Nombre dérivé, formules, tableau de variations", diff: "★★",
      desc: "Du taux d'accroissement à l'optimisation d'une boîte en carton.",
      ex: [
        {
          t: "Lire une tangente",
          c: ["Soit $f(x) = x^{3} - 3x + 1$.",
            ["q", "Calculer $f'(x)$.",
              "Déterminer l'équation réduite de la tangente à la courbe au point d'abscisse $2$.",
              "En quels points la tangente est-elle horizontale ?",
              "Dresser le tableau de variations de $f$ sur $\\mathbb{R}$."]],
          sol: [["q", "$f'(x) = 3x^{2} - 3$.",
            "$f(2) = 3$ et $f'(2) = 9$ donc $y = 9(x-2) + 3 = 9x - 15$.",
            "$f'(x) = 0 \\iff x = -1$ ou $x = 1$ : aux points $(-1\\,;\\,3)$ et $(1\\,;\\,-1)$.",
            "$f$ est croissante sur $]-\\infty\\,;\\,-1]$, décroissante sur $[-1\\,;\\,1]$, croissante sur $[1\\,;\\,+\\infty[$ ; maximum local $3$, minimum local $-1$."]],
        },
        {
          t: "Produits et quotients",
          c: ["Calculer la dérivée des fonctions suivantes sur un intervalle où elles sont dérivables :",
            ["q", "$f(x) = (3x - 1)(x^{2} + 2)$", "$g(x) = \\dfrac{2x+1}{x^{2}+1}$", "$h(x) = \\dfrac{x}{x-2}$", "$k(x) = (2x - 5)^{2}$"]],
          sol: [["q", "$f'(x) = 3(x^{2}+2) + (3x-1)(2x) = 9x^{2} - 2x + 6$.",
            "$g'(x) = \\dfrac{2(x^{2}+1) - (2x+1)(2x)}{(x^{2}+1)^{2}} = \\dfrac{-2x^{2} - 2x + 2}{(x^{2}+1)^{2}}$.",
            "$h'(x) = \\dfrac{(x-2) - x}{(x-2)^{2}} = \\dfrac{-2}{(x-2)^{2}}$ : $h$ est décroissante sur chaque intervalle.",
            "$k'(x) = 2 \\times 2 \\times (2x-5) = 4(2x-5) = 8x - 20$."]],
        },
        {
          t: "La boîte en carton",
          c: ["On découpe quatre carrés de côté $x$ aux coins d'un carton carré de $20$ cm de côté, puis on relève les bords pour former une boîte sans couvercle.",
            ["q", "Justifier que le volume vaut $V(x) = x(20 - 2x)^{2}$ pour $x \\in \\,]0\\,;\\,10[$.",
              "Montrer que $V'(x) = (20 - 2x)(20 - 6x)$.",
              "En déduire la valeur de $x$ qui rend le volume maximal, puis ce volume."]],
          sol: [["q", "La base est un carré de côté $20 - 2x$ et la hauteur vaut $x$.",
            "$V'(x) = (20-2x)^{2} + x \\times 2(20-2x) \\times (-2) = (20-2x)\\big[(20-2x) - 4x\\big] = (20-2x)(20-6x)$.",
            "Sur $]0\\,;\\,10[$, $20 - 2x > 0$ : $V'$ s'annule en $x = \\tfrac{10}{3}$ en changeant de signe. Le volume maximal vaut $V\\!\\left(\\tfrac{10}{3}\\right) = \\tfrac{10}{3} \\times \\left(\\tfrac{40}{3}\\right)^{2} = \\tfrac{16000}{27} \\approx 592{,}6$ cm$^{3}$."]],
        },
        {
          t: "Vitesse d'un drone",
          c: ["Un drone monte verticalement ; son altitude, en mètres, à l'instant $t$ (en secondes) est $z(t) = -0{,}2t^{3} + 3t^{2}$ pour $t \\in [0\\,;\\,10]$.",
            ["q", "La vitesse verticale est $v(t) = z'(t)$. Calculer $v(t)$.",
              "À quel instant la vitesse est-elle maximale ? Que vaut-elle ?",
              "À quel instant le drone commence-t-il à redescendre ?"]],
          sol: [["q", "$v(t) = -0{,}6t^{2} + 6t$.",
            "$v$ est un trinôme de sommet $t = 5$ : la vitesse maximale vaut $v(5) = -15 + 30 = 15$ m·s$^{-1}$.",
            "$v(t) = 0 \\iff t(6 - 0{,}6t) = 0 \\iff t = 10$ : le drone amorce sa descente à $t = 10$ s."]],
        },
      ],
    },
    {
      t: "Fiche 4 — La fonction exponentielle", st: "Propriétés algébriques, équations, dérivées, modèles", diff: "★★",
      desc: "Manipuler $\\mathrm{e}^{x}$ sans logarithme, et l'utiliser pour modéliser un refroidissement.",
      ex: [
        {
          t: "Gymnastique algébrique",
          c: ["Simplifier au maximum, pour $x$ réel :",
            ["q", "$A = \\mathrm{e}^{3x} \\times \\mathrm{e}^{-x}$", "$B = \\dfrac{\\mathrm{e}^{2x+1}}{\\mathrm{e}^{x-1}}$",
              "$C = \\left(\\mathrm{e}^{-x}\\right)^{3} \\times \\mathrm{e}^{4x}$", "$D = \\dfrac{\\mathrm{e}^{x} + \\mathrm{e}^{2x}}{\\mathrm{e}^{x}}$"]],
          sol: [["q", "$A = \\mathrm{e}^{2x}$.", "$B = \\mathrm{e}^{(2x+1)-(x-1)} = \\mathrm{e}^{x+2}$.",
            "$C = \\mathrm{e}^{-3x} \\times \\mathrm{e}^{4x} = \\mathrm{e}^{x}$.", "$D = 1 + \\mathrm{e}^{x}$."]],
        },
        {
          t: "Équations et inéquations",
          c: ["Résoudre dans $\\mathbb{R}$ :",
            ["q", "$\\mathrm{e}^{2x+1} = \\mathrm{e}^{x-3}$", "$\\mathrm{e}^{2x} - \\mathrm{e}^{x} = 0$",
              "$\\mathrm{e}^{x^{2}} = \\mathrm{e}^{3x-2}$", "$\\mathrm{e}^{3x} \\geqslant \\mathrm{e}^{x+4}$"]],
          sol: [["q", "$2x + 1 = x - 3 \\iff x = -4$.",
            "$\\mathrm{e}^{x}(\\mathrm{e}^{x} - 1) = 0$ ; comme $\\mathrm{e}^{x} > 0$, il reste $\\mathrm{e}^{x} = 1$, soit $x = 0$.",
            "$x^{2} = 3x - 2 \\iff x^{2} - 3x + 2 = 0 \\iff x = 1$ ou $x = 2$.",
            "La fonction exponentielle est croissante : $3x \\geqslant x + 4 \\iff x \\geqslant 2$."]],
        },
        {
          t: "Étude d'une fonction",
          c: ["Soit $f(x) = (x - 2)\\,\\mathrm{e}^{x}$ sur $\\mathbb{R}$.",
            ["q", "Calculer $f'(x)$ et montrer que $f'(x) = (x-1)\\,\\mathrm{e}^{x}$.",
              "Dresser le tableau de variations de $f$.",
              "Déterminer l'équation de la tangente à la courbe au point d'abscisse $0$.",
              "Résoudre $f(x) = 0$."]],
          sol: [["q", "$f'(x) = \\mathrm{e}^{x} + (x-2)\\mathrm{e}^{x} = (x-1)\\mathrm{e}^{x}$.",
            "$\\mathrm{e}^{x} > 0$ : $f$ décroît sur $]-\\infty\\,;\\,1]$ puis croît sur $[1\\,;\\,+\\infty[$, avec un minimum $f(1) = -\\mathrm{e}$.",
            "$f(0) = -2$ et $f'(0) = -1$ : $y = -x - 2$.",
            "$\\mathrm{e}^{x} \\neq 0$ donc $f(x) = 0 \\iff x = 2$."]],
        },
        {
          t: "Le café qui refroidit",
          c: ["La température d'un café, en degrés Celsius, $t$ minutes après le service, est",
            ["$", "T(t) = 20 + 60\\,\\mathrm{e}^{-0{,}1t}."],
            ["q", "Quelle est la température au moment du service ?",
              "Calculer $T(10)$, arrondi au dixième. Interpréter.",
              "Calculer $T'(t)$ et en déduire le sens de variation de $T$.",
              "Vers quelle température le café tend-il ? Justifier."]],
          sol: [["q", "$T(0) = 20 + 60 = 80$ °C.",
            "$T(10) = 20 + 60\\,\\mathrm{e}^{-1} \\approx 42{,}1$ °C : le café a perdu près de $38$ °C en dix minutes.",
            "$T'(t) = -6\\,\\mathrm{e}^{-0{,}1t} < 0$ : la température est strictement décroissante.",
            "$\\mathrm{e}^{-0{,}1t}$ tend vers $0$ : la température tend vers $20$ °C, la température de la pièce."]],
        },
      ],
    },
    {
      t: "Fiche 5 — Trigonométrie et cercle trigonométrique", st: "Radians, valeurs remarquables, équations, modèles périodiques", diff: "★★",
      desc: "Du cercle trigonométrique à la grande roue de la fête foraine.",
      ex: [
        {
          t: "Sur le cercle",
          c: [["q", "Placer sur le cercle trigonométrique les points images de $\\dfrac{5\\pi}{6}$, $-\\dfrac{3\\pi}{4}$ et $\\dfrac{7\\pi}{3}$.",
            "Donner la mesure principale de $\\dfrac{25\\pi}{6}$.",
            "Donner les valeurs exactes de $\\cos\\!\\left(\\dfrac{5\\pi}{6}\\right)$ et $\\sin\\!\\left(-\\dfrac{3\\pi}{4}\\right)$."]],
          sol: [["q", "$\\tfrac{5\\pi}{6}$ est dans le deuxième quadrant, $-\\tfrac{3\\pi}{4}$ dans le troisième, et $\\tfrac{7\\pi}{3} = \\tfrac{\\pi}{3} + 2\\pi$ a la même image que $\\tfrac{\\pi}{3}$.",
            "$\\tfrac{25\\pi}{6} = \\tfrac{\\pi}{6} + 4\\pi$ : la mesure principale est $\\tfrac{\\pi}{6}$.",
            "$\\cos\\!\\left(\\tfrac{5\\pi}{6}\\right) = -\\tfrac{\\sqrt{3}}{2}$ et $\\sin\\!\\left(-\\tfrac{3\\pi}{4}\\right) = -\\tfrac{\\sqrt{2}}{2}$."]],
        },
        {
          t: "Formules d'angles associés",
          c: ["Simplifier, pour tout réel $x$ :",
            ["q", "$A = \\cos(\\pi - x) + \\cos(x)$", "$B = \\sin\\!\\left(\\dfrac{\\pi}{2} + x\\right) - \\cos(-x)$",
              "$C = \\cos(\\pi + x)\\,\\sin(\\pi - x)$"]],
          sol: [["q", "$\\cos(\\pi - x) = -\\cos x$ donc $A = 0$.",
            "$\\sin\\!\\left(\\tfrac{\\pi}{2}+x\\right) = \\cos x$ et $\\cos(-x) = \\cos x$ : $B = 0$.",
            "$C = (-\\cos x)(\\sin x) = -\\cos x \\sin x$."]],
        },
        {
          t: "Équations trigonométriques",
          c: ["Résoudre dans $]-\\pi\\,;\\,\\pi]$ :",
            ["q", "$\\cos x = \\dfrac{1}{2}$", "$\\sin x = -\\dfrac{\\sqrt{2}}{2}$", "$2\\cos x + \\sqrt{3} = 0$"]],
          sol: [["q", "$x = \\tfrac{\\pi}{3}$ ou $x = -\\tfrac{\\pi}{3}$.",
            "$x = -\\tfrac{\\pi}{4}$ ou $x = -\\tfrac{3\\pi}{4}$.",
            "$\\cos x = -\\tfrac{\\sqrt{3}}{2}$ donc $x = \\tfrac{5\\pi}{6}$ ou $x = -\\tfrac{5\\pi}{6}$."]],
        },
        {
          t: "La grande roue",
          c: ["Une grande roue de rayon $30$ m a son centre à $35$ m du sol et fait un tour en $4$ minutes. La hauteur d'une nacelle, en mètres, $t$ minutes après le départ du sol, est",
            ["$", "h(t) = 35 - 30\\cos\\!\\left(\\frac{\\pi t}{2}\\right)."],
            ["q", "Vérifier que $h(0) = 5$ et interpréter.",
              "Calculer la hauteur au bout de $1$ minute, puis de $2$ minutes.",
              "À quels instants de la première rotation la nacelle est-elle à $35$ m ?",
              "Quelle est la hauteur maximale atteinte ?"]],
          sol: [["q", "$h(0) = 35 - 30 = 5$ : la nacelle embarque à $5$ m du sol.",
            "$h(1) = 35 - 30\\cos\\!\\left(\\tfrac{\\pi}{2}\\right) = 35$ m et $h(2) = 35 + 30 = 65$ m.",
            "$\\cos\\!\\left(\\tfrac{\\pi t}{2}\\right) = 0$ pour $t = 1$ et $t = 3$ minutes.",
            "Le maximum vaut $65$ m, atteint en $t = 2$ min (nacelle au sommet)."]],
        },
      ],
    },
    {
      t: "Fiche 6 — Produit scalaire", st: "Expressions, orthogonalité, Al-Kashi, ensembles de points", diff: "★★",
      desc: "Trois expressions du produit scalaire et leurs usages en géométrie et en physique.",
      ex: [
        {
          t: "Calculs dans un repère",
          c: ["Dans un repère orthonormé, $A(1\\,;\\,2)$, $B(4\\,;\\,3)$ et $C(2\\,;\\,-1)$.",
            ["q", "Calculer $\\vec{AB} \\cdot \\vec{AC}$.",
              "Calculer $AB$ et $AC$.",
              "En déduire $\\cos(\\widehat{BAC})$, puis une valeur approchée de l'angle en degrés.",
              "Le triangle $ABC$ est-il rectangle ?"]],
          sol: [["q", "$\\vec{AB}(3\\,;\\,1)$, $\\vec{AC}(1\\,;\\,-3)$ donc $\\vec{AB} \\cdot \\vec{AC} = 3 - 3 = 0$.",
            "$AB = \\sqrt{10}$ et $AC = \\sqrt{10}$.",
            "$\\cos(\\widehat{BAC}) = 0$ donc $\\widehat{BAC} = 90^{\\circ}$.",
            "Oui : il est rectangle isocèle en $A$."]],
        },
        {
          t: "Le théorème d'Al-Kashi",
          c: ["Dans un triangle $ABC$, $AB = 7$, $AC = 5$ et $\\widehat{BAC} = 60^{\\circ}$.",
            ["q", "Calculer $\\vec{AB} \\cdot \\vec{AC}$.",
              "En déduire la longueur $BC$ (valeur exacte puis approchée).",
              "Calculer l'aire du triangle."]],
          sol: [["q", "$\\vec{AB} \\cdot \\vec{AC} = 7 \\times 5 \\times \\cos 60^{\\circ} = 17{,}5$.",
            "$BC^{2} = 49 + 25 - 2 \\times 17{,}5 = 39$ donc $BC = \\sqrt{39} \\approx 6{,}24$.",
            "$\\mathcal{A} = \\tfrac{1}{2} \\times 7 \\times 5 \\times \\sin 60^{\\circ} = \\tfrac{35\\sqrt{3}}{4} \\approx 15{,}2$."]],
        },
        {
          t: "Ensembles de points",
          c: ["On donne deux points $A$ et $B$ tels que $AB = 6$, et $I$ le milieu de $[AB]$.",
            ["q", "Déterminer l'ensemble des points $M$ tels que $\\vec{MA} \\cdot \\vec{MB} = 0$.",
              "Montrer que $\\vec{MA} \\cdot \\vec{MB} = MI^{2} - 9$.",
              "En déduire l'ensemble des points $M$ tels que $\\vec{MA} \\cdot \\vec{MB} = 7$."]],
          sol: [["q", "C'est le cercle de diamètre $[AB]$, de centre $I$ et de rayon $3$.",
            "Avec $\\vec{MA} = \\vec{MI} + \\vec{IA}$ et $\\vec{MB} = \\vec{MI} + \\vec{IB} = \\vec{MI} - \\vec{IA}$, on obtient $MI^{2} - IA^{2} = MI^{2} - 9$.",
            "$MI^{2} = 16$, soit $MI = 4$ : c'est le cercle de centre $I$ et de rayon $4$."]],
        },
        {
          t: "Travail d'une force",
          c: ["Une luge est tirée sur $80$ m par une force constante d'intensité $150$ N, dont la direction fait un angle de $30^{\\circ}$ avec le déplacement.",
            ["q", "Exprimer le travail $W = \\vec{F} \\cdot \\vec{d}$ en fonction des données.",
              "Calculer $W$ en joules (valeur arrondie).",
              "Pour quel angle le travail serait-il nul ? Interpréter."]],
          sol: [["q", "$W = \\|\\vec{F}\\| \\times \\|\\vec{d}\\| \\times \\cos\\alpha$.",
            "$W = 150 \\times 80 \\times \\cos 30^{\\circ} = 12000 \\times \\tfrac{\\sqrt{3}}{2} \\approx 1{,}04 \\times 10^{4}$ J.",
            "Pour $\\alpha = 90^{\\circ}$ : une force perpendiculaire au déplacement ne travaille pas."]],
        },
      ],
    },
    {
      t: "Fiche 7 — Géométrie repérée", st: "Droites, vecteurs directeurs, cercles, intersections", diff: "★★",
      desc: "Équations cartésiennes, cercles et intersections, appliquées à une trajectoire de drone.",
      ex: [
        {
          t: "Droites du plan",
          c: ["On donne $A(-1\\,;\\,2)$ et $B(3\\,;\\,4)$.",
            ["q", "Déterminer un vecteur directeur de $(AB)$, puis une équation cartésienne de $(AB)$.",
              "La droite $d : 2x - 4y + 5 = 0$ est-elle parallèle à $(AB)$ ?",
              "Déterminer une équation de la perpendiculaire à $(AB)$ passant par $B$."]],
          sol: [["q", "$\\vec{AB}(4\\,;\\,2)$, donc $(AB) : 2x - 4y + 10 = 0$, soit $x - 2y + 5 = 0$.",
            "$d$ a pour vecteur normal $(2\\,;\\,-4)$, comme $(AB)$ : les droites sont parallèles (et distinctes).",
            "La perpendiculaire a pour vecteur normal $\\vec{AB}(4\\,;\\,2)$ : $4x + 2y + c = 0$ avec $B$ : $12 + 8 + c = 0$, donc $4x + 2y - 20 = 0$, soit $2x + y - 10 = 0$."]],
        },
        {
          t: "Reconnaître un cercle",
          c: ["Soit l'ensemble $\\mathcal{C}$ des points $M(x\\,;\\,y)$ tels que $x^{2} + y^{2} - 4x + 2y - 4 = 0$.",
            ["q", "Montrer que $\\mathcal{C}$ est un cercle dont on précisera le centre et le rayon.",
              "Le point $P(5\\,;\\,-1)$ appartient-il à $\\mathcal{C}$ ?",
              "Déterminer les points d'intersection de $\\mathcal{C}$ avec l'axe des abscisses."]],
          sol: [["q", "$(x-2)^{2} + (y+1)^{2} = 4 + 1 + 4 = 9$ : cercle de centre $\\Omega(2\\,;\\,-1)$ et de rayon $3$.",
            "$\\Omega P = \\sqrt{9 + 0} = 3$ : oui, $P \\in \\mathcal{C}$.",
            "Pour $y = 0$ : $(x-2)^{2} = 8$, soit $x = 2 \\pm 2\\sqrt{2}$."]],
        },
        {
          t: "Droite et cercle",
          c: ["Soit $\\mathcal{C}$ le cercle de centre $\\Omega(1\\,;\\,1)$ et de rayon $5$, et $d : y = x + 2$.",
            ["q", "Écrire une équation de $\\mathcal{C}$.",
              "Déterminer les coordonnées des points d'intersection de $d$ et $\\mathcal{C}$.",
              "Calculer la distance entre ces deux points."]],
          sol: [["q", "$(x-1)^{2} + (y-1)^{2} = 25$.",
            "En remplaçant : $(x-1)^{2} + (x+1)^{2} = 25 \\iff 2x^{2} + 2 = 25 \\iff x^{2} = \\tfrac{23}{2}$, donc $x = \\pm\\sqrt{11{,}5}$ et $y = x + 2$.",
            "Les abscisses sont opposées : la distance vaut $\\sqrt{2} \\times 2\\sqrt{11{,}5} = 2\\sqrt{23} \\approx 9{,}59$."]],
        },
        {
          t: "Couloir aérien",
          c: ["Un drone suit la droite $d : 3x + 4y - 12 = 0$. Une antenne est placée au point $T(6\\,;\\,5)$ et impose une zone interdite circulaire de rayon $4$.",
            ["q", "Calculer la distance du point $T$ à la droite $d$ (on pourra utiliser la formule $\\dfrac{|3x_{T} + 4y_{T} - 12|}{\\sqrt{3^{2}+4^{2}}}$).",
              "Le drone entre-t-il dans la zone interdite ?",
              "Quel devrait être le rayon maximal de la zone pour que la trajectoire reste autorisée ?"]],
          sol: [["q", "$\\dfrac{|18 + 20 - 12|}{5} = \\dfrac{26}{5} = 5{,}2$.",
            "$5{,}2 > 4$ : la trajectoire reste hors de la zone interdite.",
            "Tant que le rayon est strictement inférieur à $5{,}2$, la droite ne coupe pas le disque."]],
        },
      ],
    },
    {
      t: "Fiche 8 — Probabilités conditionnelles", st: "Arbres pondérés, probabilités totales, indépendance", diff: "★★",
      desc: "Arbres, tableaux croisés et un test de dépistage qui surprend.",
      ex: [
        {
          t: "Deux machines",
          c: ["Une usine fabrique des pièces avec deux machines. La machine $A$ produit $60\\,\\%$ des pièces et $3\\,\\%$ de sa production est défectueuse ; la machine $B$ produit le reste, avec $5\\,\\%$ de défauts.",
            ["q", "Construire un arbre pondéré.",
              "Calculer la probabilité qu'une pièce prise au hasard soit défectueuse.",
              "Une pièce est défectueuse : quelle est la probabilité qu'elle vienne de la machine $A$ ?"]],
          sol: [["q", "Premier niveau : $A$ ($0{,}6$) et $B$ ($0{,}4$) ; second niveau : $D$ avec $0{,}03$ et $0{,}05$.",
            "$P(D) = 0{,}6 \\times 0{,}03 + 0{,}4 \\times 0{,}05 = 0{,}018 + 0{,}02 = 0{,}038$.",
            "$P_{D}(A) = \\dfrac{0{,}018}{0{,}038} \\approx 0{,}474$."]],
        },
        {
          t: "Le test de dépistage",
          c: ["Une maladie touche $2\\,\\%$ d'une population. Un test donne un résultat positif pour $99\\,\\%$ des malades, et pour $5\\,\\%$ des personnes saines.",
            ["q", "Traduire l'énoncé par un arbre.",
              "Calculer la probabilité qu'un test pris au hasard soit positif.",
              "Une personne est testée positive : quelle est la probabilité qu'elle soit réellement malade ? Commenter."]],
          sol: [["q", "$P(M) = 0{,}02$, $P_{M}(T) = 0{,}99$, $P_{\\bar{M}}(T) = 0{,}05$.",
            "$P(T) = 0{,}02 \\times 0{,}99 + 0{,}98 \\times 0{,}05 = 0{,}0198 + 0{,}049 = 0{,}0688$.",
            "$P_{T}(M) = \\dfrac{0{,}0198}{0{,}0688} \\approx 0{,}288$ : moins d'un tiers des positifs sont malades, car la maladie est rare."]],
        },
        {
          t: "Tableau croisé",
          c: ["Dans un lycée de $500$ élèves, $300$ sont demi-pensionnaires, $200$ pratiquent un sport en club, et $150$ sont à la fois demi-pensionnaires et sportifs.",
            ["q", "Recopier et compléter un tableau croisé des effectifs.",
              "Calculer la probabilité qu'un élève choisi au hasard soit sportif sachant qu'il est demi-pensionnaire.",
              "Les événements « être demi-pensionnaire » et « être sportif » sont-ils indépendants ?"]],
          sol: [["q", "Demi-pensionnaires sportifs : $150$ ; demi-pensionnaires non sportifs : $150$ ; externes sportifs : $50$ ; externes non sportifs : $150$.",
            "$P_{D}(S) = \\dfrac{150}{300} = 0{,}5$.",
            "$P(S) = 0{,}4 \\neq 0{,}5 = P_{D}(S)$ : les événements ne sont pas indépendants."]],
        },
        {
          t: "Trois tirages",
          c: ["Une urne contient $4$ jetons verts et $6$ jetons rouges. On tire successivement $3$ jetons **avec remise**.",
            ["q", "Quelle est la probabilité d'obtenir trois jetons verts ?",
              "Quelle est la probabilité d'obtenir exactement un jeton vert ?",
              "Reprendre la première question pour un tirage **sans remise**."]],
          sol: [["q", "$0{,}4^{3} = 0{,}064$.",
            "$3 \\times 0{,}4 \\times 0{,}6^{2} = 3 \\times 0{,}144 = 0{,}432$.",
            "$\\dfrac{4}{10} \\times \\dfrac{3}{9} \\times \\dfrac{2}{8} = \\dfrac{24}{720} = \\dfrac{1}{30} \\approx 0{,}033$."]],
        },
      ],
    },
    {
      t: "Fiche 9 — Variables aléatoires et loi binomiale", st: "Loi de probabilité, espérance, variance, schéma de Bernoulli", diff: "★★★",
      desc: "Espérance d'un jeu, écart-type et répétitions d'épreuves identiques.",
      ex: [
        {
          t: "La fête foraine",
          c: ["À un stand, on lance un dé équilibré à six faces. On gagne $10$ € si l'on obtient un $6$, $2$ € si l'on obtient $4$ ou $5$, et rien sinon. La partie coûte $c$ euros.",
            ["q", "Donner la loi de probabilité du gain brut $G$.",
              "Calculer $E(G)$.",
              "Pour quelle mise $c$ le jeu est-il équitable ?",
              "Le forain fixe $c = 4$ €. Quel est son bénéfice moyen par partie ?"]],
          sol: [["q", "$P(G = 10) = \\tfrac{1}{6}$, $P(G = 2) = \\tfrac{2}{6}$, $P(G = 0) = \\tfrac{3}{6}$.",
            "$E(G) = \\tfrac{10}{6} + \\tfrac{4}{6} = \\tfrac{14}{6} \\approx 2{,}33$ €.",
            "Le jeu est équitable pour $c = \\tfrac{7}{3} \\approx 2{,}33$ €.",
            "$4 - \\tfrac{7}{3} = \\tfrac{5}{3} \\approx 1{,}67$ € de bénéfice moyen par partie."]],
        },
        {
          t: "Espérance, variance, écart-type",
          c: ["Soit $X$ la variable aléatoire de loi : $P(X=-1) = 0{,}3$, $P(X=0) = 0{,}5$, $P(X=4) = 0{,}2$.",
            ["q", "Vérifier qu'il s'agit bien d'une loi de probabilité.",
              "Calculer $E(X)$, $V(X)$ et $\\sigma(X)$.",
              "On pose $Y = 5X + 2$. Calculer $E(Y)$ et $\\sigma(Y)$."]],
          sol: [["q", "$0{,}3 + 0{,}5 + 0{,}2 = 1$ et toutes les probabilités sont positives.",
            "$E(X) = -0{,}3 + 0 + 0{,}8 = 0{,}5$ ; $E(X^{2}) = 0{,}3 + 0 + 3{,}2 = 3{,}5$ donc $V(X) = 3{,}5 - 0{,}25 = 3{,}25$ et $\\sigma(X) \\approx 1{,}80$.",
            "$E(Y) = 5 \\times 0{,}5 + 2 = 4{,}5$ et $\\sigma(Y) = 5\\sigma(X) \\approx 9{,}01$."]],
        },
        {
          t: "Contrôle qualité",
          c: ["Une chaîne produit des ampoules dont $4\\,\\%$ sont défectueuses. On prélève au hasard $20$ ampoules (production assez grande pour assimiler à un tirage avec remise). On note $X$ le nombre d'ampoules défectueuses.",
            ["q", "Justifier que $X$ suit une loi binomiale dont on précisera les paramètres.",
              "Calculer $P(X = 0)$, arrondi à $10^{-3}$.",
              "Calculer $P(X \\geqslant 1)$.",
              "Calculer $E(X)$ et interpréter."]],
          sol: [["q", "Répétition de $20$ épreuves de Bernoulli identiques et indépendantes de paramètre $p = 0{,}04$ : $X \\sim \\mathcal{B}(20\\,;\\,0{,}04)$.",
            "$P(X=0) = 0{,}96^{20} \\approx 0{,}442$.",
            "$P(X \\geqslant 1) = 1 - 0{,}442 = 0{,}558$.",
            "$E(X) = 20 \\times 0{,}04 = 0{,}8$ : en moyenne moins d'une ampoule défectueuse par lot de $20$."]],
        },
        {
          t: "QCM au hasard",
          c: ["Un QCM comporte $10$ questions à $4$ réponses possibles dont une seule est exacte. Un élève répond totalement au hasard ; $X$ est son nombre de bonnes réponses.",
            ["q", "Quelle est la loi de $X$ ?",
              "Calculer la probabilité qu'il ait exactement $3$ bonnes réponses (arrondi à $10^{-3}$).",
              "Calculer la probabilité d'avoir au moins la moyenne, c'est-à-dire $X \\geqslant 5$.",
              "Calculer $E(X)$ et $\\sigma(X)$."]],
          sol: [["q", "$X \\sim \\mathcal{B}\\!\\left(10\\,;\\,\\tfrac{1}{4}\\right)$.",
            "$P(X=3) = \\binom{10}{3}\\left(\\tfrac{1}{4}\\right)^{3}\\left(\\tfrac{3}{4}\\right)^{7} \\approx 0{,}250$.",
            "$P(X \\geqslant 5) = 1 - P(X \\leqslant 4) \\approx 1 - 0{,}922 = 0{,}078$.",
            "$E(X) = 2{,}5$ et $\\sigma(X) = \\sqrt{10 \\times 0{,}25 \\times 0{,}75} \\approx 1{,}37$."]],
        },
      ],
    },
    {
      t: "Fiche 10 — Algorithmique et Python", st: "Boucles, seuils, sommes, simulations", diff: "★★",
      desc: "Écrire, lire et corriger des programmes courts liés aux suites et aux probabilités.",
      ex: [
        {
          t: "Lire un programme",
          c: [["code", "python", "def mystere(n):\n    s = 0\n    for k in range(1, n + 1):\n        s = s + k * k\n    return s"],
            ["q", "Que renvoie $\\texttt{mystere(4)}$ ?",
              "Quelle somme mathématique la fonction calcule-t-elle ?",
              "Modifier le programme pour qu'il calcule la somme des cubes."]],
          sol: [["q", "$1 + 4 + 9 + 16 = 30$.",
            "$\\displaystyle\\sum_{k=1}^{n} k^{2}$.",
            "Remplacer $\\texttt{k * k}$ par $\\texttt{k ** 3}$."]],
        },
        {
          t: "Boucle de seuil",
          c: ["Une population de bactéries double toutes les heures ; elle compte $500$ individus au départ.",
            ["q", "Écrire une fonction Python $\\texttt{heures(S)}$ renvoyant le nombre d'heures nécessaires pour dépasser $S$ bactéries.",
              "Combien d'heures pour dépasser un million ?",
              "Pourquoi une boucle $\\texttt{for}$ serait-elle mal adaptée ici ?"]],
          sol: [["code", "python", "def heures(S):\n    b = 500\n    n = 0\n    while b <= S:\n        b = 2 * b\n        n = n + 1\n    return n"],
            ["q", "Le programme ci-dessus convient.",
              "$500 \\times 2^{11} = 1\\,024\\,000 > 10^{6}$ : il faut $11$ heures.",
              "On ne connaît pas à l'avance le nombre de répétitions : la boucle non bornée $\\texttt{while}$ s'impose."]],
        },
        {
          t: "Corriger un programme",
          c: ["Ce programme doit calculer les $n$ premiers termes de la suite $u_{0} = 1$, $u_{n+1} = 3u_{n} - 2$ :",
            ["code", "python", "def suite(n):\n    u = 0\n    for k in range(n):\n        u = 3 * u - 2\n    return u"],
            ["q", "Calculer à la main $u_{1}$, $u_{2}$ et $u_{3}$.",
              "Repérer l'erreur du programme et la corriger.",
              "Conjecturer une expression de $u_{n}$ (on pourra étudier $v_{n} = u_{n} - 1$)."]],
          sol: [["q", "$u_{1} = 1$, $u_{2} = 1$, $u_{3} = 1$ : la suite est constante.",
            "L'initialisation est fausse : il faut $\\texttt{u = 1}$.",
            "$v_{n} = u_{n} - 1 = 0$ pour tout $n$ : $u_{n} = 1$. La valeur $1$ est le point fixe de $x \\mapsto 3x - 2$."]],
        },
        {
          t: "Simuler pour estimer",
          c: ["On simule le lancer de deux dés équilibrés.",
            ["code", "python", "from random import randint\n\ndef simule(N):\n    c = 0\n    for i in range(N):\n        if randint(1, 6) + randint(1, 6) == 7:\n            c = c + 1\n    return c / N"],
            ["q", "Que représente la valeur renvoyée par $\\texttt{simule(10000)}$ ?",
              "Calculer la probabilité théorique d'obtenir une somme égale à $7$.",
              "Modifier la fonction pour estimer la probabilité d'obtenir un double."]],
          sol: [["q", "La fréquence observée de la somme $7$ sur $10\\,000$ lancers : une estimation de sa probabilité.",
            "Il y a $6$ cas favorables sur $36$ : $P = \\tfrac{1}{6} \\approx 0{,}167$.",
            "Stocker les deux dés dans deux variables $\\texttt{a}$ et $\\texttt{b}$ puis tester $\\texttt{if a == b:}$ (probabilité théorique $\\tfrac{1}{6}$)."]],
        },
      ],
    },
  ]);

  L.addSujets("1re", "ds", [
    {
      t: "Contrôle n° 1 — Second degré", st: "Trinômes, signes, optimisation", h: 1, calc: "autorisée",
      desc: "Trois exercices courts : formes canoniques, inéquations et un problème d'optimisation.",
      ex: [
        {
          t: "Formes et racines", pts: 7,
          c: ["Soit $f(x) = 2x^{2} - 8x + 6$.",
            ["q", "Déterminer la forme canonique de $f$.", "Résoudre $f(x) = 0$.", "Donner la forme factorisée de $f$.",
              "Dresser le tableau de signes de $f(x)$.", "Déterminer le minimum de $f$ et la valeur en laquelle il est atteint."]],
          sol: [["q", "$f(x) = 2(x^{2} - 4x + 3) = 2\\big[(x-2)^{2} - 1\\big] = 2(x-2)^{2} - 2$.",
            "$\\Delta = 64 - 48 = 16$ : $x_{1} = \\tfrac{8-4}{4} = 1$ et $x_{2} = 3$.",
            "$f(x) = 2(x-1)(x-3)$.",
            "$f(x) > 0$ hors de $[1\\,;\\,3]$, négatif sur $]1\\,;\\,3[$, nul en $1$ et $3$.",
            "Minimum $-2$ atteint en $x = 2$."]],
        },
        {
          t: "Inéquations", pts: 6,
          c: ["Résoudre dans $\\mathbb{R}$ :",
            ["q", "$-x^{2} + 4x - 3 > 0$", "$x^{2} + 2x + 5 \\leqslant 0$", "$\\dfrac{2x - 1}{x + 3} \\geqslant 0$"]],
          sol: [["q", "Racines $1$ et $3$, $a < 0$ : $S = \\,]1\\,;\\,3[$.",
            "$\\Delta = 4 - 20 = -16 < 0$ et $a > 0$ : le trinôme est toujours strictement positif, $S = \\varnothing$.",
            "Valeurs interdites $x = -3$ ; tableau de signes : $S = \\,]-\\infty\\,;\\,-3[\\,\\cup\\,\\left[\\tfrac{1}{2}\\,;\\,+\\infty\\right[$."]],
        },
        {
          t: "L'enclos du refuge", pts: 7,
          c: ["Un refuge animalier adosse un enclos rectangulaire à un mur : trois côtés seulement sont grillagés, pour une longueur totale de $60$ m. On note $x$ la largeur perpendiculaire au mur.",
            ["q", "Exprimer la longueur du côté parallèle au mur en fonction de $x$.",
              "En déduire l'aire $A(x)$ de l'enclos et l'intervalle de définition.",
              "Montrer que $A(x) = -2(x - 15)^{2} + 450$.",
              "Déterminer les dimensions de l'enclos d'aire maximale.",
              "L'aire peut-elle atteindre $500$ m$^{2}$ ? Justifier."]],
          sol: [["q", "Le côté parallèle au mur mesure $60 - 2x$.",
            "$A(x) = x(60 - 2x) = -2x^{2} + 60x$, avec $x \\in \\,]0\\,;\\,30[$.",
            "$-2(x-15)^{2} + 450 = -2x^{2} + 60x - 450 + 450 = A(x)$.",
            "Aire maximale pour $x = 15$ m : enclos de $15$ m sur $30$ m, d'aire $450$ m$^{2}$.",
            "Non : $450$ est le maximum de $A$, donc $A(x) \\leqslant 450 < 500$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 2 — Suites", st: "Arithmétiques, géométriques, suites auxiliaires, algorithme", h: 1, calc: "autorisée",
      desc: "Un abonnement de salle de sport, une somme de termes et un algorithme de seuil.",
      ex: [
        {
          t: "Reconnaître une suite", pts: 6,
          c: [["q", "$u_{n} = 5n - 3$ : montrer que $(u_{n})$ est arithmétique et donner sa raison.",
            "$v_{n} = 3 \\times 2^{\\,n}$ : montrer que $(v_{n})$ est géométrique et donner sa raison.",
            "Calculer $u_{0} + u_{1} + \\dots + u_{20}$.",
            "Calculer $v_{0} + v_{1} + \\dots + v_{10}$."]],
          sol: [["q", "$u_{n+1} - u_{n} = 5$ : arithmétique de raison $5$.",
            "$\\dfrac{v_{n+1}}{v_{n}} = 2$ : géométrique de raison $2$.",
            "$21$ termes, $u_{0} = -3$, $u_{20} = 97$ : $S = \\dfrac{21 \\times 94}{2} = 987$.",
            "$S = 3 \\times \\dfrac{2^{11} - 1}{2 - 1} = 3 \\times 2047 = 6141$."]],
        },
        {
          t: "La salle de sport", pts: 9,
          c: ["Une salle de sport compte $800$ adhérents en janvier. Chaque mois, elle perd $10\\,\\%$ de ses adhérents mais en recrute $120$ nouveaux. On note $a_{n}$ le nombre d'adhérents après $n$ mois, $a_{0} = 800$.",
            ["q", "Calculer $a_{1}$ et $a_{2}$.",
              "Justifier que $a_{n+1} = 0{,}9\\,a_{n} + 120$.",
              "On pose $b_{n} = a_{n} - 1200$. Montrer que $(b_{n})$ est géométrique de raison $0{,}9$.",
              "Exprimer $b_{n}$ puis $a_{n}$ en fonction de $n$.",
              "Le nombre d'adhérents peut-il dépasser $1\\,200$ ? Justifier.",
              "Déterminer, à la calculatrice, le premier mois où la salle dépasse $1\\,100$ adhérents."]],
          sol: [["q", "$a_{1} = 720 + 120 = 840$ et $a_{2} = 756 + 120 = 876$.",
            "On garde $90\\,\\%$ des adhérents, auxquels s'ajoutent $120$ nouveaux.",
            "$b_{n+1} = 0{,}9a_{n} + 120 - 1200 = 0{,}9(a_{n} - 1200) = 0{,}9\\,b_{n}$.",
            "$b_{0} = -400$ donc $b_{n} = -400 \\times 0{,}9^{\\,n}$ et $a_{n} = 1200 - 400 \\times 0{,}9^{\\,n}$.",
            "Non : $400 \\times 0{,}9^{\\,n} > 0$, donc $a_{n} < 1200$ pour tout $n$ (la suite croît vers $1\\,200$).",
            "$a_{13} \\approx 1099$ et $a_{14} \\approx 1110$ : c'est au bout de $14$ mois."]],
        },
        {
          t: "Algorithme", pts: 5,
          c: ["On considère le programme suivant, appliqué à la suite de l'exercice précédent :",
            ["code", "python", "def mois():\n    a = 800\n    n = 0\n    while a < 1100:\n        a = 0.9 * a + 120\n        n = n + 1\n    return n"],
            ["q", "Que renvoie ce programme ?",
              "Modifier le programme pour qu'il renvoie le nombre d'adhérents au bout de $n$ mois, $n$ étant donné en paramètre.",
              "Expliquer pourquoi la boucle $\\texttt{while}$ se termine forcément ici."]],
          sol: [["q", "Il renvoie $14$, le premier mois où le seuil $1\\,100$ est franchi.",
            "Remplacer la boucle par $\\texttt{for k in range(n): a = 0.9 * a + 120}$ puis $\\texttt{return a}$.",
            "La suite est strictement croissante et tend vers $1\\,200 > 1\\,100$ : le seuil finit par être dépassé."]],
        },
      ],
    },
    {
      t: "Contrôle n° 3 — Dérivation", st: "Nombre dérivé, tangentes, variations, optimisation", h: 1, calc: "autorisée",
      desc: "Calculs de dérivées, lecture graphique et une boîte de conserve à optimiser.",
      ex: [
        {
          t: "Calculs de dérivées", pts: 6,
          c: ["Dériver sur un intervalle bien choisi :",
            ["q", "$f(x) = 4x^{3} - 2x^{2} + 7$", "$g(x) = (x^{2} + 1)(3 - x)$", "$h(x) = \\dfrac{x + 2}{2x - 1}$", "$k(x) = \\dfrac{1}{x} + \\sqrt{x}$"]],
          sol: [["q", "$f'(x) = 12x^{2} - 4x$.",
            "$g'(x) = 2x(3 - x) + (x^{2}+1)(-1) = -3x^{2} + 6x - 1$.",
            "$h'(x) = \\dfrac{(2x-1) - 2(x+2)}{(2x-1)^{2}} = \\dfrac{-5}{(2x-1)^{2}}$.",
            "$k'(x) = -\\dfrac{1}{x^{2}} + \\dfrac{1}{2\\sqrt{x}}$ sur $]0\\,;\\,+\\infty[$."]],
        },
        {
          t: "Tangentes", pts: 6,
          c: ["Soit $f(x) = x^{3} - 6x^{2} + 9x$.",
            ["q", "Calculer $f'(x)$ et étudier son signe.",
              "Dresser le tableau de variations de $f$ sur $\\mathbb{R}$.",
              "Déterminer l'équation de la tangente $T$ au point d'abscisse $0$.",
              "Déterminer les abscisses des points où la tangente est parallèle à $T$."]],
          sol: [["q", "$f'(x) = 3x^{2} - 12x + 9 = 3(x-1)(x-3)$, positif hors de $[1\\,;\\,3]$, négatif entre $1$ et $3$.",
            "Croissante jusqu'à $x=1$ (maximum local $f(1) = 4$), décroissante jusqu'à $x=3$ (minimum local $f(3) = 0$), puis croissante.",
            "$f(0) = 0$, $f'(0) = 9$ : $T : y = 9x$.",
            "$f'(x) = 9 \\iff 3x^{2} - 12x = 0 \\iff x = 0$ ou $x = 4$."]],
        },
        {
          t: "La boîte de conserve", pts: 8,
          c: ["Une boîte cylindrique de rayon $r$ (en cm) doit contenir $500$ cm$^{3}$. Sa hauteur vérifie donc $h = \\dfrac{500}{\\pi r^{2}}$. La surface de métal utilisée est",
            ["$", "S(r) = 2\\pi r^{2} + \\frac{1000}{r}, \\qquad r > 0."],
            ["q", "Retrouver l'expression de $S(r)$ à partir de $h$.",
              "Calculer $S'(r)$ et montrer que $S'(r) = \\dfrac{4\\pi r^{3} - 1000}{r^{2}}$.",
              "En déduire le rayon qui minimise la surface (arrondi au dixième).",
              "Calculer la hauteur correspondante. Que remarque-t-on ?"]],
          sol: [["q", "$S = 2\\pi r^{2}$ (les deux disques) $+\\ 2\\pi r h$ ; or $2\\pi r h = 2\\pi r \\times \\dfrac{500}{\\pi r^{2}} = \\dfrac{1000}{r}$.",
            "$S'(r) = 4\\pi r - \\dfrac{1000}{r^{2}} = \\dfrac{4\\pi r^{3} - 1000}{r^{2}}$.",
            "$S'(r) = 0 \\iff r^{3} = \\dfrac{250}{\\pi}$, soit $r \\approx 4{,}3$ cm ; $S'$ change de signe de $-$ à $+$ : c'est un minimum.",
            "$h = \\dfrac{500}{\\pi r^{2}} \\approx 8{,}6$ cm $\\approx 2r$ : la boîte optimale est aussi haute que large."]],
        },
      ],
    },
    {
      t: "Contrôle n° 4 — Probabilités", st: "Arbres, probabilités totales, variable aléatoire, binomiale", h: 1, calc: "autorisée",
      desc: "Un escape game, un jeu de hasard et un contrôle qualité.",
      ex: [
        {
          t: "L'escape game", pts: 7,
          c: ["Une équipe doit ouvrir deux coffres. Elle ouvre le premier avec une probabilité $0{,}7$. Si elle y parvient, elle ouvre le second avec une probabilité $0{,}8$ ; sinon, avec une probabilité $0{,}3$ seulement.",
            ["q", "Représenter la situation par un arbre pondéré.",
              "Calculer la probabilité que l'équipe ouvre les deux coffres.",
              "Calculer la probabilité qu'elle ouvre le second coffre.",
              "Sachant qu'elle a ouvert le second coffre, quelle est la probabilité qu'elle ait ouvert le premier ?"]],
          sol: [["q", "Premier niveau $A$ ($0{,}7$) / $\\bar{A}$ ($0{,}3$) ; second niveau $B$ avec $0{,}8$ et $0{,}3$.",
            "$P(A \\cap B) = 0{,}7 \\times 0{,}8 = 0{,}56$.",
            "$P(B) = 0{,}56 + 0{,}3 \\times 0{,}3 = 0{,}56 + 0{,}09 = 0{,}65$.",
            "$P_{B}(A) = \\dfrac{0{,}56}{0{,}65} \\approx 0{,}862$."]],
        },
        {
          t: "La roue de la fortune", pts: 7,
          c: ["Une roue comporte $8$ secteurs identiques : trois marqués $0$ €, quatre marqués $5$ € et un marqué $20$ €. On note $X$ le gain obtenu.",
            ["q", "Donner la loi de probabilité de $X$.",
              "Calculer $E(X)$ et interpréter.",
              "Calculer $V(X)$ et $\\sigma(X)$ (arrondi au centième).",
              "Le stand fait payer $6$ € la partie. Est-ce avantageux pour le joueur ?"]],
          sol: [["q", "$P(X=0) = \\tfrac{3}{8}$, $P(X=5) = \\tfrac{4}{8}$, $P(X=20) = \\tfrac{1}{8}$.",
            "$E(X) = \\tfrac{20}{8} + \\tfrac{20}{8} = \\tfrac{40}{8} = 5$ € : gain moyen de $5$ € par partie.",
            "$E(X^{2}) = \\tfrac{100}{8} + \\tfrac{400}{8} = 62{,}5$ donc $V(X) = 62{,}5 - 25 = 37{,}5$ et $\\sigma(X) \\approx 6{,}12$.",
            "Non : la mise de $6$ € dépasse le gain moyen de $5$ €, le joueur perd $1$ € par partie en moyenne."]],
        },
        {
          t: "Contrôle qualité", pts: 6,
          c: ["Dans une production de clés USB, $5\\,\\%$ sont défectueuses. On en prélève $30$ au hasard ; $X$ compte les défectueuses.",
            ["q", "Justifier que $X$ suit une loi binomiale et préciser ses paramètres.",
              "Calculer $P(X = 0)$ et $P(X = 1)$ à $10^{-3}$ près.",
              "Calculer la probabilité qu'au moins deux clés soient défectueuses.",
              "Calculer $E(X)$."]],
          sol: [["q", "$30$ épreuves identiques et indépendantes, succès « clé défectueuse » de probabilité $0{,}05$ : $X \\sim \\mathcal{B}(30\\,;\\,0{,}05)$.",
            "$P(X=0) = 0{,}95^{30} \\approx 0{,}215$ ; $P(X=1) = 30 \\times 0{,}05 \\times 0{,}95^{29} \\approx 0{,}339$.",
            "$P(X \\geqslant 2) = 1 - 0{,}215 - 0{,}339 \\approx 0{,}446$.",
            "$E(X) = 30 \\times 0{,}05 = 1{,}5$ clé défectueuse en moyenne."]],
        },
      ],
    },
    {
      t: "Contrôle n° 5 — Géométrie", st: "Produit scalaire, droites, cercles", h: 1, calc: "autorisée",
      desc: "Produit scalaire dans un repère, Al-Kashi et un cercle à reconnaître.",
      ex: [
        {
          t: "Dans un repère", pts: 7,
          c: ["On donne $A(-2\\,;\\,1)$, $B(4\\,;\\,3)$ et $C(0\\,;\\,-3)$.",
            ["q", "Calculer les coordonnées de $\\vec{AB}$ et $\\vec{AC}$.",
              "Calculer $\\vec{AB} \\cdot \\vec{AC}$.",
              "Calculer $AB$ et $AC$, puis $\\cos(\\widehat{BAC})$.",
              "Déterminer une équation cartésienne de la droite $(AB)$.",
              "Déterminer les coordonnées du milieu $I$ de $[BC]$."]],
          sol: [["q", "$\\vec{AB}(6\\,;\\,2)$ et $\\vec{AC}(2\\,;\\,-4)$.",
            "$\\vec{AB} \\cdot \\vec{AC} = 12 - 8 = 4$.",
            "$AB = \\sqrt{40} = 2\\sqrt{10}$, $AC = \\sqrt{20} = 2\\sqrt{5}$, $\\cos(\\widehat{BAC}) = \\dfrac{4}{4\\sqrt{50}} = \\dfrac{1}{5\\sqrt{2}} \\approx 0{,}141$.",
            "Vecteur directeur $(6\\,;\\,2)$, donc $2x - 6y + c = 0$ ; avec $A$ : $-4 - 6 + c = 0$, d'où $x - 3y + 5 = 0$.",
            "$I(2\\,;\\,0)$."]],
        },
        {
          t: "Al-Kashi en terrasse", pts: 6,
          c: ["Un géomètre vise deux arbres $B$ et $C$ depuis un point $A$ : $AB = 40$ m, $AC = 55$ m et $\\widehat{BAC} = 48^{\\circ}$.",
            ["q", "Calculer $\\vec{AB} \\cdot \\vec{AC}$, arrondi à l'unité.",
              "En déduire la distance $BC$, arrondie au mètre.",
              "Calculer l'aire du triangle $ABC$, arrondie au m$^{2}$."]],
          sol: [["q", "$40 \\times 55 \\times \\cos 48^{\\circ} \\approx 1472$.",
            "$BC^{2} = 1600 + 3025 - 2944 = 1681$ donc $BC = 41$ m.",
            "$\\mathcal{A} = \\tfrac{1}{2} \\times 40 \\times 55 \\times \\sin 48^{\\circ} \\approx 818$ m$^{2}$."]],
        },
        {
          t: "Un cercle à reconnaître", pts: 7,
          c: ["Soit $\\mathcal{C} : x^{2} + y^{2} - 6x + 4y + 9 = 0$.",
            ["q", "Montrer que $\\mathcal{C}$ est un cercle, préciser son centre $\\Omega$ et son rayon.",
              "Le point $A(3\\,;\\,0)$ appartient-il à $\\mathcal{C}$ ?",
              "Déterminer les points d'intersection de $\\mathcal{C}$ avec la droite $d : y = -2$.",
              "Montrer que la droite $x = 7$ ne coupe pas $\\mathcal{C}$."]],
          sol: [["q", "$(x-3)^{2} + (y+2)^{2} = 9 + 4 - 9 = 4$ : centre $\\Omega(3\\,;\\,-2)$, rayon $2$.",
            "$\\Omega A = \\sqrt{0 + 4} = 2$ : oui.",
            "Pour $y = -2$ : $(x-3)^{2} = 4$, soit $x = 1$ ou $x = 5$ : les points $(1\\,;\\,-2)$ et $(5\\,;\\,-2)$.",
            "La distance de $\\Omega$ à cette droite verticale vaut $|7 - 3| = 4 > 2$ : pas d'intersection."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 1 — Fonctions et suites", st: "Second degré, dérivation, suites, algorithmique", h: 2, calc: "autorisée",
      desc: "Quatre exercices de synthèse autour d'un skatepark et d'une ferme aquaponique.",
      ex: [
        {
          t: "Le profil du skatepark", pts: 6,
          c: ["Le profil d'une rampe est modélisé, pour $x \\in [0\\,;\\,6]$ (en mètres), par $f(x) = 0{,}25x^{2} - 2x + 4$.",
            ["q", "Calculer $f(0)$ et $f(6)$. Interpréter.",
              "Déterminer la forme canonique de $f$.",
              "En quel point la rampe est-elle la plus basse, et à quelle hauteur ?",
              "Résoudre $f(x) = 1$ et interpréter graphiquement."]],
          sol: [["q", "$f(0) = 4$ m et $f(6) = 9 - 12 + 4 = 1$ m : la rampe part de $4$ m et finit à $1$ m.",
            "$f(x) = 0{,}25(x^{2} - 8x) + 4 = 0{,}25(x-4)^{2} - 4 + 4 = 0{,}25(x-4)^{2}$.",
            "Le point le plus bas est en $x = 4$ m, à la hauteur $0$ m (la rampe touche le sol).",
            "$0{,}25(x-4)^{2} = 1 \\iff (x-4)^{2} = 4 \\iff x = 2$ ou $x = 6$ : la rampe est à $1$ m de haut en deux endroits."]],
        },
        {
          t: "Étude d'une fonction", pts: 7,
          c: ["Soit $g$ définie sur $]1\\,;\\,+\\infty[$ par $g(x) = \\dfrac{x^{2}}{x - 1}$.",
            ["q", "Calculer $g'(x)$ et montrer que $g'(x) = \\dfrac{x(x-2)}{(x-1)^{2}}$.",
              "Étudier le signe de $g'(x)$ sur $]1\\,;\\,+\\infty[$.",
              "Dresser le tableau de variations de $g$.",
              "Déterminer l'équation de la tangente à la courbe au point d'abscisse $3$."]],
          sol: [["q", "$g'(x) = \\dfrac{2x(x-1) - x^{2}}{(x-1)^{2}} = \\dfrac{x^{2} - 2x}{(x-1)^{2}} = \\dfrac{x(x-2)}{(x-1)^{2}}$.",
            "Sur $]1\\,;\\,+\\infty[$, $x > 0$ et $(x-1)^{2} > 0$ : le signe est celui de $x - 2$.",
            "$g$ décroît sur $]1\\,;\\,2]$ puis croît sur $[2\\,;\\,+\\infty[$, avec un minimum $g(2) = 4$.",
            "$g(3) = \\tfrac{9}{2}$ et $g'(3) = \\tfrac{3}{4}$ : $y = \\tfrac{3}{4}(x-3) + \\tfrac{9}{2} = \\tfrac{3}{4}x + \\tfrac{9}{4}$."]],
        },
        {
          t: "La ferme aquaponique", pts: 7,
          c: ["Un bassin contient $4\\,000$ truites. Chaque mois, $12\\,\\%$ des truites sont vendues et l'éleveur ajoute $600$ alevins. On note $t_{n}$ le nombre de truites après $n$ mois, $t_{0} = 4000$.",
            ["q", "Calculer $t_{1}$ et $t_{2}$.",
              "Exprimer $t_{n+1}$ en fonction de $t_{n}$.",
              "On pose $w_{n} = t_{n} - 5000$. Montrer que $(w_{n})$ est géométrique.",
              "En déduire $t_{n}$ en fonction de $n$.",
              "Le bassin peut contenir au plus $4\\,900$ truites. À partir de quel mois faut-il prévoir un second bassin ?"]],
          sol: [["q", "$t_{1} = 0{,}88 \\times 4000 + 600 = 4120$ et $t_{2} = 0{,}88 \\times 4120 + 600 \\approx 4225{,}6$, soit $4\\,225$ truites.",
            "$t_{n+1} = 0{,}88\\,t_{n} + 600$.",
            "$w_{n+1} = 0{,}88t_{n} + 600 - 5000 = 0{,}88(t_{n} - 5000) = 0{,}88\\,w_{n}$ : raison $0{,}88$.",
            "$w_{0} = -1000$ donc $t_{n} = 5000 - 1000 \\times 0{,}88^{\\,n}$.",
            "$t_{n} > 4900 \\iff 0{,}88^{\\,n} < 0{,}1$ ; à la calculatrice $0{,}88^{18} \\approx 0{,}102$ et $0{,}88^{19} \\approx 0{,}090$ : à partir du $19^{\\text{e}}$ mois."]],
        },
        {
          t: "Algorithmique", pts: 5,
          c: ["On reprend la suite $(t_{n})$ de l'exercice précédent.",
            ["q", "Écrire une fonction Python $\\texttt{truites(n)}$ renvoyant $t_{n}$.",
              "Écrire une fonction $\\texttt{seuil()}$ renvoyant le premier rang où $t_{n} > 4900$.",
              "Expliquer pourquoi la suite ne dépassera jamais $5\\,000$."]],
          sol: [["code", "python", "def truites(n):\n    t = 4000\n    for k in range(n):\n        t = 0.88 * t + 600\n    return t\n\ndef seuil():\n    t = 4000\n    n = 0\n    while t <= 4900:\n        t = 0.88 * t + 600\n        n = n + 1\n    return n"],
            ["q", "Voir le programme ci-dessus.", "Elle renvoie $19$.",
              "$t_{n} = 5000 - 1000 \\times 0{,}88^{\\,n}$ avec $1000 \\times 0{,}88^{\\,n} > 0$ : $t_{n} < 5000$ pour tout $n$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 2 — Exponentielle et suites", st: "Exponentielle, dérivation, suites géométriques, algorithme", h: 2, calc: "autorisée",
      desc: "Décroissance radioactive, étude de fonction et modélisation d'un lac pollué.",
      ex: [
        {
          t: "Calculs et équations", pts: 5,
          c: [["q", "Simplifier $A = \\dfrac{\\mathrm{e}^{3x} \\times \\mathrm{e}^{-x+1}}{\\mathrm{e}^{x}}$.",
            "Résoudre $\\mathrm{e}^{x^{2} - 1} = \\mathrm{e}^{0}$.",
            "Résoudre $\\mathrm{e}^{2x} - 4\\mathrm{e}^{x} = 0$.",
            "Résoudre l'inéquation $\\mathrm{e}^{-x} < \\mathrm{e}^{2x - 3}$."]],
          sol: [["q", "$A = \\mathrm{e}^{3x - x + 1 - x} = \\mathrm{e}^{x+1}$.",
            "$x^{2} - 1 = 0 \\iff x = -1$ ou $x = 1$.",
            "$\\mathrm{e}^{x}(\\mathrm{e}^{x} - 4) = 0 \\iff \\mathrm{e}^{x} = 4$ ; sans logarithme on conclut par lecture graphique : $x \\approx 1{,}39$.",
            "La fonction exponentielle étant croissante : $-x < 2x - 3 \\iff x > 1$."]],
        },
        {
          t: "Étude d'une fonction", pts: 7,
          c: ["Soit $f(x) = (2 - x)\\,\\mathrm{e}^{-x}$ sur $\\mathbb{R}$.",
            ["q", "Montrer que $f'(x) = (x - 3)\\,\\mathrm{e}^{-x}$.",
              "Étudier le signe de $f'$ et dresser le tableau de variations de $f$.",
              "Calculer $f(3)$ (valeur exacte puis arrondie à $10^{-2}$).",
              "Déterminer l'équation de la tangente au point d'abscisse $2$.",
              "Résoudre $f(x) \\geqslant 0$."]],
          sol: [["q", "$f'(x) = -\\mathrm{e}^{-x} + (2-x)(-\\mathrm{e}^{-x}) = \\mathrm{e}^{-x}(-1 - 2 + x) = (x-3)\\mathrm{e}^{-x}$.",
            "$\\mathrm{e}^{-x} > 0$ : $f$ décroît sur $]-\\infty\\,;\\,3]$ puis croît sur $[3\\,;\\,+\\infty[$.",
            "$f(3) = -\\mathrm{e}^{-3} \\approx -0{,}05$ : c'est le minimum de $f$.",
            "$f(2) = 0$ et $f'(2) = -\\mathrm{e}^{-2}$ : $y = -\\mathrm{e}^{-2}(x - 2)$.",
            "$\\mathrm{e}^{-x} > 0$ donc $f(x) \\geqslant 0 \\iff 2 - x \\geqslant 0 \\iff x \\leqslant 2$."]],
        },
        {
          t: "Le lac et ses nitrates", pts: 8,
          c: ["Un lac contient $80$ tonnes de nitrates. Chaque année, $25\\,\\%$ des nitrates sont éliminés naturellement, mais l'agriculture en apporte $12$ tonnes. On note $n_{k}$ la masse de nitrates après $k$ années, $n_{0} = 80$.",
            ["q", "Calculer $n_{1}$ et $n_{2}$.",
              "Justifier que $n_{k+1} = 0{,}75\\,n_{k} + 12$.",
              "On pose $d_{k} = n_{k} - 48$. Montrer que $(d_{k})$ est géométrique de raison $0{,}75$ et de premier terme $32$.",
              "En déduire $n_{k}$ en fonction de $k$, puis le sens de variation de $(n_{k})$.",
              "Vers quelle valeur la pollution se stabilise-t-elle ?",
              "Au bout de combien d'années la masse passe-t-elle sous $55$ tonnes ?"]],
          sol: [["q", "$n_{1} = 60 + 12 = 72$ et $n_{2} = 54 + 12 = 66$ tonnes.",
            "Il reste $75\\,\\%$ des nitrates, auxquels s'ajoutent $12$ tonnes.",
            "$d_{k+1} = 0{,}75n_{k} + 12 - 48 = 0{,}75(n_{k} - 48) = 0{,}75\\,d_{k}$, et $d_{0} = 32$.",
            "$n_{k} = 48 + 32 \\times 0{,}75^{\\,k}$ : $0{,}75^{\\,k}$ décroît, donc $(n_{k})$ est décroissante.",
            "Elle tend vers $48$ tonnes.",
            "$32 \\times 0{,}75^{\\,k} < 7 \\iff 0{,}75^{\\,k} < 0{,}21875$ ; $0{,}75^{5} \\approx 0{,}237$ et $0{,}75^{6} \\approx 0{,}178$ : au bout de $6$ ans."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 3 — Bac blanc", st: "Fonctions, suites, probabilités, géométrie", h: 3, calc: "autorisée",
      desc: "Quatre exercices indépendants couvrant tout le programme de l'année.",
      ex: [
        {
          t: "QCM (aucune justification n'est demandée)", pts: 4,
          c: ["Pour chaque question, une seule réponse est exacte. Une réponse juste rapporte $1$ point, une réponse fausse n'enlève rien.",
            ["q", "La fonction $f(x) = x\\,\\mathrm{e}^{x}$ a pour dérivée : a) $\\mathrm{e}^{x}$ ; b) $(1+x)\\mathrm{e}^{x}$ ; c) $x\\mathrm{e}^{x-1}$.",
              "La suite $u_{n} = 4 \\times 0{,}8^{\\,n}$ est : a) arithmétique ; b) géométrique croissante ; c) géométrique décroissante.",
              "Si $P(A) = 0{,}4$, $P(B) = 0{,}5$ et $A$, $B$ indépendants, alors $P(A \\cap B)$ vaut : a) $0{,}9$ ; b) $0{,}2$ ; c) $0{,}1$.",
              "Le cercle d'équation $(x-1)^{2} + (y+3)^{2} = 16$ a pour rayon : a) $16$ ; b) $8$ ; c) $4$."]],
          sol: [["q", "b) $(1+x)\\mathrm{e}^{x}$.", "c) géométrique de raison $0{,}8 \\in \\,]0\\,;\\,1[$, donc décroissante.",
            "b) $0{,}4 \\times 0{,}5 = 0{,}2$.", "c) $4$."]],
        },
        {
          t: "Le parc éolien", pts: 6,
          c: ["La puissance d'une éolienne, en kW, en fonction de la vitesse du vent $v$ (en m·s$^{-1}$), est modélisée pour $v \\in [3\\,;\\,15]$ par $P(v) = -0{,}5v^{3} + 15v^{2}$.",
            ["q", "Calculer $P(10)$.",
              "Montrer que $P'(v) = -1{,}5v(v - 20)$.",
              "Étudier le signe de $P'(v)$ sur $[3\\,;\\,15]$ et en déduire les variations de $P$.",
              "Quelle est la puissance maximale sur cet intervalle ?"]],
          sol: [["q", "$P(10) = -500 + 1500 = 1000$ kW.",
            "$P'(v) = -1{,}5v^{2} + 30v = -1{,}5v(v - 20)$.",
            "Sur $[3\\,;\\,15]$, $v > 0$ et $v - 20 < 0$ : $P'(v) > 0$, donc $P$ est croissante.",
            "Le maximum est $P(15) = -1687{,}5 + 3375 = 1687{,}5$ kW."]],
        },
        {
          t: "Le club de robotique", pts: 6,
          c: ["Dans un club, $40\\,\\%$ des membres sont en première. Parmi les élèves de première, $75\\,\\%$ participent à la compétition ; parmi les autres, $50\\,\\%$ y participent. On choisit un membre au hasard.",
            ["q", "Représenter la situation par un arbre pondéré.",
              "Calculer la probabilité que le membre soit en première et participe à la compétition.",
              "Montrer que la probabilité qu'il participe à la compétition est $0{,}6$.",
              "Sachant qu'il participe, quelle est la probabilité qu'il soit en première ?",
              "On interroge $5$ membres au hasard et de façon indépendante. Quelle est la probabilité qu'exactement $3$ participent à la compétition ?"]],
          sol: [["q", "$P(A) = 0{,}4$ pour « être en première », puis $0{,}75$ et $0{,}5$ pour « participer ».",
            "$0{,}4 \\times 0{,}75 = 0{,}3$.",
            "$P(C) = 0{,}3 + 0{,}6 \\times 0{,}5 = 0{,}3 + 0{,}3 = 0{,}6$.",
            "$P_{C}(A) = \\dfrac{0{,}3}{0{,}6} = 0{,}5$.",
            "$X \\sim \\mathcal{B}(5\\,;\\,0{,}6)$ et $P(X=3) = \\binom{5}{3}0{,}6^{3}0{,}4^{2} = 10 \\times 0{,}216 \\times 0{,}16 = 0{,}3456$."]],
        },
        {
          t: "Le terrain triangulaire", pts: 4,
          c: ["Dans un repère orthonormé (unité : $10$ m), un terrain a pour sommets $A(0\\,;\\,0)$, $B(8\\,;\\,2)$ et $C(3\\,;\\,7)$.",
            ["q", "Calculer $\\vec{AB} \\cdot \\vec{AC}$.",
              "Calculer les longueurs $AB$ et $AC$, puis une valeur approchée de l'angle $\\widehat{BAC}$ en degrés.",
              "Déterminer une équation cartésienne de la droite $(BC)$.",
              "Calculer l'aire du terrain, en m$^{2}$."]],
          sol: [["q", "$\\vec{AB}(8\\,;\\,2)$, $\\vec{AC}(3\\,;\\,7)$ : $24 + 14 = 38$.",
            "$AB = \\sqrt{68}$, $AC = \\sqrt{58}$, $\\cos(\\widehat{BAC}) = \\dfrac{38}{\\sqrt{68 \\times 58}} \\approx 0{,}605$, soit environ $52{,}8^{\\circ}$.",
            "$\\vec{BC}(-5\\,;\\,5)$ : la droite a pour équation $x + y - 10 = 0$.",
            "$\\mathcal{A} = \\tfrac{1}{2}|8 \\times 7 - 2 \\times 3| = 25$ unités d'aire, soit $25 \\times 100 = 2\\,500$ m$^{2}$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 4 — Trigonométrie et géométrie", st: "Cercle trigonométrique, produit scalaire, repérage", h: 2, calc: "autorisée",
      desc: "Un marégraphe, un triangle à résoudre et une trajectoire circulaire.",
      ex: [
        {
          t: "Autour du cercle trigonométrique", pts: 6,
          c: [["q", "Donner la mesure principale de $\\dfrac{37\\pi}{6}$.",
            "Calculer la valeur exacte de $\\cos\\!\\left(\\dfrac{2\\pi}{3}\\right) + \\sin\\!\\left(\\dfrac{7\\pi}{6}\\right)$.",
            "Simplifier $\\cos(\\pi - x) - \\sin\\!\\left(\\dfrac{\\pi}{2} - x\\right)$.",
            "Résoudre $2\\sin x = 1$ sur $]-\\pi\\,;\\,\\pi]$."]],
          sol: [["q", "$\\tfrac{37\\pi}{6} = \\tfrac{\\pi}{6} + 6\\pi$ : la mesure principale est $\\tfrac{\\pi}{6}$.",
            "$-\\tfrac{1}{2} + \\left(-\\tfrac{1}{2}\\right) = -1$.",
            "$-\\cos x - \\cos x = -2\\cos x$.",
            "$\\sin x = \\tfrac{1}{2}$ : $x = \\tfrac{\\pi}{6}$ ou $x = \\tfrac{5\\pi}{6}$."]],
        },
        {
          t: "La marée", pts: 7,
          c: ["La hauteur d'eau dans un port, en mètres, $t$ heures après minuit, est modélisée par",
            ["$", "h(t) = 5 + 3\\sin\\!\\left(\\frac{\\pi t}{6}\\right), \\qquad t \\in [0\\,;\\,24]."],
            ["q", "Calculer la hauteur d'eau à minuit et à $3$ h.",
              "Quelle est la hauteur maximale ? À quels instants est-elle atteinte ?",
              "Quelle est la période de ce phénomène ? Interpréter.",
              "Un bateau ne peut entrer que si la hauteur dépasse $6{,}5$ m. Résoudre $h(t) > 6{,}5$ sur $[0\\,;\\,12]$."]],
          sol: [["q", "$h(0) = 5$ m et $h(3) = 5 + 3 = 8$ m.",
            "Maximum $8$ m lorsque $\\sin\\!\\left(\\tfrac{\\pi t}{6}\\right) = 1$, soit $t = 3$ h et $t = 15$ h.",
            "La période est $\\dfrac{2\\pi}{\\pi/6} = 12$ h : la marée se reproduit toutes les $12$ heures.",
            "$\\sin\\!\\left(\\tfrac{\\pi t}{6}\\right) > 0{,}5 \\iff \\tfrac{\\pi}{6} < \\tfrac{\\pi t}{6} < \\tfrac{5\\pi}{6} \\iff 1 < t < 5$."]],
        },
        {
          t: "Le quadrilatère du voilier", pts: 7,
          c: ["Dans un repère orthonormé, $A(1\\,;\\,1)$, $B(5\\,;\\,3)$, $C(4\\,;\\,6)$ et $D(0\\,;\\,4)$.",
            ["q", "Montrer que $ABCD$ est un parallélogramme.",
              "Calculer $\\vec{AB} \\cdot \\vec{AD}$. Le parallélogramme est-il un rectangle ?",
              "Calculer $AB$ et $AD$, puis une valeur approchée de l'angle $\\widehat{BAD}$ en degrés.",
              "Déterminer les coordonnées du centre $I$ du parallélogramme, puis son aire."]],
          sol: [["q", "$\\vec{AB}(4\\,;\\,2)$ et $\\vec{DC}(4\\,;\\,2)$ sont égaux : $ABCD$ est un parallélogramme.",
            "$\\vec{AD}(-1\\,;\\,3)$ donc $\\vec{AB} \\cdot \\vec{AD} = -4 + 6 = 2 \\neq 0$ : les côtés ne sont pas perpendiculaires, ce n'est pas un rectangle.",
            "$AB = \\sqrt{20} = 2\\sqrt{5}$, $AD = \\sqrt{10}$, $\\cos(\\widehat{BAD}) = \\dfrac{2}{\\sqrt{200}} \\approx 0{,}141$, soit environ $81{,}9^{\\circ}$.",
            "$I$ est le milieu de $[AC]$ : $I(2{,}5\\,;\\,3{,}5)$. L'aire vaut $|4 \\times 3 - 2 \\times (-1)| = 14$ unités d'aire."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 5 — Grand devoir de fin d'année", st: "Synthèse : fonctions, exponentielle, suites, probabilités, géométrie", h: 3, calc: "autorisée",
      desc: "Cinq exercices pour réviser toute l'année, dans l'esprit du bac.",
      ex: [
        {
          t: "Vrai ou faux (justifier)", pts: 4,
          c: [["q", "Si $\\Delta < 0$, le trinôme $ax^{2}+bx+c$ ne change jamais de signe.",
            "La suite définie par $u_{n} = n^{2}$ est arithmétique.",
            "Pour tout réel $x$, $\\mathrm{e}^{x} > 0$.",
            "Deux vecteurs orthogonaux ont un produit scalaire égal à $1$."]],
          sol: [["q", "Vrai : le trinôme garde le signe de $a$ sur $\\mathbb{R}$.",
            "Faux : $u_{1} - u_{0} = 1$ mais $u_{2} - u_{1} = 3$ : les différences ne sont pas constantes.",
            "Vrai : l'exponentielle est strictement positive sur $\\mathbb{R}$.",
            "Faux : leur produit scalaire est nul."]],
        },
        {
          t: "La tasse et le thermomètre", pts: 5,
          c: ["La température d'un thé, en °C, $t$ minutes après le service, est $T(t) = 18 + 72\\,\\mathrm{e}^{-0{,}08t}$.",
            ["q", "Quelle est la température initiale ?",
              "Calculer $T(15)$, arrondi au dixième.",
              "Calculer $T'(t)$ et justifier que $T$ est décroissante.",
              "On boit le thé lorsqu'il est à $55$ °C environ. Déterminer, par balayage à la calculatrice, l'instant correspondant (au dixième de minute)."]],
          sol: [["q", "$T(0) = 90$ °C.",
            "$T(15) = 18 + 72\\mathrm{e}^{-1{,}2} \\approx 39{,}7$ °C.",
            "$T'(t) = -5{,}76\\,\\mathrm{e}^{-0{,}08t} < 0$ : la température décroît.",
            "$72\\mathrm{e}^{-0{,}08t} = 37 \\iff \\mathrm{e}^{-0{,}08t} \\approx 0{,}5139$ ; par balayage $t \\approx 8{,}3$ min."]],
        },
        {
          t: "Le prêt étudiant", pts: 5,
          c: ["Un étudiant emprunte $6\\,000$ €. Chaque mois, la banque ajoute $0{,}4\\,\\%$ d'intérêts au capital restant dû, puis l'étudiant rembourse $200$ €. On note $c_{n}$ le capital restant dû après $n$ mois.",
            ["q", "Justifier que $c_{n+1} = 1{,}004\\,c_{n} - 200$ et calculer $c_{1}$.",
              "On pose $e_{n} = c_{n} - 50000$. Montrer que $(e_{n})$ est géométrique de raison $1{,}004$.",
              "Exprimer $c_{n}$ en fonction de $n$.",
              "À l'aide de la calculatrice, déterminer le nombre de mensualités nécessaires pour solder le prêt."]],
          sol: [["q", "Le capital est multiplié par $1{,}004$ puis diminué de $200$ : $c_{1} = 6024 - 200 = 5824$ €.",
            "$e_{n+1} = 1{,}004c_{n} - 200 - 50000 = 1{,}004(c_{n} - 50000) = 1{,}004\\,e_{n}$ car $1{,}004 \\times 50000 = 50200$.",
            "$e_{0} = -44000$ donc $c_{n} = 50000 - 44000 \\times 1{,}004^{\\,n}$.",
            "$c_{32} \\approx 25$ € et $c_{33} < 0$ : $33$ mensualités suffisent (la dernière étant réduite)."]],
        },
        {
          t: "Le jeu des trois urnes", pts: 6,
          c: ["Trois urnes contiennent des jetons : $U_{1}$ ($3$ blancs, $2$ noirs), $U_{2}$ ($1$ blanc, $4$ noirs), $U_{3}$ ($5$ blancs). On choisit une urne au hasard, puis on y tire un jeton.",
            ["q", "Représenter la situation par un arbre.",
              "Calculer la probabilité de tirer un jeton blanc.",
              "Sachant que le jeton est blanc, quelle est la probabilité qu'il vienne de $U_{3}$ ?",
              "On répète l'expérience $4$ fois de façon indépendante (en remettant le jeton). Quelle est la probabilité d'obtenir exactement $2$ jetons blancs ?"]],
          sol: [["q", "Chaque urne a la probabilité $\\tfrac{1}{3}$, puis $P(B) = \\tfrac{3}{5}$, $\\tfrac{1}{5}$ et $1$.",
            "$P(B) = \\tfrac{1}{3}\\left(\\tfrac{3}{5} + \\tfrac{1}{5} + 1\\right) = \\tfrac{1}{3} \\times \\tfrac{9}{5} = \\tfrac{3}{5} = 0{,}6$.",
            "$P_{B}(U_{3}) = \\dfrac{1/3}{3/5} = \\dfrac{5}{9} \\approx 0{,}556$.",
            "$X \\sim \\mathcal{B}(4\\,;\\,0{,}6)$ : $P(X=2) = 6 \\times 0{,}36 \\times 0{,}16 = 0{,}3456$."]],
        },
        {
          t: "La passerelle", pts: 5,
          c: ["Dans un repère orthonormé (unité : le mètre), une passerelle relie $A(0\\,;\\,4)$ à $B(12\\,;\\,10)$. Un pilier est planté en $P(6\\,;\\,0)$.",
            ["q", "Déterminer une équation cartésienne de la droite $(AB)$.",
              "Calculer la distance du pilier à la passerelle à l'aide de la formule $d = \\dfrac{|ax_{P} + by_{P} + c|}{\\sqrt{a^{2}+b^{2}}}$.",
              "Le câble de sécurité doit relier $P$ au point de $(AB)$ le plus proche. Quelle est sa longueur, arrondie au décimètre ?",
              "Calculer $\\vec{PA} \\cdot \\vec{PB}$ et en déduire si l'angle $\\widehat{APB}$ est aigu ou obtus."]],
          sol: [["q", "$\\vec{AB}(12\\,;\\,6)$, soit un vecteur normal $(6\\,;\\,-12)$ : $x - 2y + 8 = 0$.",
            "$d = \\dfrac{|6 - 0 + 8|}{\\sqrt{1 + 4}} = \\dfrac{14}{\\sqrt{5}} \\approx 6{,}26$ m.",
            "Le câble mesure la distance calculée, soit environ $6{,}3$ m.",
            "$\\vec{PA}(-6\\,;\\,4)$ et $\\vec{PB}(6\\,;\\,10)$ : $-36 + 40 = 4 > 0$, l'angle est aigu."]],
        },
      ],
    },
  ]);
})();
