/* Banque — Prépa première année (MPSI · PCSI · MP2I · PTSI) */
(function () {

  L.addSujets("sup", "fiche", [
    {
      t: "Fiche 1 — Logique, ensembles et sommes", st: "Quantificateurs, récurrence, manipulations de sommes", diff: "★★",
      desc: "Les réflexes de rédaction du premier trimestre : quantificateurs, récurrences, télescopages.",
      intro: "Une démonstration de prépa se juge autant sur la rigueur des quantificateurs que sur le résultat.",
      ex: [
        {
          t: "Quantificateurs",
          c: ["Écrire la négation des assertions suivantes, puis dire si elles sont vraies :",
            ["q", "$\\forall x \\in \\mathbb{R},\\ \\exists y \\in \\mathbb{R},\\ x + y = 0$",
              "$\\exists y \\in \\mathbb{R},\\ \\forall x \\in \\mathbb{R},\\ x + y = 0$",
              "$\\forall \\varepsilon > 0,\\ \\exists N \\in \\mathbb{N},\\ \\forall n \\geqslant N,\\ \\dfrac{1}{n+1} < \\varepsilon$",
              "$\\forall x \\in \\mathbb{R},\\ x^{2} \\geqslant x$"]],
          sol: [["q", "Négation : $\\exists x,\\ \\forall y,\\ x+y \\neq 0$. L'assertion est vraie ($y = -x$).",
            "Négation : $\\forall y,\\ \\exists x,\\ x+y \\neq 0$. L'assertion est fausse (un tel $y$ devrait convenir pour tout $x$).",
            "Négation : $\\exists \\varepsilon > 0,\\ \\forall N,\\ \\exists n \\geqslant N,\\ \\tfrac{1}{n+1} \\geqslant \\varepsilon$. L'assertion est vraie : c'est la convergence de $\\tfrac{1}{n+1}$ vers $0$.",
            "Négation : $\\exists x,\\ x^{2} < x$. L'assertion est fausse : pour $x = \\tfrac{1}{2}$, $x^{2} = \\tfrac{1}{4} < \\tfrac{1}{2}$."]],
        },
        {
          t: "Sommes classiques",
          c: ["Calculer, pour $n \\in \\mathbb{N}^{*}$ :",
            ["q", "$\\displaystyle\\sum_{k=1}^{n} (2k - 1)$", "$\\displaystyle\\sum_{k=1}^{n} \\frac{1}{k(k+1)}$",
              "$\\displaystyle\\sum_{k=0}^{n} \\binom{n}{k}$ et $\\displaystyle\\sum_{k=0}^{n} (-1)^{k}\\binom{n}{k}$",
              "$\\displaystyle\\sum_{k=1}^{n} k\\,2^{\\,k}$ (on dérivera une somme géométrique)"]],
          sol: [["q", "$2\\dfrac{n(n+1)}{2} - n = n^{2}$.",
            "Télescopage : $\\dfrac{1}{k} - \\dfrac{1}{k+1}$, la somme vaut $1 - \\dfrac{1}{n+1} = \\dfrac{n}{n+1}$.",
            "$2^{\\,n}$ et $0$ (formule du binôme avec $(1+1)^{n}$ et $(1-1)^{n}$).",
            "En dérivant $\\displaystyle\\sum_{k=0}^{n} x^{k} = \\dfrac{x^{n+1}-1}{x-1}$ puis en évaluant en $2$ : $\\displaystyle\\sum_{k=1}^{n}k2^{k} = (n-1)2^{\\,n+1} + 2$."]],
        },
        {
          t: "Récurrences",
          c: [["q", "Montrer que pour tout $n \\geqslant 1$, $\\displaystyle\\sum_{k=1}^{n} k^{3} = \\left(\\frac{n(n+1)}{2}\\right)^{2}$.",
            "Soit $(u_{n})$ définie par $u_{0} = 2$ et $u_{n+1} = 2u_{n} - 1$. Conjecturer puis démontrer une expression de $u_{n}$.",
            "Montrer par récurrence forte que tout entier $n \\geqslant 2$ admet un diviseur premier."]],
          sol: [["q", "Hérédité : $\\left(\\tfrac{n(n+1)}{2}\\right)^{2} + (n+1)^{3} = \\tfrac{(n+1)^{2}}{4}\\big(n^{2} + 4n + 4\\big) = \\left(\\tfrac{(n+1)(n+2)}{2}\\right)^{2}$.",
            "$u_{n} = 2^{\\,n} + 1$ : vrai pour $n=0$, et $2(2^{n}+1) - 1 = 2^{n+1}+1$.",
            "Si $n$ est premier, il se divise lui-même. Sinon $n = ab$ avec $2 \\leqslant a < n$, et par hypothèse de récurrence forte $a$ admet un diviseur premier, qui divise $n$."]],
        },
        {
          t: "Ensembles et applications",
          c: ["Soit $f : \\mathbb{R} \\to \\mathbb{R}$, $f(x) = \\dfrac{x}{1+x^{2}}$.",
            ["q", "$f$ est-elle injective ? Surjective ?",
              "Déterminer $f(\\mathbb{R})$.",
              "Montrer que $f$ induit une bijection de $[-1\\,;\\,1]$ sur un intervalle à préciser.",
              "Soient $A, B$ des parties d'un ensemble $E$. Montrer que $\\overline{A \\cup B} = \\overline{A} \\cap \\overline{B}$."]],
          sol: [["q", "Non injective : $f(2) = f\\!\\left(\\tfrac{1}{2}\\right) = \\tfrac{2}{5}$. Non surjective : $f$ est bornée.",
            "$f'(x) = \\dfrac{1-x^{2}}{(1+x^{2})^{2}}$ : maximum $f(1) = \\tfrac{1}{2}$, minimum $f(-1) = -\\tfrac{1}{2}$, et $f \\to 0$ en $\\pm\\infty$ : $f(\\mathbb{R}) = \\left[-\\tfrac{1}{2}\\,;\\,\\tfrac{1}{2}\\right]$.",
            "Sur $[-1\\,;\\,1]$, $f' \\geqslant 0$ : $f$ est continue strictement croissante, donc bijective de $[-1\\,;\\,1]$ sur $\\left[-\\tfrac{1}{2}\\,;\\,\\tfrac{1}{2}\\right]$.",
            "$x \\notin A \\cup B \\iff (x \\notin A$ et $x \\notin B)$ : c'est exactement la définition de $\\overline{A} \\cap \\overline{B}$."]],
        },
      ],
    },
    {
      t: "Fiche 2 — Nombres complexes", st: "Module, argument, racines n-ièmes, géométrie", diff: "★★",
      desc: "Forme exponentielle, racines de l'unité et transformations du plan.",
      ex: [
        {
          t: "Formes et calculs",
          c: [["q", "Écrire sous forme exponentielle $z_{1} = 1 + \\mathrm{i}\\sqrt{3}$ et $z_{2} = -1 + \\mathrm{i}$.",
            "En déduire le module et un argument de $\\dfrac{z_{1}}{z_{2}}$.",
            "Calculer $z_{1}^{6}$.",
            "Linéariser $\\cos^{3}\\theta$ à l'aide des formules d'Euler."]],
          sol: [["q", "$z_{1} = 2\\mathrm{e}^{\\mathrm{i}\\pi/3}$ et $z_{2} = \\sqrt{2}\\,\\mathrm{e}^{3\\mathrm{i}\\pi/4}$.",
            "$\\left|\\dfrac{z_{1}}{z_{2}}\\right| = \\sqrt{2}$ et $\\arg = \\dfrac{\\pi}{3} - \\dfrac{3\\pi}{4} = -\\dfrac{5\\pi}{12}$.",
            "$z_{1}^{6} = 2^{6}\\mathrm{e}^{2\\mathrm{i}\\pi} = 64$.",
            "$\\cos^{3}\\theta = \\dfrac{3\\cos\\theta + \\cos 3\\theta}{4}$."]],
        },
        {
          t: "Racines de l'unité",
          c: [["q", "Résoudre $z^{4} = 1$ puis $z^{3} = 8\\mathrm{i}$.",
            "Montrer que la somme des racines $n$-ièmes de l'unité est nulle pour $n \\geqslant 2$.",
            "Soit $\\omega = \\mathrm{e}^{2\\mathrm{i}\\pi/5}$. Calculer $1 + \\omega + \\omega^{2} + \\omega^{3} + \\omega^{4}$.",
            "Résoudre $z^{2} - (3+\\mathrm{i})z + 4 + 3\\mathrm{i} = 0$."]],
          sol: [["q", "$z \\in \\{1, \\mathrm{i}, -1, -\\mathrm{i}\\}$ ; $8\\mathrm{i} = 8\\mathrm{e}^{\\mathrm{i}\\pi/2}$ donc $z = 2\\mathrm{e}^{\\mathrm{i}(\\pi/6 + 2k\\pi/3)}$, $k \\in \\{0,1,2\\}$.",
            "Somme géométrique de raison $\\mathrm{e}^{2\\mathrm{i}\\pi/n} \\neq 1$ : $\\dfrac{1 - \\mathrm{e}^{2\\mathrm{i}\\pi}}{1 - \\mathrm{e}^{2\\mathrm{i}\\pi/n}} = 0$.",
            "$0$, d'après la question précédente.",
            "$\\Delta = (3+\\mathrm{i})^{2} - 4(4+3\\mathrm{i}) = 8 + 6\\mathrm{i} - 16 - 12\\mathrm{i} = -8 - 6\\mathrm{i} = (1 - 3\\mathrm{i})^{2}$, d'où $z = \\dfrac{3+\\mathrm{i} \\pm (1-3\\mathrm{i})}{2}$, soit $z = 2 - \\mathrm{i}$ ou $z = 1 + 2\\mathrm{i}$."]],
        },
        {
          t: "Géométrie complexe",
          c: ["Le plan est rapporté à un repère orthonormé direct. À tout point $M$ d'affixe $z \\neq 1$ on associe $Z = \\dfrac{z + 1}{z - 1}$.",
            ["q", "Déterminer l'ensemble des points $M$ tels que $Z$ soit réel.",
              "Déterminer l'ensemble des points $M$ tels que $|Z| = 1$.",
              "Déterminer l'ensemble des points $M$ tels que $Z$ soit imaginaire pur."]],
          sol: [["q", "$Z \\in \\mathbb{R} \\iff \\arg\\dfrac{z-(-1)}{z-1} \\equiv 0\\ [\\pi]$ : les points $M$ alignés avec $A(-1)$ et $B(1)$, soit la droite $(AB)$ privée de $B$ (l'axe réel).",
            "$|z+1| = |z-1| \\iff MA = MB$ : la médiatrice de $[AB]$, c'est-à-dire l'axe des imaginaires purs.",
            "$Z$ imaginaire pur $\\iff \\arg \\equiv \\tfrac{\\pi}{2}\\ [\\pi]$ : le cercle de diamètre $[AB]$ privé de $A$ et $B$, soit le cercle unité."]],
        },
        {
          t: "Trigonométrie et somme",
          c: ["Soit $\\theta \\in \\,]0\\,;\\,2\\pi[$ et $n \\in \\mathbb{N}$.",
            ["q", "Calculer $S = \\displaystyle\\sum_{k=0}^{n} \\mathrm{e}^{\\mathrm{i}k\\theta}$.",
              "En déduire $\\displaystyle\\sum_{k=0}^{n}\\cos(k\\theta)$ à l'aide de la technique de l'angle moitié.",
              "Application : calculer $\\displaystyle\\sum_{k=0}^{5}\\cos\\!\\left(\\frac{k\\pi}{3}\\right)$."]],
          sol: [["q", "$S = \\dfrac{1 - \\mathrm{e}^{\\mathrm{i}(n+1)\\theta}}{1 - \\mathrm{e}^{\\mathrm{i}\\theta}}$.",
            "En factorisant par l'angle moitié : $S = \\mathrm{e}^{\\mathrm{i}n\\theta/2}\\dfrac{\\sin\\!\\left(\\tfrac{(n+1)\\theta}{2}\\right)}{\\sin\\!\\left(\\tfrac{\\theta}{2}\\right)}$, d'où $\\displaystyle\\sum\\cos(k\\theta) = \\cos\\!\\left(\\tfrac{n\\theta}{2}\\right)\\dfrac{\\sin\\!\\left(\\tfrac{(n+1)\\theta}{2}\\right)}{\\sin\\!\\left(\\tfrac{\\theta}{2}\\right)}$.",
            "Avec $\\theta = \\tfrac{\\pi}{3}$ et $n = 5$ : $\\sin(\\pi) = 0$, la somme vaut $0$ (ce sont les six racines sixièmes de l'unité)."]],
        },
      ],
    },
    {
      t: "Fiche 3 — Suites réelles", st: "Convergence, suites adjacentes, récurrentes, Cesàro", diff: "★★★",
      desc: "Les grands classiques de l'analyse de première année.",
      ex: [
        {
          t: "Convergences",
          c: ["Étudier la convergence des suites suivantes :",
            ["q", "$u_{n} = \\dfrac{n + (-1)^{n}\\sqrt{n}}{n+1}$", "$v_{n} = \\left(1 + \\dfrac{1}{n}\\right)^{n}$",
              "$w_{n} = \\dfrac{n!}{n^{\\,n}}$", "$t_{n} = \\displaystyle\\sum_{k=1}^{n}\\frac{1}{k^{2}}$"]],
          sol: [["q", "$u_{n} = \\dfrac{1 + (-1)^{n}/\\sqrt{n}}{1 + 1/n} \\to 1$.",
            "$v_{n} = \\exp\\!\\left(n\\ln\\!\\left(1+\\tfrac{1}{n}\\right)\\right) \\to \\mathrm{e}$.",
            "$0 < w_{n} \\leqslant \\dfrac{1}{n}$ (tous les facteurs sauf un sont $\\leqslant 1$) : $w_{n} \\to 0$.",
            "Croissante et majorée : $t_{n} \\leqslant 1 + \\displaystyle\\sum_{k\\geqslant 2}\\dfrac{1}{k(k-1)} \\leqslant 2$, donc convergente (vers $\\tfrac{\\pi^{2}}{6}$)."]],
        },
        {
          t: "Suites adjacentes",
          c: ["On pose $u_{n} = \\displaystyle\\sum_{k=0}^{n}\\frac{1}{k!}$ et $v_{n} = u_{n} + \\frac{1}{n\\,n!}$ pour $n \\geqslant 1$.",
            ["q", "Montrer que $(u_{n})$ est croissante et $(v_{n})$ décroissante.",
              "Montrer que $v_{n} - u_{n} \\to 0$ et conclure.",
              "En déduire un encadrement de $\\mathrm{e}$ pour $n = 4$.",
              "Montrer que $\\mathrm{e}$ est irrationnel (on raisonnera par l'absurde avec $\\mathrm{e} = p/q$)."]],
          sol: [["q", "$u_{n+1} - u_{n} = \\tfrac{1}{(n+1)!} > 0$ ; un calcul donne $v_{n+1} - v_{n} = \\dfrac{-1}{n(n+1)(n+1)!} < 0$.",
            "$v_{n} - u_{n} = \\tfrac{1}{n\\,n!} \\to 0$ : les suites sont adjacentes, donc convergent vers la même limite, qui est $\\mathrm{e}$.",
            "$u_{4} = \\tfrac{65}{24} \\approx 2{,}7083$ et $v_{4} = u_{4} + \\tfrac{1}{96} \\approx 2{,}7187$.",
            "Si $\\mathrm{e} = p/q$, l'encadrement $u_{q} < \\mathrm{e} < v_{q}$ multiplié par $q\\,q!$ place l'entier $q\\,q!\\,\\mathrm{e}$ strictement entre deux entiers consécutifs : absurde."]],
        },
        {
          t: "Suite récurrente",
          c: ["Soit $u_{0} \\in [0\\,;\\,1]$ et $u_{n+1} = u_{n}(1 - u_{n})$.",
            ["q", "Montrer que $u_{n} \\in [0\\,;\\,1]$ pour tout $n$ (on étudiera $x \\mapsto x(1-x)$ sur $[0\\,;\\,1]$).",
              "Montrer que $(u_{n})$ est décroissante.",
              "En déduire qu'elle converge et déterminer sa limite.",
              "Étudier la nature de la série $\\sum u_{n}^{2}$ (on remarquera que $u_{n}^{2} = u_{n} - u_{n+1}$)."]],
          sol: [["q", "Sur $[0\\,;\\,1]$, $x(1-x) \\in \\left[0\\,;\\,\\tfrac{1}{4}\\right] \\subset [0\\,;\\,1]$ : l'intervalle est stable.",
            "$u_{n+1} - u_{n} = -u_{n}^{2} \\leqslant 0$.",
            "Décroissante et minorée par $0$ : elle converge vers $\\ell$ vérifiant $\\ell = \\ell(1-\\ell)$, soit $\\ell = 0$.",
            "$\\displaystyle\\sum_{k=0}^{n}u_{k}^{2} = u_{0} - u_{n+1} \\to u_{0}$ : la série converge et sa somme vaut $u_{0}$."]],
        },
        {
          t: "Théorème de Cesàro",
          c: ["Soit $(u_{n})$ une suite réelle convergeant vers $\\ell$, et $c_{n} = \\dfrac{1}{n}\\displaystyle\\sum_{k=1}^{n}u_{k}$.",
            ["q", "Démontrer que $c_{n} \\to \\ell$ (découpage de la somme en deux).",
              "La réciproque est-elle vraie ? Donner un contre-exemple.",
              "Application : si $u_{n+1} - u_{n} \\to a$, montrer que $\\dfrac{u_{n}}{n} \\to a$."]],
          sol: [["q", "Soit $\\varepsilon > 0$ et $N$ tel que $|u_{k} - \\ell| < \\tfrac{\\varepsilon}{2}$ pour $k \\geqslant N$. On coupe la somme en $k < N$ (terme majoré par $\\tfrac{C}{n} \\to 0$) et $k \\geqslant N$ (majoré par $\\tfrac{\\varepsilon}{2}$).",
            "Non : $u_{n} = (-1)^{n}$ diverge alors que $c_{n} \\to 0$.",
            "On applique Cesàro à $v_{n} = u_{n} - u_{n-1}$ : la moyenne des $v_{k}$ vaut $\\dfrac{u_{n} - u_{0}}{n} \\to a$."]],
        },
      ],
    },
    {
      t: "Fiche 4 — Fonctions usuelles", st: "arctan, fonctions hyperboliques, équations fonctionnelles", diff: "★★",
      desc: "Les fonctions du programme et les identités à connaître par cœur.",
      ex: [
        {
          t: "Autour d'arctan",
          c: [["q", "Simplifier $\\arctan x + \\arctan\\dfrac{1}{x}$ pour $x > 0$, puis pour $x < 0$.",
            "Montrer que $\\arctan\\dfrac{1}{2} + \\arctan\\dfrac{1}{3} = \\dfrac{\\pi}{4}$.",
            "Résoudre $\\arctan(x) + \\arctan(2x) = \\dfrac{\\pi}{4}$.",
            "Calculer $\\displaystyle\\lim_{x\\to+\\infty} x\\left(\\frac{\\pi}{2} - \\arctan x\\right)$."]],
          sol: [["q", "$\\tfrac{\\pi}{2}$ si $x > 0$ et $-\\tfrac{\\pi}{2}$ si $x < 0$ (dériver : la somme est constante sur chaque intervalle).",
            "$\\tan$ de la somme $= \\dfrac{\\tfrac{1}{2}+\\tfrac{1}{3}}{1 - \\tfrac{1}{6}} = 1$, et la somme est dans $\\left]0\\,;\\,\\tfrac{\\pi}{2}\\right[$ : elle vaut $\\tfrac{\\pi}{4}$.",
            "$\\dfrac{3x}{1-2x^{2}} = 1$ avec $1-2x^{2} > 0$ : $2x^{2}+3x-1 = 0$, $x = \\dfrac{-3+\\sqrt{17}}{4} \\approx 0{,}281$ (l'autre racine est négative et ne convient pas).",
            "$\\tfrac{\\pi}{2} - \\arctan x = \\arctan\\tfrac{1}{x} \\sim \\tfrac{1}{x}$ : la limite vaut $1$."]],
        },
        {
          t: "Fonctions hyperboliques",
          c: [["q", "Montrer que $\\mathrm{ch}^{2}x - \\mathrm{sh}^{2}x = 1$.",
            "Résoudre $\\mathrm{ch}\\,x = 2$.",
            "Montrer que $\\mathrm{sh}$ est une bijection de $\\mathbb{R}$ sur $\\mathbb{R}$ et exprimer sa réciproque à l'aide de $\\ln$.",
            "Calculer $\\displaystyle\\int_{0}^{1}\\mathrm{sh}(2x)\\,\\mathrm{d}x$."]],
          sol: [["q", "Développer : $\\tfrac{(\\mathrm{e}^{x}+\\mathrm{e}^{-x})^{2} - (\\mathrm{e}^{x}-\\mathrm{e}^{-x})^{2}}{4} = \\tfrac{4}{4} = 1$.",
            "Avec $X = \\mathrm{e}^{x}$ : $X^{2} - 4X + 1 = 0$, $X = 2 \\pm \\sqrt{3}$, donc $x = \\pm\\ln(2+\\sqrt{3})$.",
            "$\\mathrm{sh}' = \\mathrm{ch} > 0$ et les limites sont $\\pm\\infty$ : $\\mathrm{sh}$ est bijective, et $\\mathrm{argsh}\\,y = \\ln\\!\\left(y + \\sqrt{y^{2}+1}\\right)$.",
            "$\\left[\\tfrac{1}{2}\\mathrm{ch}(2x)\\right]_{0}^{1} = \\tfrac{\\mathrm{ch}\\,2 - 1}{2} \\approx 1{,}38$."]],
        },
        {
          t: "Équations fonctionnelles",
          c: [["q", "Déterminer les fonctions continues $f : \\mathbb{R}\\to\\mathbb{R}$ telles que $f(x+y) = f(x)+f(y)$.",
            "Déterminer les fonctions dérivables telles que $f' = f$ et $f(0) = 3$.",
            "Soit $f$ continue sur $\\mathbb{R}$ telle que $f(x)^{2} = 1$ pour tout $x$. Montrer que $f$ est constante."]],
          sol: [["q", "On obtient $f(qx) = qf(x)$ pour $q$ rationnel, puis par densité de $\\mathbb{Q}$ et continuité $f(x) = ax$ avec $a = f(1)$.",
            "$\\left(f(x)\\mathrm{e}^{-x}\\right)' = 0$ donc $f(x) = C\\mathrm{e}^{x}$, et $f(0) = 3$ donne $f(x) = 3\\mathrm{e}^{x}$.",
            "$f$ ne prend que les valeurs $\\pm 1$ ; par le TVI, si elle prenait les deux, elle prendrait $0$ : contradiction."]],
        },
        {
          t: "Étude complète",
          c: ["Soit $f(x) = x^{\\,x}$ définie pour $x > 0$.",
            ["q", "Justifier que $f(x) = \\mathrm{e}^{x\\ln x}$ et calculer $\\displaystyle\\lim_{x\\to 0^{+}} f(x)$.",
              "Calculer $f'(x)$ et dresser le tableau de variations.",
              "Déterminer le minimum de $f$.",
              "Déterminer $\\displaystyle\\lim_{x\\to+\\infty} \\frac{\\ln f(x)}{x}$."]],
          sol: [["q", "$x\\ln x \\to 0$ donc $f(x) \\to 1$.",
            "$f'(x) = (\\ln x + 1)\\mathrm{e}^{x\\ln x}$ : décroissante sur $\\left]0\\,;\\,\\tfrac{1}{\\mathrm{e}}\\right]$, croissante ensuite.",
            "$f\\!\\left(\\tfrac{1}{\\mathrm{e}}\\right) = \\mathrm{e}^{-1/\\mathrm{e}} \\approx 0{,}6922$.",
            "$\\dfrac{x\\ln x}{x} = \\ln x \\to +\\infty$."]],
        },
      ],
    },
    {
      t: "Fiche 5 — Dérivation et accroissements finis", st: "Rolle, TAF, inégalités, fonctions convexes", diff: "★★★",
      desc: "Les théorèmes globaux de la dérivation et leurs applications aux inégalités.",
      ex: [
        {
          t: "Théorème de Rolle",
          c: [["q", "Soit $P$ un polynôme réel scindé à racines simples. Montrer que $P'$ est scindé.",
            "Soit $f$ dérivable sur $[a\\,;\\,b]$ avec $f(a) = f(b) = 0$. Montrer que pour tout $\\lambda \\in \\mathbb{R}$, il existe $c$ tel que $f'(c) = \\lambda f(c)$ (on posera $g = f\\mathrm{e}^{-\\lambda x}$).",
            "Montrer que l'équation $\\mathrm{e}^{x} = x + 1$ n'a qu'une solution."]],
          sol: [["q", "Entre deux racines consécutives de $P$, Rolle fournit une racine de $P'$ ; on obtient ainsi $\\deg P - 1$ racines distinctes, soit toutes celles de $P'$.",
            "$g$ est dérivable, $g(a) = g(b) = 0$ : Rolle donne $c$ avec $g'(c) = (f'(c) - \\lambda f(c))\\mathrm{e}^{-\\lambda c} = 0$.",
            "$h(x) = \\mathrm{e}^{x} - x - 1$ a pour dérivée $\\mathrm{e}^{x}-1$, qui s'annule une seule fois : $h$ a un minimum nul en $0$, donc $0$ est l'unique solution."]],
        },
        {
          t: "Inégalités des accroissements finis",
          c: [["q", "Montrer que pour tous $a, b$ réels, $|\\sin a - \\sin b| \\leqslant |a - b|$.",
            "Montrer que pour $0 < a < b$, $\\dfrac{b-a}{b} \\leqslant \\ln\\dfrac{b}{a} \\leqslant \\dfrac{b-a}{a}$.",
            "En déduire un encadrement de $\\ln(1{,}1)$."]],
          sol: [["q", "$|\\sin'| = |\\cos| \\leqslant 1$ : l'IAF donne le résultat.",
            "Le TAF appliqué à $\\ln$ sur $[a\\,;\\,b]$ donne $\\ln b - \\ln a = \\dfrac{b-a}{c}$ avec $a < c < b$, d'où l'encadrement.",
            "Avec $a = 1$, $b = 1{,}1$ : $\\tfrac{0{,}1}{1{,}1} \\approx 0{,}0909 \\leqslant \\ln 1{,}1 \\leqslant 0{,}1$."]],
        },
        {
          t: "Convexité",
          c: [["q", "Montrer que pour tout $x > -1$, $\\ln(1+x) \\leqslant x$.",
            "Montrer l'inégalité arithmético-géométrique pour deux réels positifs : $\\sqrt{ab} \\leqslant \\dfrac{a+b}{2}$.",
            "Soit $f$ convexe sur $I$ et $x_{1},\\dots,x_{n} \\in I$. Énoncer l'inégalité de Jensen.",
            "Application : montrer que $\\dfrac{x_{1}+\\dots+x_{n}}{n} \\geqslant \\sqrt[n]{x_{1}\\cdots x_{n}}$ pour des réels strictement positifs."]],
          sol: [["q", "La concavité de $\\ln$ place la courbe sous sa tangente en $0$, d'équation $y = x$.",
            "$\\left(\\sqrt{a}-\\sqrt{b}\\right)^{2} \\geqslant 0$ donne $a + b \\geqslant 2\\sqrt{ab}$.",
            "$f\\!\\left(\\dfrac{1}{n}\\sum x_{i}\\right) \\leqslant \\dfrac{1}{n}\\sum f(x_{i})$.",
            "On applique Jensen à $-\\ln$ (convexe) : $\\ln\\!\\left(\\tfrac{1}{n}\\sum x_{i}\\right) \\geqslant \\tfrac{1}{n}\\sum \\ln x_{i} = \\ln\\sqrt[n]{\\prod x_{i}}$, puis on compose par $\\exp$."]],
        },
        {
          t: "Dérivées successives",
          c: ["Soit $f(x) = \\dfrac{1}{1-x}$ sur $]-\\infty\\,;\\,1[$.",
            ["q", "Calculer $f^{(n)}(x)$ pour tout $n$.",
              "En déduire le développement de Taylor de $f$ en $0$ à l'ordre $n$.",
              "Calculer la dérivée $n$-ième de $x \\mapsto x^{2}\\mathrm{e}^{x}$ (formule de Leibniz)."]],
          sol: [["q", "$f^{(n)}(x) = \\dfrac{n!}{(1-x)^{n+1}}$ (récurrence immédiate).",
            "$f(x) = 1 + x + x^{2} + \\dots + x^{n} + o(x^{n})$.",
            "Leibniz : $\\left(x^{2}\\mathrm{e}^{x}\\right)^{(n)} = \\mathrm{e}^{x}\\left(x^{2} + 2nx + n(n-1)\\right)$."]],
        },
      ],
    },
    {
      t: "Fiche 6 — Développements limités", st: "Formules de Taylor, équivalents, limites, asymptotes", diff: "★★★",
      desc: "Calculer un DL proprement, et s'en servir pour lever une indétermination.",
      ex: [
        {
          t: "DL usuels",
          c: ["Donner le développement limité en $0$ à l'ordre $4$ de :",
            ["q", "$\\mathrm{e}^{x}$", "$\\ln(1+x)$", "$\\cos x$", "$\\dfrac{1}{1+x}$", "$\\sqrt{1+x}$ (ordre 3)"]],
          sol: [["q", "$1 + x + \\tfrac{x^{2}}{2} + \\tfrac{x^{3}}{6} + \\tfrac{x^{4}}{24} + o(x^{4})$.",
            "$x - \\tfrac{x^{2}}{2} + \\tfrac{x^{3}}{3} - \\tfrac{x^{4}}{4} + o(x^{4})$.",
            "$1 - \\tfrac{x^{2}}{2} + \\tfrac{x^{4}}{24} + o(x^{4})$.",
            "$1 - x + x^{2} - x^{3} + x^{4} + o(x^{4})$.",
            "$1 + \\tfrac{x}{2} - \\tfrac{x^{2}}{8} + \\tfrac{x^{3}}{16} + o(x^{3})$."]],
        },
        {
          t: "Limites par DL",
          c: ["Calculer :",
            ["q", "$\\displaystyle\\lim_{x\\to 0}\\frac{\\mathrm{e}^{x} - 1 - x}{x^{2}}$",
              "$\\displaystyle\\lim_{x\\to 0}\\frac{\\sin x - x}{x^{3}}$",
              "$\\displaystyle\\lim_{x\\to 0}\\frac{\\ln(1+x) - x + \\tfrac{x^{2}}{2}}{x^{3}}$",
              "$\\displaystyle\\lim_{x\\to 0}\\left(\\frac{1}{x} - \\frac{1}{\\sin x}\\right)$"]],
          sol: [["q", "$\\tfrac{1}{2}$.", "$-\\tfrac{1}{6}$.", "$\\tfrac{1}{3}$.",
            "$\\dfrac{\\sin x - x}{x\\sin x} \\sim \\dfrac{-x^{3}/6}{x^{2}} \\to 0$."]],
        },
        {
          t: "Étude asymptotique",
          c: ["Soit $f(x) = \\sqrt{x^{2}+x+1}$.",
            ["q", "Déterminer un développement asymptotique de $f$ en $+\\infty$ à l'ordre $\\tfrac{1}{x}$.",
              "En déduire l'équation de l'asymptote oblique et la position de la courbe.",
              "Faire de même en $-\\infty$."]],
          sol: [["q", "$f(x) = x\\sqrt{1 + \\tfrac{1}{x} + \\tfrac{1}{x^{2}}} = x + \\tfrac{1}{2} + \\tfrac{3}{8x} + o\\!\\left(\\tfrac{1}{x}\\right)$.",
            "Asymptote $y = x + \\tfrac{1}{2}$, la courbe est au-dessus (terme $\\tfrac{3}{8x} > 0$).",
            "En $-\\infty$, $\\sqrt{x^{2}} = -x$ : $f(x) = -x - \\tfrac{1}{2} - \\tfrac{3}{8x} + o\\!\\left(\\tfrac{1}{x}\\right)$, asymptote $y = -x - \\tfrac{1}{2}$, courbe au-dessus également."]],
        },
        {
          t: "Équivalents et séries",
          c: [["q", "Donner un équivalent simple en $0$ de $\\tan x - x$.",
            "Donner un équivalent en $+\\infty$ de $\\ln(n+1) - \\ln n$.",
            "En déduire la nature de $\\displaystyle\\sum_{n\\geqslant 1} \\left(\\ln(n+1)-\\ln n\\right)$.",
            "Étudier la nature de $\\displaystyle\\sum_{n \\geqslant 1}\\left(\\tan\\frac{1}{n} - \\frac{1}{n}\\right)$."]],
          sol: [["q", "$\\tan x - x \\sim \\tfrac{x^{3}}{3}$.",
            "$\\ln\\!\\left(1+\\tfrac{1}{n}\\right) \\sim \\tfrac{1}{n}$.",
            "Somme télescopique $= \\ln(n+1) \\to +\\infty$ : la série diverge (cohérent avec l'équivalent harmonique).",
            "Le terme général est équivalent à $\\dfrac{1}{3n^{3}}$, positif : la série converge (Riemann, $3 > 1$)."]],
        },
      ],
    },
    {
      t: "Fiche 7 — Intégration", st: "IPP, changement de variable, sommes de Riemann", diff: "★★★",
      desc: "Les techniques de calcul et les théorèmes d'approximation.",
      ex: [
        {
          t: "Techniques de calcul",
          c: ["Calculer :",
            ["q", "$\\displaystyle\\int_{0}^{1} x^{2}\\mathrm{e}^{x}\\,\\mathrm{d}x$", "$\\displaystyle\\int_{0}^{\\pi/2}\\cos^{3}x\\,\\mathrm{d}x$",
              "$\\displaystyle\\int_{0}^{1}\\frac{\\mathrm{d}x}{1+x^{2}}$", "$\\displaystyle\\int_{1}^{\\mathrm{e}}\\frac{\\ln x}{x^{2}}\\,\\mathrm{d}x$"]],
          sol: [["q", "Deux IPP : $\\mathrm{e} - 2$.",
            "$\\cos^{3} = \\cos(1-\\sin^{2})$, changement $u = \\sin x$ : $\\displaystyle\\int_{0}^{1}(1-u^{2})\\mathrm{d}u = \\tfrac{2}{3}$.",
            "$\\big[\\arctan x\\big]_{0}^{1} = \\tfrac{\\pi}{4}$.",
            "IPP avec $u = \\ln x$, $v' = x^{-2}$ : $\\left[-\\tfrac{\\ln x}{x}\\right]_{1}^{\\mathrm{e}} + \\displaystyle\\int_{1}^{\\mathrm{e}}\\tfrac{\\mathrm{d}x}{x^{2}} = -\\tfrac{1}{\\mathrm{e}} + 1 - \\tfrac{1}{\\mathrm{e}} = 1 - \\tfrac{2}{\\mathrm{e}}$."]],
        },
        {
          t: "Intégrales de Wallis",
          c: ["On pose $W_{n} = \\displaystyle\\int_{0}^{\\pi/2}\\cos^{n}x\\,\\mathrm{d}x$.",
            ["q", "Calculer $W_{0}$ et $W_{1}$.",
              "Montrer que $(W_{n})$ est décroissante et positive.",
              "Établir la relation $W_{n+2} = \\dfrac{n+1}{n+2}W_{n}$.",
              "Calculer $W_{4}$.",
              "Montrer que $(n+1)W_{n+1}W_{n} = \\dfrac{\\pi}{2}$ pour tout $n$."]],
          sol: [["q", "$W_{0} = \\tfrac{\\pi}{2}$ et $W_{1} = 1$.",
            "Sur $\\left[0\\,;\\,\\tfrac{\\pi}{2}\\right]$, $0 \\leqslant \\cos^{n+1}x \\leqslant \\cos^{n}x$ : l'intégration conserve l'inégalité.",
            "IPP avec $u = \\cos^{n+1}x$, $v' = \\cos x$ : on obtient $W_{n+2} = (n+1)(W_{n} - W_{n+2})$, d'où la relation.",
            "$W_{2} = \\tfrac{1}{2}W_{0} = \\tfrac{\\pi}{4}$ et $W_{4} = \\tfrac{3}{4}W_{2} = \\tfrac{3\\pi}{16}$.",
            "La quantité $u_{n} = (n+1)W_{n+1}W_{n}$ vérifie $u_{n+1} = u_{n}$ grâce à la relation de récurrence, et $u_{0} = W_{1}W_{0} = \\tfrac{\\pi}{2}$."]],
        },
        {
          t: "Sommes de Riemann",
          c: ["Déterminer les limites suivantes :",
            ["q", "$\\displaystyle\\lim_{n\\to+\\infty}\\frac{1}{n}\\sum_{k=1}^{n}\\frac{1}{1 + (k/n)^{2}}$",
              "$\\displaystyle\\lim_{n\\to+\\infty}\\sum_{k=1}^{n}\\frac{n}{n^{2}+k^{2}}$",
              "$\\displaystyle\\lim_{n\\to+\\infty}\\frac{1}{n}\\sum_{k=1}^{n}\\ln\\!\\left(1+\\frac{k}{n}\\right)$"]],
          sol: [["q", "$\\displaystyle\\int_{0}^{1}\\frac{\\mathrm{d}t}{1+t^{2}} = \\frac{\\pi}{4}$.",
            "Même somme réécrite : $\\dfrac{1}{n}\\displaystyle\\sum\\dfrac{1}{1+(k/n)^{2}} \\to \\dfrac{\\pi}{4}$.",
            "$\\displaystyle\\int_{0}^{1}\\ln(1+t)\\,\\mathrm{d}t = \\big[(1+t)\\ln(1+t) - t\\big]_{0}^{1} = 2\\ln 2 - 1$."]],
        },
        {
          t: "Inégalités intégrales",
          c: [["q", "Montrer que $\\displaystyle\\int_{0}^{1}\\frac{x^{n}}{1+x}\\mathrm{d}x \\leqslant \\frac{1}{n+1}$ et en déduire sa limite.",
            "Énoncer et démontrer l'inégalité de Cauchy-Schwarz intégrale.",
            "Application : pour $f$ continue positive sur $[0\\,;\\,1]$, comparer $\\left(\\displaystyle\\int_{0}^{1}f\\right)^{2}$ et $\\displaystyle\\int_{0}^{1}f^{2}$."]],
          sol: [["q", "$\\dfrac{1}{1+x} \\leqslant 1$ sur $[0\\,;\\,1]$ donne la majoration, et la limite est $0$.",
            "$\\left(\\displaystyle\\int fg\\right)^{2} \\leqslant \\displaystyle\\int f^{2}\\displaystyle\\int g^{2}$ : le trinôme $t \\mapsto \\displaystyle\\int (f+tg)^{2} \\geqslant 0$ a un discriminant négatif.",
            "Avec $g = 1$ : $\\left(\\displaystyle\\int_{0}^{1}f\\right)^{2} \\leqslant \\displaystyle\\int_{0}^{1}f^{2}$."]],
        },
      ],
    },
    {
      t: "Fiche 8 — Équations différentielles", st: "Ordre 1, ordre 2 à coefficients constants, raccords", diff: "★★",
      desc: "Résolution, variation de la constante et problèmes de Cauchy.",
      ex: [
        {
          t: "Équations d'ordre 1",
          c: ["Résoudre sur l'intervalle indiqué :",
            ["q", "$y' + 2y = \\mathrm{e}^{-2x}$ sur $\\mathbb{R}$",
              "$y' - \\dfrac{y}{x} = x$ sur $]0\\,;\\,+\\infty[$",
              "$(1+x^{2})y' + 2xy = 1$ sur $\\mathbb{R}$",
              "$y' + y\\tan x = \\sin 2x$ sur $\\left]-\\tfrac{\\pi}{2}\\,;\\,\\tfrac{\\pi}{2}\\right[$"]],
          sol: [["q", "$y = (x + C)\\mathrm{e}^{-2x}$.",
            "Solution homogène $Cx$ ; variation de la constante : $y = x^{2} + Cx$.",
            "Le membre de gauche est $\\left((1+x^{2})y\\right)'$ : $y = \\dfrac{x + C}{1+x^{2}}$.",
            "Facteur intégrant $\\dfrac{1}{\\cos x}$ : $y = \\cos x\\left(C - 2\\cos x\\right)$, à vérifier par dérivation."]],
        },
        {
          t: "Équations d'ordre 2",
          c: ["Résoudre sur $\\mathbb{R}$ :",
            ["q", "$y'' - 3y' + 2y = 0$", "$y'' + 4y = 0$", "$y'' - 2y' + y = \\mathrm{e}^{x}$",
              "$y'' + y = \\cos x$ (phénomène de résonance)"]],
          sol: [["q", "$r^{2}-3r+2 = 0$ : $y = A\\mathrm{e}^{x} + B\\mathrm{e}^{2x}$.",
            "$y = A\\cos 2x + B\\sin 2x$.",
            "Racine double $1$ : solution particulière $\\tfrac{x^{2}}{2}\\mathrm{e}^{x}$, donc $y = (A + Bx + \\tfrac{x^{2}}{2})\\mathrm{e}^{x}$.",
            "$y = A\\cos x + B\\sin x + \\tfrac{x}{2}\\sin x$ : l'amplitude croît linéairement."]],
        },
        {
          t: "Problème de Cauchy",
          c: ["On considère $y'' + 2y' + 5y = 0$ avec $y(0) = 1$ et $y'(0) = 0$.",
            ["q", "Résoudre l'équation homogène.",
              "Déterminer l'unique solution du problème de Cauchy.",
              "Décrire le comportement de la solution en $+\\infty$.",
              "Interpréter physiquement (oscillateur amorti)."]],
          sol: [["q", "$r^{2}+2r+5 = 0$ donne $r = -1 \\pm 2\\mathrm{i}$ : $y = \\mathrm{e}^{-x}(A\\cos 2x + B\\sin 2x)$.",
            "$y(0) = A = 1$ ; $y'(0) = -A + 2B = 0$ donne $B = \\tfrac{1}{2}$ : $y = \\mathrm{e}^{-x}\\left(\\cos 2x + \\tfrac{1}{2}\\sin 2x\\right)$.",
            "L'amplitude est majorée par $C\\mathrm{e}^{-x} \\to 0$ : la solution oscille en s'amortissant.",
            "C'est un régime pseudo-périodique : oscillations de pulsation $2$ amorties par le frottement."]],
        },
        {
          t: "Modélisation",
          c: ["Un corps de température $T(t)$ plongé dans un milieu à $20$ °C vérifie la loi de Newton $T' = -k(T - 20)$ avec $k > 0$.",
            ["q", "Résoudre cette équation avec $T(0) = 90$.",
              "Sachant que $T(10) = 60$ (temps en minutes), déterminer $k$.",
              "Au bout de combien de temps la température atteint-elle $30$ °C ?"]],
          sol: [["q", "$T(t) = 20 + 70\\mathrm{e}^{-kt}$.",
            "$70\\mathrm{e}^{-10k} = 40$ donne $k = \\tfrac{1}{10}\\ln\\tfrac{7}{4} \\approx 0{,}0560$ min$^{-1}$.",
            "$70\\mathrm{e}^{-kt} = 10 \\iff t = \\dfrac{\\ln 7}{k} \\approx 34{,}8$ minutes."]],
        },
      ],
    },
    {
      t: "Fiche 9 — Algèbre linéaire", st: "Sous-espaces, familles libres, applications linéaires, matrices", diff: "★★★",
      desc: "Les objets de base : base, dimension, rang, noyau et image.",
      ex: [
        {
          t: "Sous-espaces vectoriels",
          c: ["Dans $\\mathbb{R}^{3}$, on pose $F = \\{(x,y,z) : x + y - z = 0\\}$ et $G = \\mathrm{Vect}\\big((1,1,1)\\big)$.",
            ["q", "Montrer que $F$ est un sous-espace vectoriel et en donner une base.",
              "Déterminer $\\dim F$ et $\\dim G$.",
              "Montrer que $F \\oplus G = \\mathbb{R}^{3}$.",
              "Déterminer la matrice, dans la base canonique, de la projection sur $F$ parallèlement à $G$."]],
          sol: [["q", "$F$ est le noyau de la forme linéaire $(x,y,z)\\mapsto x+y-z$ ; base : $(1,0,1)$ et $(0,1,1)$.",
            "$\\dim F = 2$ et $\\dim G = 1$.",
            "$(1,1,1) \\notin F$ car $1+1-1 = 1 \\neq 0$ : $F \\cap G = \\{0\\}$ et $2 + 1 = 3$.",
            "Tout $u$ s'écrit $u = p(u) + \\lambda(1,1,1)$ avec $\\lambda = x+y-z$ : $p(x,y,z) = (x - \\lambda,\\ y - \\lambda,\\ z - \\lambda)$, de matrice $\\begin{pmatrix}0&-1&1\\\\-1&0&1\\\\-1&-1&2\\end{pmatrix}$."]],
        },
        {
          t: "Applications linéaires",
          c: ["Soit $f : \\mathbb{R}^{3}\\to\\mathbb{R}^{3}$ définie par $f(x,y,z) = (x+y,\\ y+z,\\ x-z)$.",
            ["q", "Écrire la matrice $A$ de $f$ dans la base canonique.",
              "Déterminer $\\ker f$ et sa dimension.",
              "En déduire $\\mathrm{rg}(f)$ et une base de $\\mathrm{Im}\\,f$.",
              "$f$ est-elle un automorphisme ?"]],
          sol: [["q", "$A = \\begin{pmatrix}1&1&0\\\\0&1&1\\\\1&0&-1\\end{pmatrix}$.",
            "Le système donne $x = -y = z$ : $\\ker f = \\mathrm{Vect}\\big((1,-1,1)\\big)$, de dimension $1$.",
            "Par le théorème du rang, $\\mathrm{rg}(f) = 2$ ; les deux premières colonnes $(1,0,1)$ et $(1,1,0)$ en forment une base.",
            "Non : le noyau n'est pas réduit à $\\{0\\}$, $f$ n'est pas injective."]],
        },
        {
          t: "Calcul matriciel",
          c: ["Soit $A = \\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$ et $N = A - I_{2}$.",
            ["q", "Calculer $N^{2}$.",
              "En déduire $A^{\\,n}$ pour tout $n \\in \\mathbb{N}$.",
              "$A$ est-elle inversible ? Calculer $A^{-1}$.",
              "La formule obtenue pour $A^{\\,n}$ reste-t-elle valable pour $n$ négatif ?"]],
          sol: [["q", "$N = \\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$ et $N^{2} = 0$.",
            "$A^{n} = (I+N)^{n} = I + nN = \\begin{pmatrix}1&n\\\\0&1\\end{pmatrix}$ (binôme, $I$ et $N$ commutent).",
            "$\\det A = 1 \\neq 0$ : $A^{-1} = \\begin{pmatrix}1&-1\\\\0&1\\end{pmatrix}$.",
            "Oui : la formule $\\begin{pmatrix}1&n\\\\0&1\\end{pmatrix}$ vaut pour tout $n \\in \\mathbb{Z}$."]],
        },
        {
          t: "Systèmes linéaires",
          c: ["Discuter et résoudre, selon le paramètre $m$, le système",
            ["$", "\\begin{cases} x + y + z = 1 \\\\ x + my + z = m \\\\ x + y + mz = m^{2}\\end{cases}"],
            ["q", "Calculer le déterminant de la matrice du système.",
              "Résoudre lorsque $m \\neq 1$.",
              "Étudier le cas $m = 1$."]],
          sol: [["q", "En développant : $\\det = (m-1)^{2}$.",
            "Pour $m \\neq 1$ : en soustrayant la première ligne aux autres, $(m-1)y = m-1$ et $(m-1)z = m^{2}-1$, d'où $y = 1$, $z = m+1$ et $x = 1 - y - z = -m - 1$.",
            "Pour $m = 1$, les trois équations deviennent $x+y+z = 1$ : l'ensemble des solutions est un plan affine de dimension $2$."]],
        },
      ],
    },
    {
      t: "Fiche 10 — Arithmétique et dénombrement", st: "Bézout, congruences, dénombrement, probabilités finies", diff: "★★",
      desc: "Divisibilité, cryptographie élémentaire et comptages classiques.",
      ex: [
        {
          t: "PGCD et Bézout",
          c: [["q", "Calculer $\\mathrm{pgcd}(462, 1071)$ par l'algorithme d'Euclide.",
            "Déterminer une relation de Bézout associée.",
            "Résoudre dans $\\mathbb{Z}^{2}$ l'équation $462u + 1071v = 21$.",
            "Résoudre $7x \\equiv 3 \\ [11]$."]],
          sol: [["q", "$1071 = 2\\times462 + 147$ ; $462 = 3\\times147 + 21$ ; $147 = 7\\times21$ : le pgcd vaut $21$.",
            "$21 = 462 - 3\\times147 = 462 - 3(1071 - 2\\times462) = 7\\times462 - 3\\times1071$.",
            "Solution particulière $(7,-3)$ ; solutions générales : $u = 7 + 51k$, $v = -3 - 22k$, $k \\in \\mathbb{Z}$ (on a divisé par $21$).",
            "$7 \\times 8 = 56 \\equiv 1\\ [11]$ donc $x \\equiv 8\\times3 = 24 \\equiv 2\\ [11]$."]],
        },
        {
          t: "Congruences",
          c: [["q", "Déterminer le reste de la division euclidienne de $3^{2024}$ par $7$.",
            "Montrer que pour tout $n$, $n^{3} - n$ est divisible par $6$.",
            "Énoncer le petit théorème de Fermat et l'appliquer au calcul de $2^{100} \\bmod 101$."]],
          sol: [["q", "$3^{6} \\equiv 1\\ [7]$ et $2024 = 6\\times337 + 2$ : le reste est $3^{2} = 2$.",
            "$n^{3}-n = (n-1)n(n+1)$ est un produit de trois entiers consécutifs, divisible par $2$ et par $3$.",
            "Si $p$ est premier et $p \\nmid a$, alors $a^{p-1} \\equiv 1\\ [p]$ : ici $2^{100} \\equiv 1\\ [101]$."]],
        },
        {
          t: "Dénombrement",
          c: ["Un jeu de $32$ cartes ; on tire une main de $5$ cartes.",
            ["q", "Combien de mains possibles ?",
              "Combien de mains contenant exactement deux rois ?",
              "Combien de mains contenant au moins un as ?",
              "Combien d'anagrammes du mot MATHS ? Et du mot SUITES ?"]],
          sol: [["q", "$\\binom{32}{5} = 201\\,376$.",
            "$\\binom{4}{2}\\binom{28}{3} = 6 \\times 3276 = 19\\,656$.",
            "$\\binom{32}{5} - \\binom{28}{5} = 201\\,376 - 98\\,280 = 103\\,096$.",
            "$5! = 120$ ; pour SUITES, six lettres dont deux S : $\\dfrac{6!}{2} = 360$."]],
        },
        {
          t: "Probabilités finies",
          c: ["On lance trois dés équilibrés à six faces.",
            ["q", "Quelle est la probabilité d'obtenir trois faces identiques ?",
              "Quelle est la probabilité que la somme vaille $10$ ?",
              "Quelle est la probabilité d'obtenir au moins un $6$ ?",
              "On répète l'expérience jusqu'au premier triple. Quelle est la probabilité que cela arrive au $k$-ième lancer ?"]],
          sol: [["q", "$\\dfrac{6}{216} = \\dfrac{1}{36}$.",
            "Il y a $27$ triplets ordonnés de somme $10$ : $\\dfrac{27}{216} = \\dfrac{1}{8}$.",
            "$1 - \\left(\\tfrac{5}{6}\\right)^{3} = \\dfrac{91}{216} \\approx 0{,}421$.",
            "Loi géométrique de paramètre $\\tfrac{1}{36}$ : $P(T = k) = \\left(\\tfrac{35}{36}\\right)^{k-1}\\tfrac{1}{36}$."]],
        },
      ],
    },
  ]);

  L.addSujets("sup", "ds", [
    {
      t: "Contrôle n° 1 — Nombres complexes", st: "Formes, racines, géométrie", h: 1, calc: "interdite",
      desc: "Trois exercices courts sur le chapitre des complexes.",
      ex: [
        {
          t: "Calculs", pts: 7,
          c: [["q", "Mettre $z = \\dfrac{1+\\mathrm{i}}{\\sqrt{3}-\\mathrm{i}}$ sous forme algébrique puis exponentielle.",
            "En déduire les valeurs exactes de $\\cos\\dfrac{5\\pi}{12}$ et $\\sin\\dfrac{5\\pi}{12}$.",
            "Calculer $z^{12}$."]],
          sol: [["q", "$|1+\\mathrm{i}| = \\sqrt{2}$, $\\arg = \\tfrac{\\pi}{4}$ ; $|\\sqrt{3}-\\mathrm{i}| = 2$, $\\arg = -\\tfrac{\\pi}{6}$ : $z = \\tfrac{\\sqrt{2}}{2}\\mathrm{e}^{5\\mathrm{i}\\pi/12}$. Forme algébrique : $z = \\dfrac{(1+\\mathrm{i})(\\sqrt{3}+\\mathrm{i})}{4} = \\dfrac{\\sqrt{3}-1}{4} + \\mathrm{i}\\dfrac{\\sqrt{3}+1}{4}$.",
            "En identifiant : $\\cos\\tfrac{5\\pi}{12} = \\dfrac{\\sqrt{6}-\\sqrt{2}}{4}$ et $\\sin\\tfrac{5\\pi}{12} = \\dfrac{\\sqrt{6}+\\sqrt{2}}{4}$.",
            "$z^{12} = \\left(\\tfrac{\\sqrt{2}}{2}\\right)^{12}\\mathrm{e}^{5\\mathrm{i}\\pi} = \\tfrac{1}{64}\\times(-1) = -\\tfrac{1}{64}$."]],
        },
        {
          t: "Racines", pts: 6,
          c: [["q", "Résoudre $z^{3} = -27$.",
            "Résoudre $z^{2} = 3 + 4\\mathrm{i}$ (on cherchera les racines sous forme algébrique).",
            "Résoudre $z^{2} - 2z\\cos\\theta + 1 = 0$ pour $\\theta \\in \\,]0\\,;\\,\\pi[$."]],
          sol: [["q", "$-27 = 27\\mathrm{e}^{\\mathrm{i}\\pi}$ : $z = 3\\mathrm{e}^{\\mathrm{i}(\\pi/3 + 2k\\pi/3)}$, soit $-3$, $\\tfrac{3}{2}(1 \\pm \\mathrm{i}\\sqrt{3})$.",
            "Avec $z = a+\\mathrm{i}b$ : $a^{2}-b^{2} = 3$, $2ab = 4$, $a^{2}+b^{2} = 5$ : $a = \\pm 2$, $b = \\pm 1$ de même signe, soit $z = \\pm(2+\\mathrm{i})$.",
            "$\\Delta = 4\\cos^{2}\\theta - 4 = -4\\sin^{2}\\theta$ : $z = \\cos\\theta \\pm \\mathrm{i}\\sin\\theta = \\mathrm{e}^{\\pm\\mathrm{i}\\theta}$."]],
        },
        {
          t: "Géométrie", pts: 7,
          c: ["On note $A$, $B$, $C$ les points d'affixes $a = 1$, $b = \\mathrm{i}$, $c = -1 + \\mathrm{i}$.",
            ["q", "Calculer $\\dfrac{c-a}{b-a}$ sous forme algébrique.",
              "En déduire la nature du triangle $ABC$.",
              "Déterminer l'affixe du point $D$ tel que $ABDC$ soit un parallélogramme.",
              "Déterminer l'image de $A$ par la rotation de centre $B$ et d'angle $\\tfrac{\\pi}{2}$."]],
          sol: [["q", "$\\dfrac{-2+\\mathrm{i}}{-1+\\mathrm{i}} = \\dfrac{(-2+\\mathrm{i})(-1-\\mathrm{i})}{2} = \\dfrac{3 + \\mathrm{i}}{2}$.",
            "Le quotient n'est ni réel ni imaginaire pur et son module vaut $\\tfrac{\\sqrt{10}}{2} \\neq 1$ : le triangle est quelconque.",
            "$d = b + c - a = -2 + 2\\mathrm{i}$.",
            "$z' = b + \\mathrm{i}(a - b) = \\mathrm{i} + \\mathrm{i}(1 - \\mathrm{i}) = 1 + 2\\mathrm{i}$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 2 — Suites", st: "Convergence, récurrence, suites adjacentes", h: 1, calc: "interdite",
      desc: "Trois exercices de rédaction sur les suites réelles.",
      ex: [
        {
          t: "Limites", pts: 6,
          c: ["Déterminer, en justifiant, la limite de :",
            ["q", "$u_{n} = \\sqrt{n+1} - \\sqrt{n}$", "$v_{n} = \\dfrac{2^{\\,n}}{n!}$", "$w_{n} = n\\sin\\dfrac{1}{n}$",
              "$t_{n} = \\left(\\dfrac{n}{n+1}\\right)^{n}$"]],
          sol: [["q", "$u_{n} = \\dfrac{1}{\\sqrt{n+1}+\\sqrt{n}} \\to 0$.",
            "$\\dfrac{v_{n+1}}{v_{n}} = \\dfrac{2}{n+1} \\to 0 < 1$ : $v_{n} \\to 0$.",
            "$\\sin u \\sim u$ en $0$ : $w_{n} \\to 1$.",
            "$t_{n} = \\exp\\!\\left(-n\\ln\\!\\left(1+\\tfrac{1}{n}\\right)\\right) \\to \\mathrm{e}^{-1}$."]],
        },
        {
          t: "Suite récurrente", pts: 8,
          c: ["Soit $u_{0} = 3$ et $u_{n+1} = \\dfrac{u_{n}^{2}+2}{2u_{n}}$.",
            ["q", "Montrer que $u_{n} \\geqslant \\sqrt{2}$ pour tout $n$.",
              "Montrer que $(u_{n})$ est décroissante.",
              "En déduire qu'elle converge et calculer sa limite.",
              "Montrer que $u_{n+1} - \\sqrt{2} \\leqslant \\dfrac{(u_{n}-\\sqrt{2})^{2}}{2\\sqrt{2}}$ : que peut-on dire de la vitesse de convergence ?"]],
          sol: [["q", "$u_{n+1} - \\sqrt{2} = \\dfrac{(u_{n}-\\sqrt{2})^{2}}{2u_{n}} \\geqslant 0$ dès que $u_{n} > 0$, et la positivité se propage.",
            "$u_{n+1} - u_{n} = \\dfrac{2 - u_{n}^{2}}{2u_{n}} \\leqslant 0$ puisque $u_{n} \\geqslant \\sqrt{2}$.",
            "Décroissante et minorée : elle converge vers $\\ell$ vérifiant $2\\ell^{2} = \\ell^{2}+2$, donc $\\ell = \\sqrt{2}$.",
            "L'inégalité vient de $u_{n} \\geqslant \\sqrt{2}$ : la convergence est quadratique (le nombre de décimales exactes double à chaque étape) — c'est la méthode de Héron."]],
        },
        {
          t: "Suites adjacentes", pts: 6,
          c: ["On pose $u_{n} = \\displaystyle\\sum_{k=1}^{n}\\frac{(-1)^{k+1}}{k}$.",
            ["q", "Montrer que $(u_{2n})$ est croissante et $(u_{2n+1})$ décroissante.",
              "Montrer que ces deux suites sont adjacentes.",
              "En déduire que $(u_{n})$ converge et encadrer sa limite entre $u_{4}$ et $u_{5}$."]],
          sol: [["q", "$u_{2n+2} - u_{2n} = \\dfrac{1}{2n+1} - \\dfrac{1}{2n+2} > 0$ ; de même $u_{2n+3} - u_{2n+1} < 0$.",
            "$u_{2n+1} - u_{2n} = \\dfrac{1}{2n+1} \\to 0$ : les suites sont adjacentes.",
            "Elles convergent vers la même limite $\\ell$ (qui vaut $\\ln 2$), avec $u_{4} = \\tfrac{7}{12} \\approx 0{,}583 \\leqslant \\ell \\leqslant u_{5} = \\tfrac{47}{60} \\approx 0{,}783$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 3 — Développements limités", st: "DL, équivalents, limites, asymptotes", h: 1, calc: "interdite",
      desc: "Calculs de DL et applications immédiates.",
      ex: [
        {
          t: "Calculs de DL", pts: 8,
          c: ["Déterminer le développement limité en $0$ :",
            ["q", "de $\\dfrac{\\mathrm{e}^{x}}{1+x}$ à l'ordre $3$",
              "de $\\ln(1+\\sin x)$ à l'ordre $3$",
              "de $\\sqrt{1+x^{2}}$ à l'ordre $4$",
              "de $\\tan x$ à l'ordre $5$"]],
          sol: [["q", "$1 + \\tfrac{x^{2}}{2} - \\tfrac{x^{3}}{3} + o(x^{3})$.",
            "$\\sin x = x - \\tfrac{x^{3}}{6}$ puis composition : $x - \\tfrac{x^{2}}{2} + \\tfrac{x^{3}}{6} + o(x^{3})$.",
            "$1 + \\tfrac{x^{2}}{2} - \\tfrac{x^{4}}{8} + o(x^{4})$.",
            "$x + \\tfrac{x^{3}}{3} + \\tfrac{2x^{5}}{15} + o(x^{5})$."]],
        },
        {
          t: "Limites", pts: 6,
          c: ["Calculer :",
            ["q", "$\\displaystyle\\lim_{x\\to 0}\\frac{\\cos x - 1 + \\tfrac{x^{2}}{2}}{x^{4}}$",
              "$\\displaystyle\\lim_{x\\to 0}\\frac{(1+x)^{1/x} - \\mathrm{e}}{x}$",
              "$\\displaystyle\\lim_{x\\to+\\infty} x^{2}\\left(\\mathrm{e}^{1/x} - 1 - \\tfrac{1}{x}\\right)$"]],
          sol: [["q", "$\\tfrac{1}{24}$.",
            "$(1+x)^{1/x} = \\mathrm{e}\\exp\\!\\left(-\\tfrac{x}{2}+o(x)\\right) = \\mathrm{e}\\left(1-\\tfrac{x}{2}+o(x)\\right)$ : la limite vaut $-\\tfrac{\\mathrm{e}}{2}$.",
            "Avec $u = \\tfrac{1}{x} \\to 0$ : $\\dfrac{\\mathrm{e}^{u}-1-u}{u^{2}} \\to \\tfrac{1}{2}$."]],
        },
        {
          t: "Étude locale", pts: 6,
          c: ["Soit $f(x) = \\dfrac{\\ln(1+x)}{x}$ pour $x > -1$, $x \\neq 0$, prolongée par $f(0) = 1$.",
            ["q", "Justifier que $f$ est continue en $0$.",
              "Donner un DL de $f$ à l'ordre $2$ en $0$.",
              "En déduire que $f$ est dérivable en $0$ et donner $f'(0)$.",
              "La courbe admet-elle une tangente horizontale en $0$ ?"]],
          sol: [["q", "$\\ln(1+x) \\sim x$ : $f(x) \\to 1 = f(0)$.",
            "$f(x) = 1 - \\tfrac{x}{2} + \\tfrac{x^{2}}{3} + o(x^{2})$.",
            "Le DL à l'ordre $1$ donne la dérivabilité : $f'(0) = -\\tfrac{1}{2}$.",
            "Non : la tangente a pour pente $-\\tfrac{1}{2}$, d'équation $y = 1 - \\tfrac{x}{2}$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 4 — Intégration", st: "IPP, changement de variable, sommes de Riemann", h: 1, calc: "interdite",
      desc: "Calculs d'intégrales et une suite définie par une intégrale.",
      ex: [
        {
          t: "Calculs", pts: 8,
          c: ["Calculer :",
            ["q", "$\\displaystyle\\int_{0}^{\\pi}x\\sin x\\,\\mathrm{d}x$", "$\\displaystyle\\int_{0}^{1}\\frac{x}{1+x^{2}}\\mathrm{d}x$",
              "$\\displaystyle\\int_{1}^{2}\\frac{\\mathrm{d}x}{x(x+1)}$", "$\\displaystyle\\int_{0}^{1}\\arctan x\\,\\mathrm{d}x$"]],
          sol: [["q", "IPP : $\\big[-x\\cos x\\big]_{0}^{\\pi} + \\displaystyle\\int_{0}^{\\pi}\\cos x\\,\\mathrm{d}x = \\pi$.",
            "$\\tfrac{1}{2}\\big[\\ln(1+x^{2})\\big]_{0}^{1} = \\tfrac{\\ln 2}{2}$.",
            "Décomposition $\\tfrac{1}{x}-\\tfrac{1}{x+1}$ : $\\big[\\ln\\tfrac{x}{x+1}\\big]_{1}^{2} = \\ln\\tfrac{4}{3}$.",
            "IPP : $\\tfrac{\\pi}{4} - \\tfrac{\\ln 2}{2}$."]],
        },
        {
          t: "Suite d'intégrales", pts: 8,
          c: ["Pour $n \\geqslant 0$, $I_{n} = \\displaystyle\\int_{0}^{1}\\frac{x^{\\,n}}{1+x}\\,\\mathrm{d}x$.",
            ["q", "Calculer $I_{0}$.",
              "Montrer que $(I_{n})$ est décroissante et positive.",
              "Montrer que $I_{n} + I_{n+1} = \\dfrac{1}{n+1}$.",
              "En déduire $\\displaystyle\\lim_{n\\to+\\infty} I_{n}$ puis un équivalent de $I_{n}$.",
              "En déduire la valeur de $\\displaystyle\\sum_{k=1}^{+\\infty}\\frac{(-1)^{k+1}}{k}$."]],
          sol: [["q", "$I_{0} = \\big[\\ln(1+x)\\big]_{0}^{1} = \\ln 2$.",
            "Positivité évidente ; $x^{n+1} \\leqslant x^{n}$ sur $[0\\,;\\,1]$ donne la décroissance.",
            "$I_{n}+I_{n+1} = \\displaystyle\\int_{0}^{1}\\frac{x^{n}(1+x)}{1+x}\\mathrm{d}x = \\frac{1}{n+1}$.",
            "$0 \\leqslant I_{n} \\leqslant \\tfrac{1}{n+1} \\to 0$ ; la décroissance et la relation donnent $2I_{n} \\sim \\tfrac{1}{n}$, soit $I_{n} \\sim \\tfrac{1}{2n}$.",
            "En sommant $I_{k} + I_{k+1} = \\tfrac{1}{k+1}$ avec des signes alternés, on obtient $\\displaystyle\\sum_{k=1}^{n}\\frac{(-1)^{k+1}}{k} = \\ln 2 - (-1)^{n}I_{n} \\to \\ln 2$."]],
        },
        {
          t: "Somme de Riemann", pts: 4,
          c: [["q", "Reconnaître $\\displaystyle\\lim_{n\\to+\\infty}\\frac{1}{n}\\sum_{k=1}^{n}\\sqrt{\\frac{k}{n}}$ comme une intégrale, puis la calculer.",
            "Même question pour $\\displaystyle\\lim_{n\\to+\\infty}\\sum_{k=1}^{n}\\frac{1}{n+k}$."]],
          sol: [["q", "$\\displaystyle\\int_{0}^{1}\\sqrt{t}\\,\\mathrm{d}t = \\tfrac{2}{3}$.",
            "$\\dfrac{1}{n}\\displaystyle\\sum\\dfrac{1}{1+k/n} \\to \\displaystyle\\int_{0}^{1}\\frac{\\mathrm{d}t}{1+t} = \\ln 2$."]],
        },
      ],
    },
    {
      t: "Contrôle n° 5 — Algèbre linéaire", st: "Matrices, systèmes, noyau et image", h: 1, calc: "interdite",
      desc: "Calcul matriciel, rang et applications linéaires.",
      ex: [
        {
          t: "Calcul matriciel", pts: 7,
          c: ["Soit $A = \\begin{pmatrix}2&1&0\\\\0&2&1\\\\0&0&2\\end{pmatrix}$.",
            ["q", "Écrire $A = 2I_{3} + N$ et calculer $N^{2}$, $N^{3}$.",
              "En déduire $A^{\\,n}$ pour $n \\in \\mathbb{N}$.",
              "Justifier que $A$ est inversible et calculer $A^{-1}$."]],
          sol: [["q", "$N$ est nilpotente d'indice $3$ : $N^{2} = \\begin{pmatrix}0&0&1\\\\0&0&0\\\\0&0&0\\end{pmatrix}$ et $N^{3} = 0$.",
            "$A^{n} = \\displaystyle\\sum_{k=0}^{2}\\binom{n}{k}2^{\\,n-k}N^{k} = 2^{n}I + n2^{\\,n-1}N + \\tfrac{n(n-1)}{2}2^{\\,n-2}N^{2}$.",
            "$\\det A = 8 \\neq 0$ ; $A^{-1} = \\tfrac{1}{2}I - \\tfrac{1}{4}N + \\tfrac{1}{8}N^{2} = \\begin{pmatrix}\\tfrac12&-\\tfrac14&\\tfrac18\\\\0&\\tfrac12&-\\tfrac14\\\\0&0&\\tfrac12\\end{pmatrix}$."]],
        },
        {
          t: "Noyau et image", pts: 7,
          c: ["Soit $f : \\mathbb{R}^{4}\\to\\mathbb{R}^{3}$ de matrice $M = \\begin{pmatrix}1&2&0&1\\\\0&1&1&1\\\\1&3&1&2\\end{pmatrix}$.",
            ["q", "Déterminer le rang de $M$.",
              "En déduire $\\dim\\ker f$.",
              "Donner une base de $\\ker f$.",
              "$f$ est-elle surjective ?"]],
          sol: [["q", "$L_{3} = L_{1}+L_{2}$ : le rang est $2$ (les deux premières lignes sont indépendantes).",
            "Théorème du rang : $\\dim\\ker f = 4 - 2 = 2$.",
            "Le système donne $y = -z - t$ et $x = -2y - t = 2z + t$ : base $\\{(2,-1,1,0),\\ (1,-1,0,1)\\}$.",
            "Non : $\\mathrm{rg}(f) = 2 < 3$."]],
        },
        {
          t: "Système paramétré", pts: 6,
          c: ["Discuter selon $a$ le système $\\begin{cases}x + 2y = 1\\\\ 2x + ay = 3\\end{cases}$.",
            ["q", "Calculer le déterminant.",
              "Résoudre pour $a \\neq 4$.",
              "Étudier le cas $a = 4$."]],
          sol: [["q", "$\\det = a - 4$.",
            "Système de Cramer : $x = \\dfrac{a-6}{a-4}$ et $y = \\dfrac{1}{a-4}$.",
            "Pour $a = 4$, $L_{2} = 2L_{1}$ donnerait $3 = 2$ : le système est incompatible, aucune solution."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 1 — Analyse", st: "Suites, fonctions, DL, intégrales", h: 3, calc: "interdite",
      desc: "Trois problèmes progressifs d'analyse, dans l'esprit des concours.",
      ex: [
        {
          t: "Une suite implicite", pts: 8, nom: "Problème",
          c: ["Pour $n \\geqslant 1$, on considère l'équation $(E_{n})$ : $x + \\ln x = n$, d'inconnue $x > 0$.",
            ["h", "Partie A — Existence"],
            ["q", "Montrer que $(E_{n})$ admet une unique solution $x_{n} > 0$.",
              "Montrer que $(x_{n})$ est strictement croissante.",
              "Montrer que $x_{n} \\to +\\infty$."],
            ["h", "Partie B — Comportement asymptotique"],
            ["q", "Montrer que $x_{n} \\sim n$.",
              "Montrer que $x_{n} = n - \\ln n + o(\\ln n)$.",
              "En déduire un équivalent de $x_{n} - n + \\ln n$."]],
          sol: [["h", "Partie A"],
            ["q", "$\\varphi(x) = x + \\ln x$ est continue strictement croissante de $]0\\,;\\,+\\infty[$ sur $\\mathbb{R}$ : c'est une bijection, d'où l'existence et l'unicité.",
              "$\\varphi(x_{n+1}) = n+1 > n = \\varphi(x_{n})$ et $\\varphi$ est croissante : $x_{n+1} > x_{n}$.",
              "Si $(x_{n})$ était majorée, elle convergerait vers $\\ell$ et $n = \\varphi(x_{n}) \\to \\varphi(\\ell)$ serait borné : absurde."],
            ["h", "Partie B"],
            ["q", "$\\dfrac{x_{n}}{n} = \\dfrac{x_{n}}{x_{n}+\\ln x_{n}} = \\dfrac{1}{1 + \\tfrac{\\ln x_{n}}{x_{n}}} \\to 1$.",
              "$x_{n} = n - \\ln x_{n}$ et $\\ln x_{n} = \\ln n + \\ln\\tfrac{x_{n}}{n} = \\ln n + o(1)$, d'où le résultat.",
              "$x_{n} - n + \\ln n = -\\ln\\dfrac{x_{n}}{n} \\sim -\\dfrac{x_{n}-n}{n} \\sim \\dfrac{\\ln n}{n}$."]],
        },
        {
          t: "Étude d'une fonction", pts: 6, nom: "Problème",
          c: ["Soit $f(x) = \\dfrac{x}{\\mathrm{e}^{x}-1}$ pour $x \\neq 0$, prolongée par $f(0) = 1$.",
            ["q", "Montrer que $f$ est continue en $0$.",
              "Donner le DL de $f$ à l'ordre $2$ en $0$.",
              "En déduire que $f$ est dérivable en $0$ et préciser la tangente.",
              "Déterminer les limites de $f$ en $\\pm\\infty$.",
              "Montrer que $f(x) + \\dfrac{x}{2}$ est paire (on écrira $f$ à l'aide de $\\mathrm{coth}$)."]],
          sol: [["q", "$\\mathrm{e}^{x}-1 \\sim x$ : $f(x)\\to 1$.",
            "$\\dfrac{x}{x + \\tfrac{x^{2}}{2} + \\tfrac{x^{3}}{6}} = 1 - \\tfrac{x}{2} + \\tfrac{x^{2}}{12} + o(x^{2})$.",
            "$f'(0) = -\\tfrac{1}{2}$ : tangente $y = 1 - \\tfrac{x}{2}$.",
            "En $+\\infty$ : $0$ ; en $-\\infty$ : $\\dfrac{x}{-1} \\to +\\infty$.",
            "$f(x) + \\tfrac{x}{2} = \\tfrac{x}{2}\\,\\mathrm{coth}\\!\\left(\\tfrac{x}{2}\\right)$, produit de deux fonctions impaires : c'est une fonction paire."]],
        },
        {
          t: "Autour d'une intégrale", pts: 6, nom: "Problème",
          c: ["Pour $n \\in \\mathbb{N}$, on pose $J_{n} = \\displaystyle\\int_{0}^{1}(1-t)^{n}\\mathrm{e}^{t}\\,\\mathrm{d}t$.",
            ["q", "Calculer $J_{0}$ et $J_{1}$.",
              "Établir $J_{n+1} = (n+1)J_{n} - 1$.",
              "Montrer que $0 \\leqslant J_{n} \\leqslant \\dfrac{\\mathrm{e}}{n+1}$, puis déterminer $\\displaystyle\\lim J_{n}$.",
              "En déduire que $\\displaystyle\\sum_{k=0}^{n}\\frac{1}{k!} \\to \\mathrm{e}$ (on utilisera $\\dfrac{J_{n}}{n!}$)."]],
          sol: [["q", "$J_{0} = \\mathrm{e}-1$ ; IPP : $J_{1} = \\mathrm{e} - 2$.",
            "IPP avec $u = (1-t)^{n+1}$, $v' = \\mathrm{e}^{t}$ : $J_{n+1} = -1 + (n+1)J_{n}$.",
            "$(1-t)^{n}\\mathrm{e}^{t} \\leqslant \\mathrm{e}(1-t)^{n}$ donne la majoration ; par encadrement, $J_{n} \\to 0$.",
            "En divisant la relation par $(n+1)!$ : $\\dfrac{J_{n+1}}{(n+1)!} = \\dfrac{J_{n}}{n!} - \\dfrac{1}{(n+1)!}$, d'où en sommant $\\dfrac{J_{n}}{n!} = \\mathrm{e} - \\displaystyle\\sum_{k=0}^{n}\\frac{1}{k!}$, qui tend vers $0$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 2 — Algèbre", st: "Polynômes, espaces vectoriels, matrices", h: 3, calc: "interdite",
      desc: "Polynômes de Tchebychev, endomorphismes et matrices nilpotentes.",
      ex: [
        {
          t: "Polynômes de Tchebychev", pts: 8, nom: "Problème",
          c: ["On définit $T_{0} = 1$, $T_{1} = X$ et $T_{n+2} = 2X\\,T_{n+1} - T_{n}$.",
            ["q", "Calculer $T_{2}$, $T_{3}$ et $T_{4}$.",
              "Montrer par récurrence double que $T_{n}(\\cos\\theta) = \\cos(n\\theta)$.",
              "En déduire le degré et le coefficient dominant de $T_{n}$.",
              "Déterminer les racines de $T_{n}$ dans $[-1\\,;\\,1]$.",
              "En déduire que $T_{n}$ est scindé à racines simples sur $\\mathbb{R}$."]],
          sol: [["q", "$T_{2} = 2X^{2}-1$, $T_{3} = 4X^{3}-3X$, $T_{4} = 8X^{4}-8X^{2}+1$.",
            "Vrai aux rangs $0$ et $1$ ; l'hérédité vient de $\\cos((n+2)\\theta) = 2\\cos\\theta\\cos((n+1)\\theta) - \\cos(n\\theta)$.",
            "$\\deg T_{n} = n$ et le coefficient dominant vaut $2^{\\,n-1}$ pour $n \\geqslant 1$.",
            "$\\cos(n\\theta) = 0 \\iff \\theta = \\dfrac{(2k+1)\\pi}{2n}$ : les racines sont $x_{k} = \\cos\\dfrac{(2k+1)\\pi}{2n}$, $0 \\leqslant k \\leqslant n-1$.",
            "Ces $n$ racines sont deux à deux distinctes dans $[-1\\,;\\,1]$ : $T_{n}$, de degré $n$, est scindé à racines simples."]],
        },
        {
          t: "Un endomorphisme de polynômes", pts: 7, nom: "Problème",
          c: ["Sur $E = \\mathbb{R}_{3}[X]$, on pose $\\varphi(P) = P - P'$.",
            ["q", "Montrer que $\\varphi$ est un endomorphisme de $E$.",
              "Écrire la matrice de $\\varphi$ dans la base canonique $(1, X, X^{2}, X^{3})$.",
              "Déterminer $\\ker\\varphi$ ; $\\varphi$ est-elle bijective ?",
              "Résoudre $\\varphi(P) = X^{3}$.",
              "Exprimer $\\varphi^{-1}$ à l'aide de $P, P', P'', P'''$."]],
          sol: [["q", "La dérivation diminue le degré : $\\varphi(P) \\in E$, et la linéarité est immédiate.",
            "$\\begin{pmatrix}1&-1&0&0\\\\0&1&-2&0\\\\0&0&1&-3\\\\0&0&0&1\\end{pmatrix}$.",
            "La matrice est triangulaire à diagonale non nulle : $\\ker\\varphi = \\{0\\}$ et $\\varphi$ est bijective.",
            "$P = X^{3} + 3X^{2} + 6X + 6$ (on remonte le système).",
            "Avec $D$ nilpotente d'indice $4$ : $\\varphi^{-1} = (\\mathrm{id}-D)^{-1} = \\mathrm{id} + D + D^{2} + D^{3}$, soit $\\varphi^{-1}(P) = P + P' + P'' + P'''$."]],
        },
        {
          t: "Matrices et rang", pts: 5, nom: "Problème",
          c: ["Soit $A = \\begin{pmatrix}1&1&1\\\\1&1&1\\\\1&1&1\\end{pmatrix}$.",
            ["q", "Calculer $A^{2}$ et en déduire $A^{\\,n}$ pour $n \\geqslant 1$.",
              "Déterminer le rang de $A$, puis $\\ker A$.",
              "$A$ est-elle inversible ?",
              "Déterminer les réels $\\lambda$ tels que $A - \\lambda I_{3}$ ne soit pas inversible."]],
          sol: [["q", "$A^{2} = 3A$ donc $A^{n} = 3^{\\,n-1}A$.",
            "Rang $1$ ; $\\ker A = \\{(x,y,z) : x+y+z = 0\\}$, de dimension $2$.",
            "Non : son rang est $1 < 3$.",
            "$A^{2} = 3A$ donne $A(A-3I) = 0$ : les valeurs propres possibles sont $0$ et $3$, et ce sont exactement les $\\lambda$ cherchés."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 3 — Complexes et arithmétique", st: "Racines de l'unité, congruences, dénombrement", h: 2, calc: "interdite",
      desc: "Un problème sur les racines de l'unité et un problème d'arithmétique.",
      ex: [
        {
          t: "Racines de l'unité", pts: 10, nom: "Problème",
          c: ["Soit $n \\geqslant 2$ et $\\mathbb{U}_{n}$ l'ensemble des racines $n$-ièmes de l'unité.",
            ["q", "Montrer que $\\mathbb{U}_{n}$ est un groupe pour la multiplication.",
              "Calculer $\\displaystyle\\sum_{z\\in\\mathbb{U}_{n}} z$ et $\\displaystyle\\prod_{z\\in\\mathbb{U}_{n}} z$.",
              "Montrer que $\\displaystyle\\prod_{k=1}^{n-1}\\left(1 - \\mathrm{e}^{2\\mathrm{i}k\\pi/n}\\right) = n$ (on utilisera $X^{n}-1 = \\prod (X - z)$).",
              "En déduire $\\displaystyle\\prod_{k=1}^{n-1}\\sin\\frac{k\\pi}{n} = \\frac{n}{2^{\\,n-1}}$."]],
          sol: [["q", "Stable par produit et inverse, contient $1$ : c'est un sous-groupe de $\\mathbb{C}^{*}$.",
            "La somme vaut $0$ (somme géométrique) ; le produit vaut $(-1)^{n+1}$ (produit des racines de $X^{n}-1$).",
            "$\\dfrac{X^{n}-1}{X-1} = \\displaystyle\\prod_{k=1}^{n-1}(X - z_{k})$ ; en évaluant en $X=1$ le membre de gauche vaut $n$.",
            "$1 - \\mathrm{e}^{2\\mathrm{i}k\\pi/n} = -2\\mathrm{i}\\sin\\!\\left(\\tfrac{k\\pi}{n}\\right)\\mathrm{e}^{\\mathrm{i}k\\pi/n}$ ; en prenant les modules dans l'égalité précédente, $2^{\\,n-1}\\displaystyle\\prod\\sin\\tfrac{k\\pi}{n} = n$."]],
        },
        {
          t: "Arithmétique", pts: 10, nom: "Problème",
          c: ["On s'intéresse aux entiers $a$ tels que $a^{2} \\equiv 1 \\ [8]$.",
            ["q", "Montrer que tout entier impair vérifie $a^{2}\\equiv 1\\ [8]$.",
              "En déduire que $x^{2} + y^{2} = 3z^{2}$ n'a pas de solution en entiers non tous nuls (on raisonnera modulo $3$ puis par descente infinie).",
              "Résoudre $17x \\equiv 5\\ [43]$.",
              "Déterminer tous les couples $(x,y) \\in \\mathbb{Z}^{2}$ tels que $12x + 18y = 30$."]],
          sol: [["q", "$a = 2k+1$ donne $a^{2} = 4k(k+1)+1$ et $k(k+1)$ est pair.",
            "Modulo $3$, un carré vaut $0$ ou $1$ : $x^{2}+y^{2}\\equiv 0\\ [3]$ impose $x\\equiv y\\equiv 0\\ [3]$. Alors $9$ divise $3z^{2}$, donc $3$ divise $z$ : le triplet $(x/3,\\,y/3,\\,z/3)$ est une solution strictement plus petite. Par descente infinie, seule la solution nulle existe.",
            "$17 \\times 38 = 646 = 15\\times43 + 1$ donc $17^{-1} \\equiv 38$ et $x \\equiv 38\\times5 = 190 \\equiv 190 - 4\\times43 = 18\\ [43]$.",
            "On divise par $6$ : $2x + 3y = 5$ ; solution particulière $(1,1)$, solutions : $x = 1+3k$, $y = 1-2k$, $k\\in\\mathbb{Z}$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 4 — Intégration et équations différentielles", st: "Calcul intégral, équations linéaires, modélisation", h: 2, calc: "interdite",
      desc: "Un problème d'intégrales à paramètre et un problème d'équations différentielles.",
      ex: [
        {
          t: "Intégrales à paramètre", pts: 10, nom: "Problème",
          c: ["Pour $x > 0$, on pose $F(x) = \\displaystyle\\int_{0}^{1}\\frac{\\mathrm{d}t}{x + t}$.",
            ["q", "Calculer $F(x)$ explicitement.",
              "Étudier les variations de $F$ et ses limites en $0^{+}$ et $+\\infty$.",
              "Donner un équivalent de $F(x)$ en $+\\infty$.",
              "Montrer que $F$ est convexe sur $]0\\,;\\,+\\infty[$.",
              "Calculer $\\displaystyle\\int_{1}^{2}F(x)\\,\\mathrm{d}x$."]],
          sol: [["q", "$F(x) = \\ln(x+1) - \\ln x = \\ln\\!\\left(1+\\tfrac{1}{x}\\right)$.",
            "$F' (x)= \\dfrac{1}{x+1}-\\dfrac{1}{x} < 0$ : $F$ décroît de $+\\infty$ (en $0^{+}$) à $0$ (en $+\\infty$).",
            "$F(x) \\sim \\dfrac{1}{x}$.",
            "$F''(x) = \\dfrac{1}{x^{2}} - \\dfrac{1}{(x+1)^{2}} > 0$ : $F$ est convexe.",
            "$\\displaystyle\\int_{1}^{2}\\big(\\ln(x+1)-\\ln x\\big)\\mathrm{d}x = \\big[(x+1)\\ln(x+1) - x\\ln x\\big]_{1}^{2} = 3\\ln 3 - 4\\ln 2$."]],
        },
        {
          t: "Circuit RLC", pts: 10, nom: "Problème",
          c: ["L'intensité $i(t)$ dans un circuit vérifie $i'' + 2\\lambda i' + \\omega_{0}^{2}\\,i = 0$, avec $\\lambda, \\omega_{0} > 0$.",
            ["q", "Résoudre l'équation lorsque $\\lambda < \\omega_{0}$ (régime pseudo-périodique).",
              "Résoudre lorsque $\\lambda = \\omega_{0}$ (régime critique).",
              "Résoudre lorsque $\\lambda > \\omega_{0}$ (régime apériodique).",
              "Dans le cas $\\lambda < \\omega_{0}$, avec $i(0) = 0$ et $i'(0) = 1$, déterminer la solution et sa pseudo-période.",
              "Montrer que dans tous les cas $i(t) \\to 0$."]],
          sol: [["q", "$r = -\\lambda \\pm \\mathrm{i}\\omega$ avec $\\omega = \\sqrt{\\omega_{0}^{2}-\\lambda^{2}}$ : $i(t) = \\mathrm{e}^{-\\lambda t}(A\\cos\\omega t + B\\sin\\omega t)$.",
            "Racine double $-\\lambda$ : $i(t) = (A + Bt)\\mathrm{e}^{-\\lambda t}$.",
            "Deux racines réelles négatives $r_{\\pm} = -\\lambda \\pm \\sqrt{\\lambda^{2}-\\omega_{0}^{2}}$ : $i(t) = A\\mathrm{e}^{r_{+}t} + B\\mathrm{e}^{r_{-}t}$.",
            "$A = 0$ et $B\\omega = 1$ : $i(t) = \\dfrac{\\mathrm{e}^{-\\lambda t}}{\\omega}\\sin(\\omega t)$, de pseudo-période $T = \\dfrac{2\\pi}{\\omega}$.",
            "Toutes les exponentielles ont un exposant de partie réelle strictement négative : $i(t) \\to 0$."]],
        },
      ],
    },
    {
      t: "Devoir surveillé n° 5 — Concours blanc", st: "Problème long : étude complète d'une suite de fonctions", h: 3, calc: "interdite",
      desc: "Un problème unique en quatre parties, format écrit de concours.",
      ex: [
        {
          t: "Autour de la fonction $x \\mapsto x^{n}\\mathrm{e}^{-x}$", pts: 20, nom: "Problème",
          c: ["Pour $n \\in \\mathbb{N}^{*}$, on pose $f_{n}(x) = x^{\\,n}\\mathrm{e}^{-x}$ sur $[0\\,;\\,+\\infty[$.",
            ["h", "Partie A — Étude de $f_{n}$"],
            ["q", "Calculer $f_{n}'(x)$ et dresser le tableau de variations de $f_{n}$.",
              "Montrer que $f_{n}$ atteint son maximum en $x = n$, et calculer $M_{n} = f_{n}(n)$.",
              "Déterminer $\\displaystyle\\lim_{x\\to+\\infty} f_{n}(x)$."],
            ["h", "Partie B — L'intégrale $I_{n}$"],
            ["q", "Justifier l'existence de $I_{n} = \\displaystyle\\int_{0}^{1}x^{\\,n}\\mathrm{e}^{-x}\\,\\mathrm{d}x$ et calculer $I_{0}$.",
              "Montrer que $I_{n+1} = (n+1)I_{n} - \\mathrm{e}^{-1}$.",
              "Montrer que $(I_{n})$ est décroissante et tend vers $0$.",
              "Donner un équivalent de $I_{n}$ en $+\\infty$."],
            ["h", "Partie C — Une suite définie par une équation"],
            ["q", "Montrer que pour $n \\geqslant 1$, l'équation $f_{n}(x) = 1$ admet exactement deux solutions sur $]0\\,;\\,+\\infty[$ dès que $M_{n} > 1$.",
              "Déterminer le plus petit entier $n$ tel que $M_{n} > 1$.",
              "On note $a_{n} < b_{n}$ ces deux solutions. Montrer que $a_{n} \\to 1$ et $b_{n}\\to+\\infty$."],
            ["h", "Partie D — Convexité"],
            ["q", "Calculer $f_{n}''$ et déterminer les points d'inflexion de la courbe de $f_{n}$.",
              "Tracer l'allure de la courbe pour $n = 2$."]],
          sol: [["h", "Partie A"],
            ["q", "$f_{n}'(x) = x^{\\,n-1}\\mathrm{e}^{-x}(n - x)$ : croissante sur $[0\\,;\\,n]$, décroissante ensuite.",
              "Le maximum est atteint en $x = n$ et vaut $M_{n} = n^{\\,n}\\mathrm{e}^{-n}$.",
              "$0$, par croissance comparée."],
            ["h", "Partie B"],
            ["q", "La fonction est continue sur $[0\\,;\\,1]$ ; $I_{0} = 1 - \\mathrm{e}^{-1}$.",
              "IPP avec $u = x^{\\,n+1}$ et $v' = \\mathrm{e}^{-x}$ : $I_{n+1} = \\big[-x^{n+1}\\mathrm{e}^{-x}\\big]_{0}^{1} + (n+1)I_{n} = -\\mathrm{e}^{-1} + (n+1)I_{n}$.",
              "Sur $[0\\,;\\,1]$, $x^{n+1}\\leqslant x^{n}$ ; et $0\\leqslant I_{n}\\leqslant \\displaystyle\\int_{0}^{1}x^{n}\\mathrm{d}x = \\tfrac{1}{n+1} \\to 0$.",
              "Sur $[0\\,;\\,1]$, $\\mathrm{e}^{-1} \\leqslant \\mathrm{e}^{-x}\\leqslant 1$ donne $\\dfrac{\\mathrm{e}^{-1}}{n+1}\\leqslant I_{n}\\leqslant\\dfrac{1}{n+1}$ ; plus finement, le poids se concentre en $x=1$ et $I_{n} \\sim \\dfrac{\\mathrm{e}^{-1}}{n}$."],
            ["h", "Partie C"],
            ["q", "$f_{n}$ est continue, strictement croissante de $0$ à $M_{n}$ sur $[0\\,;\\,n]$, puis strictement décroissante de $M_{n}$ à $0$ : si $M_{n} > 1$, le TVI donne exactement une solution sur chaque intervalle.",
              "$M_{n} > 1 \\iff n\\ln n > n \\iff \\ln n > 1 \\iff n \\geqslant 3$.",
              "L'équation s'écrit $n\\ln x = x$. Pour $a_{n} \\in \\,]0\\,;\\,n]$ : $\\ln a_{n} = \\tfrac{a_{n}}{n} \\leqslant 1$, donc $(a_{n})$ est bornée et $\\ln a_{n} \\to 0$, soit $a_{n} \\to 1$. Comme $b_{n} \\geqslant n$, on a $b_{n} \\to +\\infty$ (et même $b_{n} \\sim n\\ln n$)."],
            ["h", "Partie D"],
            ["q", "$f_{n}''(x) = x^{\\,n-2}\\mathrm{e}^{-x}\\big(x^{2} - 2nx + n(n-1)\\big)$, qui s'annule en $x = n \\pm \\sqrt{n}$ : deux points d'inflexion.",
              "Pour $n = 2$ : courbe partant de $0$, maximum $4\\mathrm{e}^{-2}\\approx 0{,}54$ en $x = 2$, inflexions en $2\\pm\\sqrt{2}$, puis décroissance vers $0$."]],
        },
      ],
    },
  ]);
})();
